var annotated_dup =
[
    [ "kcenon", "namespacekcenon.html", [
      [ "thread", "namespacekcenon_1_1thread.html", [
        [ "adapters", "namespacekcenon_1_1thread_1_1adapters.html", [
          [ "common_executor_factory", "classkcenon_1_1thread_1_1adapters_1_1common__executor__factory.html", "classkcenon_1_1thread_1_1adapters_1_1common__executor__factory" ],
          [ "thread_pool_executor_adapter", "classkcenon_1_1thread_1_1adapters_1_1thread__pool__executor__adapter.html", "classkcenon_1_1thread_1_1adapters_1_1thread__pool__executor__adapter" ]
        ] ],
        [ "concepts", "namespacekcenon_1_1thread_1_1concepts.html", [
          [ "callable_return_type", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type.html", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type" ],
          [ "callable_return_type< F, std::enable_if_t< std::is_invocable_v< F > > >", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type_3_01F_00_01std_1_1enable__if__t_3_0934ffa248d47f139931de1a3e7ea01d0.html", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type_3_01F_00_01std_1_1enable__if__t_3_0934ffa248d47f139931de1a3e7ea01d0" ],
          [ "has_get_method", "structkcenon_1_1thread_1_1concepts_1_1has__get__method.html", null ],
          [ "has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "structkcenon_1_1thread_1_1concepts_1_1has__get__method_3_01T_00_01std_1_1void__t_3_01decltype_07d869b6cf96acafc0ea1f11f421689910.html", null ],
          [ "has_wait_method", "structkcenon_1_1thread_1_1concepts_1_1has__wait__method.html", null ],
          [ "has_wait_method< T, std::void_t< decltype(std::declval< T >().wait())> >", "structkcenon_1_1thread_1_1concepts_1_1has__wait__method_3_01T_00_01std_1_1void__t_3_01decltype_05d3c12d9bfc583e0c6389f2921b80175.html", null ],
          [ "is_duration", "structkcenon_1_1thread_1_1concepts_1_1is__duration.html", null ],
          [ "is_duration< std::chrono::duration< Rep, Period > >", "structkcenon_1_1thread_1_1concepts_1_1is__duration_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_01_4.html", null ],
          [ "is_future_like", "structkcenon_1_1thread_1_1concepts_1_1is__future__like.html", null ],
          [ "is_nothrow_callable", "structkcenon_1_1thread_1_1concepts_1_1is__nothrow__callable.html", null ],
          [ "is_valid_job_type", "structkcenon_1_1thread_1_1concepts_1_1is__valid__job__type.html", null ],
          [ "is_valid_job_type< T, std::enable_if_t< JobType< T > > >", "structkcenon_1_1thread_1_1concepts_1_1is__valid__job__type_3_01T_00_01std_1_1enable__if__t_3_01JobType_3_01T_01_4_01_4_01_4.html", null ]
        ] ],
        [ "detail", "namespacekcenon_1_1thread_1_1detail.html", [
          [ "callable_eraser", "classkcenon_1_1thread_1_1detail_1_1callable__eraser.html", "classkcenon_1_1thread_1_1detail_1_1callable__eraser" ],
          [ "compile_string", "structkcenon_1_1thread_1_1detail_1_1compile__string.html", "structkcenon_1_1thread_1_1detail_1_1compile__string" ],
          [ "concurrent_queue", "classkcenon_1_1thread_1_1detail_1_1concurrent__queue.html", "classkcenon_1_1thread_1_1detail_1_1concurrent__queue" ],
          [ "conditional_feature", "structkcenon_1_1thread_1_1detail_1_1conditional__feature.html", "structkcenon_1_1thread_1_1detail_1_1conditional__feature" ],
          [ "constexpr_string", "structkcenon_1_1thread_1_1detail_1_1constexpr__string.html", "structkcenon_1_1thread_1_1detail_1_1constexpr__string" ],
          [ "function_traits", "structkcenon_1_1thread_1_1detail_1_1function__traits.html", null ],
          [ "function_traits< R(*)(Args...) noexcept >", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4.html", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4" ],
          [ "function_traits< R(*)(Args...)>", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4" ],
          [ "function_traits< R(C::*)(Args...) const >", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
          [ "function_traits< R(C::*)(Args...)>", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
          [ "future_value_type", "structkcenon_1_1thread_1_1detail_1_1future__value__type.html", "structkcenon_1_1thread_1_1detail_1_1future__value__type" ],
          [ "global_reclamation_manager", "classkcenon_1_1thread_1_1detail_1_1global__reclamation__manager.html", "classkcenon_1_1thread_1_1detail_1_1global__reclamation__manager" ],
          [ "has_bound_policy_tag", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__tag.html", null ],
          [ "has_bound_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__tag_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1policy__tag_01_4_01_4.html", null ],
          [ "has_bound_policy_type", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__type.html", null ],
          [ "has_bound_policy_type< T, std::void_t< typename T::bound_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__type_3_01T_00_01std_1_1void__t_3_01typen855d4214eb0f318dab7d3b857389f8a0.html", null ],
          [ "has_do_work_method", "structkcenon_1_1thread_1_1detail_1_1has__do__work__method.html", null ],
          [ "has_do_work_method< T, std::void_t< decltype(std::declval< T >().do_work())> >", "structkcenon_1_1thread_1_1detail_1_1has__do__work__method_3_01T_00_01std_1_1void__t_3_01decltype279da4895ca19f645443738873665ae7.html", null ],
          [ "has_get_method", "structkcenon_1_1thread_1_1detail_1_1has__get__method.html", null ],
          [ "has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "structkcenon_1_1thread_1_1detail_1_1has__get__method_3_01T_00_01std_1_1void__t_3_01decltype_07st2973351f2472797fc8429b46ac63ffb8.html", null ],
          [ "has_overflow_policy_tag", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__tag.html", null ],
          [ "has_overflow_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__tag_3_01T_00_01std_1_1void__t_3_01typ2b25af737181b619f5e96dad2dc19fc0.html", null ],
          [ "has_overflow_policy_type", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__type.html", null ],
          [ "has_overflow_policy_type< T, std::void_t< typename T::overflow_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__type_3_01T_00_01std_1_1void__t_3_01tyd833da87b23127ba287c43a16167794f.html", null ],
          [ "has_priority_method", "structkcenon_1_1thread_1_1detail_1_1has__priority__method.html", null ],
          [ "has_priority_method< T, std::void_t< decltype(std::declval< T >().priority())> >", "structkcenon_1_1thread_1_1detail_1_1has__priority__method_3_01T_00_01std_1_1void__t_3_01decltype1259939ce1df6e30ea7bdfeb245c14ca.html", null ],
          [ "has_sync_policy_tag", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__tag.html", null ],
          [ "has_sync_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__tag_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1policy__tag_01_4_01_4.html", null ],
          [ "has_sync_policy_type", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__type.html", null ],
          [ "has_sync_policy_type< T, std::void_t< typename T::sync_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__type_3_01T_00_01std_1_1void__t_3_01typena93cedef5780fa3e844c7d4b967dd5a13.html", null ],
          [ "hazard_pointer_registry", "classkcenon_1_1thread_1_1detail_1_1hazard__pointer__registry.html", "classkcenon_1_1thread_1_1detail_1_1hazard__pointer__registry" ],
          [ "is_compatible_job", "structkcenon_1_1thread_1_1detail_1_1is__compatible__job.html", null ],
          [ "is_compatible_job< Job, ExpectedJobType >", "structkcenon_1_1thread_1_1detail_1_1is__compatible__job_3_01Job_00_01ExpectedJobType_01_4.html", "structkcenon_1_1thread_1_1detail_1_1is__compatible__job_3_01Job_00_01ExpectedJobType_01_4" ],
          [ "is_policy_queue_impl", "structkcenon_1_1thread_1_1detail_1_1is__policy__queue__impl.html", null ],
          [ "is_policy_queue_impl< policy_queue< SyncPolicy, BoundPolicy, OverflowPolicy > >", "structkcenon_1_1thread_1_1detail_1_1is__policy__queue__impl_3_01policy__queue_3_01SyncPolicy_00_e091157b5e63405d7e768a64a3750f7f.html", null ],
          [ "job_eraser", "classkcenon_1_1thread_1_1detail_1_1job__eraser.html", "classkcenon_1_1thread_1_1detail_1_1job__eraser" ],
          [ "job_type_extractor", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor.html", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor" ],
          [ "job_type_extractor< T >", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor_3_01T_01_4.html", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor_3_01T_01_4" ],
          [ "job_type_list", "structkcenon_1_1thread_1_1detail_1_1job__type__list.html", "structkcenon_1_1thread_1_1detail_1_1job__type__list" ],
          [ "job_type_traits", "structkcenon_1_1thread_1_1detail_1_1job__type__traits.html", "structkcenon_1_1thread_1_1detail_1_1job__type__traits" ],
          [ "job_validator", "structkcenon_1_1thread_1_1detail_1_1job__validator.html", "structkcenon_1_1thread_1_1detail_1_1job__validator" ],
          [ "lockfree_job_queue", "classkcenon_1_1thread_1_1detail_1_1lockfree__job__queue.html", "classkcenon_1_1thread_1_1detail_1_1lockfree__job__queue" ],
          [ "priority_comparator", "structkcenon_1_1thread_1_1detail_1_1priority__comparator.html", "structkcenon_1_1thread_1_1detail_1_1priority__comparator" ],
          [ "retire_node", "structkcenon_1_1thread_1_1detail_1_1retire__node.html", "structkcenon_1_1thread_1_1detail_1_1retire__node" ],
          [ "thread_hazard_list", "structkcenon_1_1thread_1_1detail_1_1thread__hazard__list.html", "structkcenon_1_1thread_1_1detail_1_1thread__hazard__list" ],
          [ "thread_impl", "classkcenon_1_1thread_1_1detail_1_1thread__impl.html", "classkcenon_1_1thread_1_1detail_1_1thread__impl" ],
          [ "validate_thread_count", "structkcenon_1_1thread_1_1detail_1_1validate__thread__count.html", "structkcenon_1_1thread_1_1detail_1_1validate__thread__count" ]
        ] ],
        [ "diagnostics", "namespacekcenon_1_1thread_1_1diagnostics.html", [
          [ "bottleneck_report", "structkcenon_1_1thread_1_1diagnostics_1_1bottleneck__report.html", "structkcenon_1_1thread_1_1diagnostics_1_1bottleneck__report" ],
          [ "component_health", "structkcenon_1_1thread_1_1diagnostics_1_1component__health.html", "structkcenon_1_1thread_1_1diagnostics_1_1component__health" ],
          [ "diagnostics_config", "structkcenon_1_1thread_1_1diagnostics_1_1diagnostics__config.html", "structkcenon_1_1thread_1_1diagnostics_1_1diagnostics__config" ],
          [ "execution_event_listener", "classkcenon_1_1thread_1_1diagnostics_1_1execution__event__listener.html", "classkcenon_1_1thread_1_1diagnostics_1_1execution__event__listener" ],
          [ "health_status", "structkcenon_1_1thread_1_1diagnostics_1_1health__status.html", "structkcenon_1_1thread_1_1diagnostics_1_1health__status" ],
          [ "health_thresholds", "structkcenon_1_1thread_1_1diagnostics_1_1health__thresholds.html", "structkcenon_1_1thread_1_1diagnostics_1_1health__thresholds" ],
          [ "job_execution_event", "structkcenon_1_1thread_1_1diagnostics_1_1job__execution__event.html", "structkcenon_1_1thread_1_1diagnostics_1_1job__execution__event" ],
          [ "job_info", "structkcenon_1_1thread_1_1diagnostics_1_1job__info.html", "structkcenon_1_1thread_1_1diagnostics_1_1job__info" ],
          [ "thread_info", "structkcenon_1_1thread_1_1diagnostics_1_1thread__info.html", "structkcenon_1_1thread_1_1diagnostics_1_1thread__info" ],
          [ "thread_pool_diagnostics", "classkcenon_1_1thread_1_1diagnostics_1_1thread__pool__diagnostics.html", "classkcenon_1_1thread_1_1diagnostics_1_1thread__pool__diagnostics" ]
        ] ],
        [ "jobs", "namespacekcenon_1_1thread_1_1jobs.html", [
          [ "job_interface", "classkcenon_1_1thread_1_1jobs_1_1job__interface.html", "classkcenon_1_1thread_1_1jobs_1_1job__interface" ]
        ] ],
        [ "lockfree", "namespacekcenon_1_1thread_1_1lockfree.html", [
          [ "circular_array", "classkcenon_1_1thread_1_1lockfree_1_1circular__array.html", "classkcenon_1_1thread_1_1lockfree_1_1circular__array" ],
          [ "work_stealing_deque", "classkcenon_1_1thread_1_1lockfree_1_1work__stealing__deque.html", "classkcenon_1_1thread_1_1lockfree_1_1work__stealing__deque" ]
        ] ],
        [ "metrics", "namespacekcenon_1_1thread_1_1metrics.html", [
          [ "BackendRegistry", "classkcenon_1_1thread_1_1metrics_1_1BackendRegistry.html", "classkcenon_1_1thread_1_1metrics_1_1BackendRegistry" ],
          [ "BaseSnapshot", "structkcenon_1_1thread_1_1metrics_1_1BaseSnapshot.html", "structkcenon_1_1thread_1_1metrics_1_1BaseSnapshot" ],
          [ "EnhancedSnapshot", "structkcenon_1_1thread_1_1metrics_1_1EnhancedSnapshot.html", "structkcenon_1_1thread_1_1metrics_1_1EnhancedSnapshot" ],
          [ "EnhancedThreadPoolMetrics", "classkcenon_1_1thread_1_1metrics_1_1EnhancedThreadPoolMetrics.html", "classkcenon_1_1thread_1_1metrics_1_1EnhancedThreadPoolMetrics" ],
          [ "JsonBackend", "classkcenon_1_1thread_1_1metrics_1_1JsonBackend.html", "classkcenon_1_1thread_1_1metrics_1_1JsonBackend" ],
          [ "LatencyHistogram", "classkcenon_1_1thread_1_1metrics_1_1LatencyHistogram.html", "classkcenon_1_1thread_1_1metrics_1_1LatencyHistogram" ],
          [ "LoggingBackend", "classkcenon_1_1thread_1_1metrics_1_1LoggingBackend.html", "classkcenon_1_1thread_1_1metrics_1_1LoggingBackend" ],
          [ "metrics_service", "classkcenon_1_1thread_1_1metrics_1_1metrics__service.html", "classkcenon_1_1thread_1_1metrics_1_1metrics__service" ],
          [ "MetricsBackend", "classkcenon_1_1thread_1_1metrics_1_1MetricsBackend.html", "classkcenon_1_1thread_1_1metrics_1_1MetricsBackend" ],
          [ "MetricsBase", "classkcenon_1_1thread_1_1metrics_1_1MetricsBase.html", "classkcenon_1_1thread_1_1metrics_1_1MetricsBase" ],
          [ "PrometheusBackend", "classkcenon_1_1thread_1_1metrics_1_1PrometheusBackend.html", "classkcenon_1_1thread_1_1metrics_1_1PrometheusBackend" ],
          [ "SlidingWindowCounter", "classkcenon_1_1thread_1_1metrics_1_1SlidingWindowCounter.html", "classkcenon_1_1thread_1_1metrics_1_1SlidingWindowCounter" ],
          [ "ThreadPoolMetrics", "classkcenon_1_1thread_1_1metrics_1_1ThreadPoolMetrics.html", "classkcenon_1_1thread_1_1metrics_1_1ThreadPoolMetrics" ],
          [ "WorkerMetrics", "structkcenon_1_1thread_1_1metrics_1_1WorkerMetrics.html", "structkcenon_1_1thread_1_1metrics_1_1WorkerMetrics" ]
        ] ],
        [ "platform", "namespacekcenon_1_1thread_1_1platform.html", [
          [ "system_info", "structkcenon_1_1thread_1_1platform_1_1system__info.html", "structkcenon_1_1thread_1_1platform_1_1system__info" ]
        ] ],
        [ "policies", "namespacekcenon_1_1thread_1_1policies.html", [
          [ "adaptive_sync_policy", "classkcenon_1_1thread_1_1policies_1_1adaptive__sync__policy.html", "classkcenon_1_1thread_1_1policies_1_1adaptive__sync__policy" ],
          [ "bound_policy_tag", "structkcenon_1_1thread_1_1policies_1_1bound__policy__tag.html", null ],
          [ "bounded_policy", "classkcenon_1_1thread_1_1policies_1_1bounded__policy.html", "classkcenon_1_1thread_1_1policies_1_1bounded__policy" ],
          [ "dynamic_bounded_policy", "classkcenon_1_1thread_1_1policies_1_1dynamic__bounded__policy.html", "classkcenon_1_1thread_1_1policies_1_1dynamic__bounded__policy" ],
          [ "lockfree_sync_policy", "classkcenon_1_1thread_1_1policies_1_1lockfree__sync__policy.html", "classkcenon_1_1thread_1_1policies_1_1lockfree__sync__policy" ],
          [ "mutex_sync_policy", "classkcenon_1_1thread_1_1policies_1_1mutex__sync__policy.html", "classkcenon_1_1thread_1_1policies_1_1mutex__sync__policy" ],
          [ "overflow_block_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__block__policy.html", "classkcenon_1_1thread_1_1policies_1_1overflow__block__policy" ],
          [ "overflow_drop_newest_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__newest__policy.html", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__newest__policy" ],
          [ "overflow_drop_oldest_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__oldest__policy.html", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__oldest__policy" ],
          [ "overflow_policy_tag", "structkcenon_1_1thread_1_1policies_1_1overflow__policy__tag.html", null ],
          [ "overflow_reject_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__reject__policy.html", "classkcenon_1_1thread_1_1policies_1_1overflow__reject__policy" ],
          [ "overflow_timeout_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__timeout__policy.html", "classkcenon_1_1thread_1_1policies_1_1overflow__timeout__policy" ],
          [ "sync_policy_tag", "structkcenon_1_1thread_1_1policies_1_1sync__policy__tag.html", null ],
          [ "unbounded_policy", "classkcenon_1_1thread_1_1policies_1_1unbounded__policy.html", "classkcenon_1_1thread_1_1policies_1_1unbounded__policy" ]
        ] ],
        [ "sync", "namespacekcenon_1_1thread_1_1sync.html", [
          [ "atomic_flag_wrapper", "classkcenon_1_1thread_1_1sync_1_1atomic__flag__wrapper.html", "classkcenon_1_1thread_1_1sync_1_1atomic__flag__wrapper" ],
          [ "condition_variable_wrapper", "classkcenon_1_1thread_1_1sync_1_1condition__variable__wrapper.html", "classkcenon_1_1thread_1_1sync_1_1condition__variable__wrapper" ],
          [ "scoped_lock_guard", "classkcenon_1_1thread_1_1sync_1_1scoped__lock__guard.html", "classkcenon_1_1thread_1_1sync_1_1scoped__lock__guard" ],
          [ "shared_mutex_wrapper", "classkcenon_1_1thread_1_1sync_1_1shared__mutex__wrapper.html", "classkcenon_1_1thread_1_1sync_1_1shared__mutex__wrapper" ]
        ] ],
        [ "utils", "namespacekcenon_1_1thread_1_1utils.html", [
          [ "enum_formatter", "classkcenon_1_1thread_1_1utils_1_1enum__formatter.html", "classkcenon_1_1thread_1_1utils_1_1enum__formatter" ],
          [ "formatter", "classkcenon_1_1thread_1_1utils_1_1formatter.html", "classkcenon_1_1thread_1_1utils_1_1formatter" ]
        ] ],
        [ "adaptive_job_queue", "classkcenon_1_1thread_1_1adaptive__job__queue.html", "classkcenon_1_1thread_1_1adaptive__job__queue" ],
        [ "aged_priority", "structkcenon_1_1thread_1_1aged__priority.html", "structkcenon_1_1thread_1_1aged__priority" ],
        [ "aging_stats", "structkcenon_1_1thread_1_1aging__stats.html", "structkcenon_1_1thread_1_1aging__stats" ],
        [ "aging_typed_job_queue_t", "classkcenon_1_1thread_1_1aging__typed__job__queue__t.html", "classkcenon_1_1thread_1_1aging__typed__job__queue__t" ],
        [ "aging_typed_job_t", "classkcenon_1_1thread_1_1aging__typed__job__t.html", "classkcenon_1_1thread_1_1aging__typed__job__t" ],
        [ "atomic_shared_ptr", "classkcenon_1_1thread_1_1atomic__shared__ptr.html", "classkcenon_1_1thread_1_1atomic__shared__ptr" ],
        [ "atomic_wait_helper", "classkcenon_1_1thread_1_1atomic__wait__helper.html", "classkcenon_1_1thread_1_1atomic__wait__helper" ],
        [ "atomic_with_wait", "classkcenon_1_1thread_1_1atomic__with__wait.html", "classkcenon_1_1thread_1_1atomic__with__wait" ],
        [ "autoscaler", "classkcenon_1_1thread_1_1autoscaler.html", "classkcenon_1_1thread_1_1autoscaler" ],
        [ "autoscaling_policy", "structkcenon_1_1thread_1_1autoscaling__policy.html", "structkcenon_1_1thread_1_1autoscaling__policy" ],
        [ "autoscaling_pool_policy", "classkcenon_1_1thread_1_1autoscaling__pool__policy.html", "classkcenon_1_1thread_1_1autoscaling__pool__policy" ],
        [ "autoscaling_stats", "structkcenon_1_1thread_1_1autoscaling__stats.html", "structkcenon_1_1thread_1_1autoscaling__stats" ],
        [ "backoff_calculator", "classkcenon_1_1thread_1_1backoff__calculator.html", "classkcenon_1_1thread_1_1backoff__calculator" ],
        [ "backpressure_config", "structkcenon_1_1thread_1_1backpressure__config.html", "structkcenon_1_1thread_1_1backpressure__config" ],
        [ "backpressure_job_queue", "classkcenon_1_1thread_1_1backpressure__job__queue.html", "classkcenon_1_1thread_1_1backpressure__job__queue" ],
        [ "backpressure_stats", "structkcenon_1_1thread_1_1backpressure__stats.html", "structkcenon_1_1thread_1_1backpressure__stats" ],
        [ "backpressure_stats_snapshot", "structkcenon_1_1thread_1_1backpressure__stats__snapshot.html", "structkcenon_1_1thread_1_1backpressure__stats__snapshot" ],
        [ "barrier", "classkcenon_1_1thread_1_1barrier.html", "classkcenon_1_1thread_1_1barrier" ],
        [ "callback_job", "classkcenon_1_1thread_1_1callback__job.html", "classkcenon_1_1thread_1_1callback__job" ],
        [ "callback_typed_job_t", "classkcenon_1_1thread_1_1callback__typed__job__t.html", "classkcenon_1_1thread_1_1callback__typed__job__t" ],
        [ "cancellable_future", "classkcenon_1_1thread_1_1cancellable__future.html", "classkcenon_1_1thread_1_1cancellable__future" ],
        [ "cancellable_future< void >", "classkcenon_1_1thread_1_1cancellable__future_3_01void_01_4.html", "classkcenon_1_1thread_1_1cancellable__future_3_01void_01_4" ],
        [ "cancellation_callback_guard", "classkcenon_1_1thread_1_1cancellation__callback__guard.html", "classkcenon_1_1thread_1_1cancellation__callback__guard" ],
        [ "cancellation_context", "classkcenon_1_1thread_1_1cancellation__context.html", "classkcenon_1_1thread_1_1cancellation__context" ],
        [ "cancellation_reason", "structkcenon_1_1thread_1_1cancellation__reason.html", "structkcenon_1_1thread_1_1cancellation__reason" ],
        [ "cancellation_scope", "classkcenon_1_1thread_1_1cancellation__scope.html", "classkcenon_1_1thread_1_1cancellation__scope" ],
        [ "cancellation_token", "classkcenon_1_1thread_1_1cancellation__token.html", "classkcenon_1_1thread_1_1cancellation__token" ],
        [ "circuit_breaker_policy", "classkcenon_1_1thread_1_1circuit__breaker__policy.html", "classkcenon_1_1thread_1_1circuit__breaker__policy" ],
        [ "config_builder", "classkcenon_1_1thread_1_1config__builder.html", "classkcenon_1_1thread_1_1config__builder" ],
        [ "config_changed_event", "structkcenon_1_1thread_1_1config__changed__event.html", "structkcenon_1_1thread_1_1config__changed__event" ],
        [ "configuration_manager", "classkcenon_1_1thread_1_1configuration__manager.html", "classkcenon_1_1thread_1_1configuration__manager" ],
        [ "crash_context", "structkcenon_1_1thread_1_1crash__context.html", "structkcenon_1_1thread_1_1crash__context" ],
        [ "crash_handler", "classkcenon_1_1thread_1_1crash__handler.html", "classkcenon_1_1thread_1_1crash__handler" ],
        [ "dag_config", "structkcenon_1_1thread_1_1dag__config.html", "structkcenon_1_1thread_1_1dag__config" ],
        [ "dag_job", "classkcenon_1_1thread_1_1dag__job.html", "classkcenon_1_1thread_1_1dag__job" ],
        [ "dag_job_builder", "classkcenon_1_1thread_1_1dag__job__builder.html", "classkcenon_1_1thread_1_1dag__job__builder" ],
        [ "dag_job_info", "structkcenon_1_1thread_1_1dag__job__info.html", "structkcenon_1_1thread_1_1dag__job__info" ],
        [ "dag_scheduler", "classkcenon_1_1thread_1_1dag__scheduler.html", "classkcenon_1_1thread_1_1dag__scheduler" ],
        [ "dag_stats", "structkcenon_1_1thread_1_1dag__stats.html", "structkcenon_1_1thread_1_1dag__stats" ],
        [ "default_error_handler", "classkcenon_1_1thread_1_1default__error__handler.html", "classkcenon_1_1thread_1_1default__error__handler" ],
        [ "enhanced_cancellation_token", "classkcenon_1_1thread_1_1enhanced__cancellation__token.html", "classkcenon_1_1thread_1_1enhanced__cancellation__token" ],
        [ "enhanced_work_stealing_config", "structkcenon_1_1thread_1_1enhanced__work__stealing__config.html", "structkcenon_1_1thread_1_1enhanced__work__stealing__config" ],
        [ "error", "classkcenon_1_1thread_1_1error.html", "classkcenon_1_1thread_1_1error" ],
        [ "error_handler", "classkcenon_1_1thread_1_1error__handler.html", "classkcenon_1_1thread_1_1error__handler" ],
        [ "event_base", "classkcenon_1_1thread_1_1event__base.html", "classkcenon_1_1thread_1_1event__base" ],
        [ "event_bus", "classkcenon_1_1thread_1_1event__bus.html", "classkcenon_1_1thread_1_1event__bus" ],
        [ "future_job", "classkcenon_1_1thread_1_1future__job.html", "classkcenon_1_1thread_1_1future__job" ],
        [ "has_blocking_overflow", "structkcenon_1_1thread_1_1has__blocking__overflow.html", null ],
        [ "has_blocking_overflow< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1has__blocking__overflow_3_01T_00_01std_1_1enable__if__t_3_01policy__qu2578a9953134c095edab50d2ce8b7484.html", "structkcenon_1_1thread_1_1has__blocking__overflow_3_01T_00_01std_1_1enable__if__t_3_01policy__qu2578a9953134c095edab50d2ce8b7484" ],
        [ "hazard_pointer", "classkcenon_1_1thread_1_1hazard__pointer.html", "classkcenon_1_1thread_1_1hazard__pointer" ],
        [ "hazard_pointer_domain", "classkcenon_1_1thread_1_1hazard__pointer__domain.html", "classkcenon_1_1thread_1_1hazard__pointer__domain" ],
        [ "is_bounded_queue", "structkcenon_1_1thread_1_1is__bounded__queue.html", null ],
        [ "is_bounded_queue< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1is__bounded__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue__6d81250e1ad6a165a566bf9432592958.html", "structkcenon_1_1thread_1_1is__bounded__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue__6d81250e1ad6a165a566bf9432592958" ],
        [ "is_lockfree_queue", "structkcenon_1_1thread_1_1is__lockfree__queue.html", null ],
        [ "is_lockfree_queue< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1is__lockfree__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue_0a64f444c12908d9268f79b4e4314f7a.html", "structkcenon_1_1thread_1_1is__lockfree__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue_0a64f444c12908d9268f79b4e4314f7a" ],
        [ "job", "classkcenon_1_1thread_1_1job.html", "classkcenon_1_1thread_1_1job" ],
        [ "job_builder", "classkcenon_1_1thread_1_1job__builder.html", "classkcenon_1_1thread_1_1job__builder" ],
        [ "job_components", "structkcenon_1_1thread_1_1job__components.html", "structkcenon_1_1thread_1_1job__components" ],
        [ "job_info", "structkcenon_1_1thread_1_1job__info.html", "structkcenon_1_1thread_1_1job__info" ],
        [ "job_queue", "classkcenon_1_1thread_1_1job__queue.html", "classkcenon_1_1thread_1_1job__queue" ],
        [ "job_queue_adapter", "classkcenon_1_1thread_1_1job__queue__adapter.html", "classkcenon_1_1thread_1_1job__queue__adapter" ],
        [ "latch", "classkcenon_1_1thread_1_1latch.html", "classkcenon_1_1thread_1_1latch" ],
        [ "lifecycle_controller", "classkcenon_1_1thread_1_1lifecycle__controller.html", "classkcenon_1_1thread_1_1lifecycle__controller" ],
        [ "module_version", "structkcenon_1_1thread_1_1module__version.html", "structkcenon_1_1thread_1_1module__version" ],
        [ "numa_node", "structkcenon_1_1thread_1_1numa__node.html", "structkcenon_1_1thread_1_1numa__node" ],
        [ "numa_thread_pool", "classkcenon_1_1thread_1_1numa__thread__pool.html", "classkcenon_1_1thread_1_1numa__thread__pool" ],
        [ "numa_topology", "classkcenon_1_1thread_1_1numa__topology.html", "classkcenon_1_1thread_1_1numa__topology" ],
        [ "numa_work_stealer", "classkcenon_1_1thread_1_1numa__work__stealer.html", "classkcenon_1_1thread_1_1numa__work__stealer" ],
        [ "operation_cancelled_exception", "classkcenon_1_1thread_1_1operation__cancelled__exception.html", "classkcenon_1_1thread_1_1operation__cancelled__exception" ],
        [ "performance_alert_event", "structkcenon_1_1thread_1_1performance__alert__event.html", "structkcenon_1_1thread_1_1performance__alert__event" ],
        [ "policy_queue", "classkcenon_1_1thread_1_1policy__queue.html", "classkcenon_1_1thread_1_1policy__queue" ],
        [ "policy_queue_adapter", "classkcenon_1_1thread_1_1policy__queue__adapter.html", "classkcenon_1_1thread_1_1policy__queue__adapter" ],
        [ "policy_queue_traits", "structkcenon_1_1thread_1_1policy__queue__traits.html", "structkcenon_1_1thread_1_1policy__queue__traits" ],
        [ "policy_queue_traits< T, std::enable_if_t< detail::has_sync_policy_type< T >::value &&detail::has_bound_policy_type< T >::value &&detail::has_overflow_policy_type< T >::value > >", "structkcenon_1_1thread_1_1policy__queue__traits_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1haeec5129467d87996fbc20a79b22278eb.html", "structkcenon_1_1thread_1_1policy__queue__traits_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1haeec5129467d87996fbc20a79b22278eb" ],
        [ "pool_future", "classkcenon_1_1thread_1_1pool__future.html", "classkcenon_1_1thread_1_1pool__future" ],
        [ "pool_policy", "classkcenon_1_1thread_1_1pool__policy.html", "classkcenon_1_1thread_1_1pool__policy" ],
        [ "pool_promise", "classkcenon_1_1thread_1_1pool__promise.html", "classkcenon_1_1thread_1_1pool__promise" ],
        [ "pool_promise< void >", "classkcenon_1_1thread_1_1pool__promise_3_01void_01_4.html", "classkcenon_1_1thread_1_1pool__promise_3_01void_01_4" ],
        [ "pool_queue_adapter_interface", "classkcenon_1_1thread_1_1pool__queue__adapter__interface.html", "classkcenon_1_1thread_1_1pool__queue__adapter__interface" ],
        [ "priority_aging_config", "structkcenon_1_1thread_1_1priority__aging__config.html", "structkcenon_1_1thread_1_1priority__aging__config" ],
        [ "protected_job", "classkcenon_1_1thread_1_1protected__job.html", "classkcenon_1_1thread_1_1protected__job" ],
        [ "queue_capabilities", "structkcenon_1_1thread_1_1queue__capabilities.html", "structkcenon_1_1thread_1_1queue__capabilities" ],
        [ "queue_capabilities_interface", "classkcenon_1_1thread_1_1queue__capabilities__interface.html", "classkcenon_1_1thread_1_1queue__capabilities__interface" ],
        [ "queue_factory", "classkcenon_1_1thread_1_1queue__factory.html", "classkcenon_1_1thread_1_1queue__factory" ],
        [ "queue_type_selector", "structkcenon_1_1thread_1_1queue__type__selector.html", "structkcenon_1_1thread_1_1queue__type__selector" ],
        [ "result", "classkcenon_1_1thread_1_1result.html", "classkcenon_1_1thread_1_1result" ],
        [ "result< void >", "classkcenon_1_1thread_1_1result_3_01void_01_4.html", "classkcenon_1_1thread_1_1result_3_01void_01_4" ],
        [ "result_void", "classkcenon_1_1thread_1_1result__void.html", "classkcenon_1_1thread_1_1result__void" ],
        [ "retry_policy", "classkcenon_1_1thread_1_1retry__policy.html", "classkcenon_1_1thread_1_1retry__policy" ],
        [ "safe_hazard_guard", "classkcenon_1_1thread_1_1safe__hazard__guard.html", "classkcenon_1_1thread_1_1safe__hazard__guard" ],
        [ "safe_hazard_pointer_domain", "classkcenon_1_1thread_1_1safe__hazard__pointer__domain.html", "classkcenon_1_1thread_1_1safe__hazard__pointer__domain" ],
        [ "safe_hazard_pointer_record", "classkcenon_1_1thread_1_1safe__hazard__pointer__record.html", "classkcenon_1_1thread_1_1safe__hazard__pointer__record" ],
        [ "scaling_decision", "structkcenon_1_1thread_1_1scaling__decision.html", "structkcenon_1_1thread_1_1scaling__decision" ],
        [ "scaling_metrics_sample", "structkcenon_1_1thread_1_1scaling__metrics__sample.html", "structkcenon_1_1thread_1_1scaling__metrics__sample" ],
        [ "scheduler_interface", "classkcenon_1_1thread_1_1scheduler__interface.html", "classkcenon_1_1thread_1_1scheduler__interface" ],
        [ "scoped_crash_callback", "classkcenon_1_1thread_1_1scoped__crash__callback.html", "classkcenon_1_1thread_1_1scoped__crash__callback" ],
        [ "scoped_service", "classkcenon_1_1thread_1_1scoped__service.html", "classkcenon_1_1thread_1_1scoped__service" ],
        [ "service_container", "classkcenon_1_1thread_1_1service__container.html", "classkcenon_1_1thread_1_1service__container" ],
        [ "service_registry", "classkcenon_1_1thread_1_1service__registry.html", "classkcenon_1_1thread_1_1service__registry" ],
        [ "steal_backoff_config", "structkcenon_1_1thread_1_1steal__backoff__config.html", "structkcenon_1_1thread_1_1steal__backoff__config" ],
        [ "submit_options", "structkcenon_1_1thread_1_1submit__options.html", "structkcenon_1_1thread_1_1submit__options" ],
        [ "system_shutdown_event", "structkcenon_1_1thread_1_1system__shutdown__event.html", "structkcenon_1_1thread_1_1system__shutdown__event" ],
        [ "system_startup_event", "structkcenon_1_1thread_1_1system__startup__event.html", "structkcenon_1_1thread_1_1system__startup__event" ],
        [ "thread_base", "classkcenon_1_1thread_1_1thread__base.html", "classkcenon_1_1thread_1_1thread__base" ],
        [ "thread_context", "classkcenon_1_1thread_1_1thread__context.html", "classkcenon_1_1thread_1_1thread__context" ],
        [ "thread_context_builder", "classkcenon_1_1thread_1_1thread__context__builder.html", "classkcenon_1_1thread_1_1thread__context__builder" ],
        [ "thread_error_category", "classkcenon_1_1thread_1_1thread__error__category.html", "classkcenon_1_1thread_1_1thread__error__category" ],
        [ "thread_logger", "classkcenon_1_1thread_1_1thread__logger.html", "classkcenon_1_1thread_1_1thread__logger" ],
        [ "thread_pool", "classkcenon_1_1thread_1_1thread__pool.html", "classkcenon_1_1thread_1_1thread__pool" ],
        [ "thread_pool_builder", "classkcenon_1_1thread_1_1thread__pool__builder.html", "classkcenon_1_1thread_1_1thread__pool__builder" ],
        [ "thread_pool_crash_safety", "classkcenon_1_1thread_1_1thread__pool__crash__safety.html", "classkcenon_1_1thread_1_1thread__pool__crash__safety" ],
        [ "thread_system_config", "structkcenon_1_1thread_1_1thread__system__config.html", "structkcenon_1_1thread_1_1thread__system__config" ],
        [ "thread_worker", "classkcenon_1_1thread_1_1thread__worker.html", "classkcenon_1_1thread_1_1thread__worker" ],
        [ "token_bucket", "classkcenon_1_1thread_1_1token__bucket.html", "classkcenon_1_1thread_1_1token__bucket" ],
        [ "typed_job_factory_interface", "classkcenon_1_1thread_1_1typed__job__factory__interface.html", "classkcenon_1_1thread_1_1typed__job__factory__interface" ],
        [ "typed_job_interface", "classkcenon_1_1thread_1_1typed__job__interface.html", "classkcenon_1_1thread_1_1typed__job__interface" ],
        [ "typed_job_t", "classkcenon_1_1thread_1_1typed__job__t.html", "classkcenon_1_1thread_1_1typed__job__t" ],
        [ "typed_safe_hazard_domain", "classkcenon_1_1thread_1_1typed__safe__hazard__domain.html", "classkcenon_1_1thread_1_1typed__safe__hazard__domain" ],
        [ "typed_thread_pool_builder", "classkcenon_1_1thread_1_1typed__thread__pool__builder.html", "classkcenon_1_1thread_1_1typed__thread__pool__builder" ],
        [ "typed_thread_pool_t", "classkcenon_1_1thread_1_1typed__thread__pool__t.html", "classkcenon_1_1thread_1_1typed__thread__pool__t" ],
        [ "typed_thread_worker_t", "classkcenon_1_1thread_1_1typed__thread__worker__t.html", "classkcenon_1_1thread_1_1typed__thread__worker__t" ],
        [ "validation_result", "structkcenon_1_1thread_1_1validation__result.html", "structkcenon_1_1thread_1_1validation__result" ],
        [ "work_affinity_tracker", "classkcenon_1_1thread_1_1work__affinity__tracker.html", "classkcenon_1_1thread_1_1work__affinity__tracker" ],
        [ "work_stealing_pool_policy", "classkcenon_1_1thread_1_1work__stealing__pool__policy.html", "classkcenon_1_1thread_1_1work__stealing__pool__policy" ],
        [ "work_stealing_stats", "structkcenon_1_1thread_1_1work__stealing__stats.html", "structkcenon_1_1thread_1_1work__stealing__stats" ],
        [ "work_stealing_stats_snapshot", "structkcenon_1_1thread_1_1work__stealing__stats__snapshot.html", "structkcenon_1_1thread_1_1work__stealing__stats__snapshot" ],
        [ "worker_policy", "structkcenon_1_1thread_1_1worker__policy.html", "structkcenon_1_1thread_1_1worker__policy" ]
      ] ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "formatter< kcenon::thread::job_queue >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_01_4" ],
      [ "formatter< kcenon::thread::job_queue, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::job_types >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_01_4" ],
      [ "formatter< kcenon::thread::job_types, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::thread_conditions >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_01_4" ],
      [ "formatter< kcenon::thread::thread_conditions, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::thread_pool >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_01_4" ],
      [ "formatter< kcenon::thread::thread_pool, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::thread_worker >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_01_4" ],
      [ "formatter< kcenon::thread::thread_worker, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::typed_thread_pool_t< job_type > >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_01_4" ],
      [ "formatter< kcenon::thread::typed_thread_pool_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_00_01wchar__t_01_4" ],
      [ "formatter< kcenon::thread::typed_thread_worker_t< job_type > >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_01_4" ],
      [ "formatter< kcenon::thread::typed_thread_worker_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_00_01wchar__t_01_4" ],
      [ "formatter< test_priority >", "structstd_1_1formatter_3_01test__priority_01_4.html", "structstd_1_1formatter_3_01test__priority_01_4" ],
      [ "formatter< test_priority, wchar_t >", "structstd_1_1formatter_3_01test__priority_00_01wchar__t_01_4.html", "structstd_1_1formatter_3_01test__priority_00_01wchar__t_01_4" ],
      [ "is_error_code_enum< kcenon::thread::error_code >", "structstd_1_1is__error__code__enum_3_01kcenon_1_1thread_1_1error__code_01_4.html", null ]
    ] ],
    [ "utility_module", "namespaceutility__module.html", [
      [ "convert_string", "classutility__module_1_1convert__string.html", "classutility__module_1_1convert__string" ],
      [ "enum_formatter", "classutility__module_1_1enum__formatter.html", "classutility__module_1_1enum__formatter" ],
      [ "formatter", "classutility__module_1_1formatter.html", "classutility__module_1_1formatter" ],
      [ "span", "classutility__module_1_1span.html", "classutility__module_1_1span" ]
    ] ],
    [ "cancellable_long_job", "classcancellable__long__job.html", "classcancellable__long__job" ],
    [ "console_logger", "classconsole__logger.html", "classconsole__logger" ],
    [ "console_monitoring", "classconsole__monitoring.html", "classconsole__monitoring" ],
    [ "critical_resource", "classcritical__resource.html", "classcritical__resource" ],
    [ "demo_service", "structdemo__service.html", "structdemo__service" ],
    [ "LockFreeStack", "classLockFreeStack.html", "classLockFreeStack" ],
    [ "mock_logger", "classmock__logger.html", "classmock__logger" ],
    [ "mock_monitoring", "classmock__monitoring.html", "classmock__monitoring" ],
    [ "non_cancellable_job", "classnon__cancellable__job.html", "classnon__cancellable__job" ],
    [ "sample_monitoring", "classsample__monitoring.html", "classsample__monitoring" ],
    [ "SmartJobProcessor", "classSmartJobProcessor.html", "classSmartJobProcessor" ],
    [ "TestData", "structTestData.html", "structTestData" ],
    [ "TestNode", "structTestNode.html", "structTestNode" ]
];