Thread System: kcenon::thread::cancellable_future< void > Class Reference
kcenon::thread::cancellable_future< void > Class Reference
Specialization for void return type.
#include <cancellable_future.h>
Public Types
using value_type = void
Public Member Functions
cancellable_future (std::future< void > future, cancellation_token token)
~cancellable_future ()=default
cancellable_future (const cancellable_future &)=delete
cancellable_future & operator= (const cancellable_future &)=delete
cancellable_future (cancellable_future &&) noexcept=default
cancellable_future & operator= (cancellable_future &&) noexcept=default
auto get () -> common::VoidResult
auto get_for (std::chrono::milliseconds timeout) -> common::Result< bool >
auto is_ready () const -> bool
auto is_cancelled () const -> bool
void cancel ()
auto valid () const -> bool
void wait () const
template<typename Rep , typename Period >
auto wait_for (const std::chrono::duration< Rep, Period > &timeout) const -> std::future_status
auto get_token () const -> cancellation_token
Private Attributes
std::future< void > future_
cancellation_token token_
Detailed Description
Specialization for void return type.
Definition at line 215 of file cancellable_future.h.
Member Typedef Documentation
value_type
using kcenon::thread::cancellable_future< void >::value_type = void
Definition at line 217 of file cancellable_future.h.
Constructor & Destructor Documentation
cancellable_future() [1/3]
kcenon::thread::cancellable_future< void >::cancellable_future (std::future< void > future, cancellation_token token) inline
Definition at line 219 of file cancellable_future.h.
        : future_(std::move(future))
        , token_(std::move(token))
    {}
~cancellable_future()
kcenon::thread::cancellable_future< void >::~cancellable_future () default
cancellable_future() [2/3]
kcenon::thread::cancellable_future< void >::cancellable_future (const cancellable_future< void > &) delete
cancellable_future() [3/3]
kcenon::thread::cancellable_future< void >::cancellable_future (cancellable_future< void > &&) default noexcept
Member Function Documentation
cancel()
void kcenon::thread::cancellable_future< void >::cancel () inline
Definition at line 273 of file cancellable_future.h.
                  {
        token_.cancel();
    }
References kcenon::thread::cancellation_token::cancel(), and kcenon::thread::cancellable_future< R >::token_.
get()
auto kcenon::thread::cancellable_future< void >::get () -> common::VoidResult inline nodiscard
Definition at line 231 of file cancellable_future.h.
{
        if (token_.is_cancelled()) {
            return make_error_result(error_code::operation_canceled);
        }
        try {
            future_.get();
            return common::ok();
        } catch (const std::exception& e) {
            return make_error_result(error_code::job_execution_failed, e.what());
        } catch (...) {
            return make_error_result(error_code::unknown_error, "Unknown exception in future");
        }
    }
References kcenon::thread::cancellation_token::is_cancelled(), kcenon::thread::job_execution_failed, kcenon::thread::make_error_result(), kcenon::thread::cancellable_future< R >::token_, and kcenon::thread::unknown_error.
get_for()
auto kcenon::thread::cancellable_future< void >::get_for (std::chrono::milliseconds timeout) -> common::Result<bool> inline nodiscard
Definition at line 245 of file cancellable_future.h.
{
        if (token_.is_cancelled()) {
            return make_error_result<bool>(error_code::operation_canceled);
        }
        auto status = future_.wait_for(timeout);
        if (status == std::future_status::ready) {
            try {
                future_.get();
                return common::Result<bool>::ok(true);
            } catch (const std::exception& e) {
                return make_error_result<bool>(error_code::job_execution_failed, e.what());
            } catch (...) {
                return make_error_result<bool>(error_code::unknown_error, "Unknown exception in future");
            }
        }
        return common::Result<bool>::ok(false);
    }
References kcenon::thread::cancellable_future< R >::future_, kcenon::thread::cancellation_token::is_cancelled(), kcenon::thread::job_execution_failed, kcenon::thread::make_error_result(), kcenon::thread::operation_canceled, kcenon::thread::cancellable_future< R >::token_, and kcenon::thread::unknown_error.
get_token()
auto kcenon::thread::cancellable_future< void >::get_token () const -> cancellation_token inline nodiscard
Definition at line 292 of file cancellable_future.h.
{
        return token_;
    }
References kcenon::thread::cancellable_future< R >::token_.
is_cancelled()
auto kcenon::thread::cancellable_future< void >::is_cancelled () const -> bool inline nodiscard
Definition at line 269 of file cancellable_future.h.
{
        return token_.is_cancelled();
    }
References kcenon::thread::cancellation_token::is_cancelled(), and kcenon::thread::cancellable_future< R >::token_.
is_ready()
auto kcenon::thread::cancellable_future< void >::is_ready () const -> bool inline nodiscard
Definition at line 264 of file cancellable_future.h.
{
        return future_.wait_for(std::chrono::seconds(0)) ==
               std::future_status::ready;
    }
References kcenon::thread::cancellable_future< R >::future_.
operator=() [1/2]
cancellable_future & kcenon::thread::cancellable_future< void >::operator= (cancellable_future< void > &&) default noexcept
operator=() [2/2]
cancellable_future & kcenon::thread::cancellable_future< void >::operator= (const cancellable_future< void > &) delete
valid()
auto kcenon::thread::cancellable_future< void >::valid () const -> bool inline nodiscard
Definition at line 277 of file cancellable_future.h.
{
        return future_.valid();
    }
References kcenon::thread::cancellable_future< R >::future_.
wait()
void kcenon::thread::cancellable_future< void >::wait () const inline
Definition at line 281 of file cancellable_future.h.
                      {
        future_.wait();
    }
References kcenon::thread::cancellable_future< R >::future_.
wait_for()
template<typename Rep , typename Period > auto kcenon::thread::cancellable_future< void >::wait_for (const std::chrono::duration< Rep, Period > & timeout) const -> std::future_status inline nodiscard
Definition at line 286 of file cancellable_future.h.
    {
        return future_.wait_for(timeout);
    }
References kcenon::thread::cancellable_future< R >::future_.
Member Data Documentation
future_
std::future<void> kcenon::thread::cancellable_future< void >::future_ mutable private
Definition at line 297 of file cancellable_future.h.
token_
cancellation_token kcenon::thread::cancellable_future< void >::token_ private
Definition at line 298 of file cancellable_future.h.
The documentation for this class was generated from the following file:
include/kcenon/thread/core/cancellable_future.h