Thread System: kcenon::thread::latch Class Reference
kcenon::thread::latch Class Reference
C++17-compatible latch implementation.
#include <synchronization.h>
Public Member Functions
latch (std::ptrdiff_t count)
Constructs a latch with the given count.
void count_down (std::ptrdiff_t n=1)
Decrements the counter in a non-blocking manner.
bool try_wait () const noexcept
Tests if the internal counter equals zero.
void wait () const
Blocks until the counter reaches zero.
void arrive_and_wait (std::ptrdiff_t n=1)
Decrements the counter and blocks until it reaches zero.
Private Attributes
std::mutex mutex_
std::condition_variable cv_
std::ptrdiff_t count_
Detailed Description
C++17-compatible latch implementation.
A downward counter which can be used to synchronize threads. The value of the counter is initialized on creation. Threads may block on the latch until the counter is decremented to zero.
Definition at line 39 of file synchronization.h.
Constructor & Destructor Documentation
latch()
kcenon::thread::latch::latch (std::ptrdiff_t count) inline explicit
Constructs a latch with the given count.
Parameters
count The initial value of the counter (must be >= 0)
Definition at line 45 of file synchronization.h.
            : count_(count) {}
Member Function Documentation
arrive_and_wait()
void kcenon::thread::latch::arrive_and_wait (std::ptrdiff_t n = 1) inline
Decrements the counter and blocks until it reaches zero.
Parameters
n The value to subtract from the counter (default: 1)
Definition at line 81 of file synchronization.h.
{
            count_down(n);
            wait();
        }
References count_down(), and wait().
count_down()
void kcenon::thread::latch::count_down (std::ptrdiff_t n = 1) inline
Decrements the counter in a non-blocking manner.
Parameters
n The value to subtract from the counter (default: 1)
Definition at line 52 of file synchronization.h.
{
            std::unique_lock<std::mutex> lock(mutex_);
            count_ -= n;
            if (count_ <= 0) {
                cv_.notify_all();
            }
        }
References count_, cv_, and mutex_.
Referenced by arrive_and_wait().
try_wait()
bool kcenon::thread::latch::try_wait () const inline noexcept
Tests if the internal counter equals zero.
Returns
true if the counter has reached zero, false otherwise
Definition at line 64 of file synchronization.h.
{
            std::unique_lock<std::mutex> lock(mutex_);
            return count_ <= 0;
        }
References count_, and mutex_.
wait()
void kcenon::thread::latch::wait () const inline
Blocks until the counter reaches zero.
Definition at line 72 of file synchronization.h.
{
            std::unique_lock<std::mutex> lock(mutex_);
            cv_.wait(lock, [this] { return count_ <= 0; });
        }
References count_, cv_, and mutex_.
Referenced by arrive_and_wait().
Member Data Documentation
count_
std::ptrdiff_t kcenon::thread::latch::count_ private
Definition at line 89 of file synchronization.h.
Referenced by count_down(), try_wait(), and wait().
cv_
std::condition_variable kcenon::thread::latch::cv_ mutable private
Definition at line 88 of file synchronization.h.
Referenced by count_down(), and wait().
mutex_
std::mutex kcenon::thread::latch::mutex_ mutable private
Definition at line 87 of file synchronization.h.
Referenced by count_down(), try_wait(), and wait().
The documentation for this class was generated from the following file:
include/kcenon/thread/utils/synchronization.h