Thread System: kcenon::thread::cancellation_context Class Reference
kcenon::thread::cancellation_context Class Reference
Cancellation
Thread-local cancellation context for implicit token propagation.
#include <enhanced_cancellation_token.h>
Classes
class guard
RAII guard for push/pop operations.
Static Public Member Functions
static auto current () -> enhanced_cancellation_token
Gets the current thread's cancellation token.
static auto push (enhanced_cancellation_token token) -> void
Pushes a token to the thread-local stack.
static auto pop () -> void
Pops a token from the thread-local stack.
Private Member Functions
cancellation_context ()=delete
Detailed Description
Thread-local cancellation context for implicit token propagation.
Provides a way to implicitly propagate cancellation tokens through the call stack using thread-local storage.
Usage Example
void outer_function(enhanced_cancellation_token token) {
    cancellation_context::guard guard(token);
    inner_function();  // Can access token via current()
}
void inner_function() {
    auto token = cancellation_context::current();
    if (token.is_cancelled()) {
        return;
    }
    // do work
}
Definition at line 489 of file enhanced_cancellation_token.h.
Constructor & Destructor Documentation
cancellation_context()
kcenon::thread::cancellation_context::cancellation_context () private delete
Member Function Documentation
current()
auto kcenon::thread::cancellation_context::current () -> enhanced_cancellation_token static nodiscard
Gets the current thread's cancellation token.
Returns
The current token, or a new uncancelled token if none.
Definition at line 606 of file enhanced_cancellation_token.cpp.
    {
        if (context_stack.empty())
        {
            return enhanced_cancellation_token::create();
        }
        return context_stack.back();
    }
References kcenon::thread::enhanced_cancellation_token::create().
pop()
auto kcenon::thread::cancellation_context::pop () -> void static
Pops a token from the thread-local stack.
Definition at line 620 of file enhanced_cancellation_token.cpp.
    {
        if (!context_stack.empty())
        {
            context_stack.pop_back();
        }
    }
Referenced by kcenon::thread::cancellation_context::guard::~guard().
push()
auto kcenon::thread::cancellation_context::push (enhanced_cancellation_token token) -> void static
Pushes a token to the thread-local stack.
Parameters
token The token to push.
Definition at line 615 of file enhanced_cancellation_token.cpp.
    {
        context_stack.push_back(std::move(token));
    }
Referenced by kcenon::thread::cancellation_context::guard::guard().
The documentation for this class was generated from the following files:
include/kcenon/thread/core/enhanced_cancellation_token.h
src/core/enhanced_cancellation_token.cpp