Thread System: utility_module::span< T, Extent > Class Template Reference
utility_module::span< T, Extent > Class Template Reference
A fallback span implementation for C++17 and earlier compilers.
#include <span.h>
Public Types
using element_type = T
using value_type = std::remove_cv_t<T>
using size_type = size_t
using difference_type = ptrdiff_t
using pointer = T*
using const_pointer = const T*
using reference = T&
using const_reference = const T&
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
Public Member Functions
constexpr span () noexcept
constexpr span (pointer ptr, size_type count) noexcept
constexpr span (pointer first, pointer last) noexcept
template<size_t N>
constexpr span (std::array< value_type, N > &arr) noexcept
template<size_t N>
constexpr span (const std::array< value_type, N > &arr) noexcept
template<typename Allocator >
constexpr span (std::vector< value_type, Allocator > &vec) noexcept
template<typename Allocator >
constexpr span (const std::vector< value_type, Allocator > &vec) noexcept
template<size_t N>
constexpr span (element_type(&arr)[N]) noexcept
constexpr span & operator= (const span &other) noexcept=default
constexpr size_type size () const noexcept
constexpr size_type size_bytes () const noexcept
constexpr bool empty () const noexcept
constexpr reference operator[] (size_type idx) const noexcept
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr pointer data () const noexcept
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
template<size_t Count>
constexpr span< element_type, Count > first () const noexcept
constexpr span< element_type, dynamic_extent > first (size_type count) const noexcept
template<size_t Count>
constexpr span< element_type, Count > last () const noexcept
constexpr span< element_type, dynamic_extent > last (size_type count) const noexcept
template<size_t Offset, size_t Count = dynamic_extent>
constexpr auto subspan () const noexcept
constexpr span< element_type, dynamic_extent > subspan (size_type offset, size_type count=dynamic_extent) const noexcept
constexpr span () noexcept
constexpr span (pointer ptr, size_type count) noexcept
constexpr span (pointer first, pointer last) noexcept
template<size_t N>
constexpr span (std::array< value_type, N > &arr) noexcept
template<size_t N>
constexpr span (const std::array< value_type, N > &arr) noexcept
template<typename Allocator >
constexpr span (std::vector< value_type, Allocator > &vec) noexcept
template<typename Allocator >
constexpr span (const std::vector< value_type, Allocator > &vec) noexcept
template<size_t N>
constexpr span (element_type(&arr)[N]) noexcept
constexpr span & operator= (const span &other) noexcept=default
constexpr size_type size () const noexcept
constexpr size_type size_bytes () const noexcept
constexpr bool empty () const noexcept
constexpr reference operator[] (size_type idx) const noexcept
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr pointer data () const noexcept
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
template<size_t Count>
constexpr span< element_type, Count > first () const noexcept
constexpr span< element_type, dynamic_extent > first (size_type count) const noexcept
template<size_t Count>
constexpr span< element_type, Count > last () const noexcept
constexpr span< element_type, dynamic_extent > last (size_type count) const noexcept
template<size_t Offset, size_t Count = dynamic_extent>
constexpr auto subspan () const noexcept
constexpr span< element_type, dynamic_extent > subspan (size_type offset, size_type count=dynamic_extent) const noexcept
Static Public Attributes
static constexpr size_t dynamic_extent = size_t(-1)
Private Attributes
pointer data_
size_type size_
Detailed Description
template<typename T, size_t Extent = size_t(-1)>
class utility_module::span< T, Extent >
A fallback span implementation for C++17 and earlier compilers.
Provides a view over a contiguous sequence of objects, similar to C++20's std::span. This implementation offers a compatible subset of the std::span interface.
Template Parameters
T The type of elements in the span.
Extent The extent (size) of the span, or dynamic_extent if determined at runtime.
Definition at line 45 of file span.h.
Member Typedef Documentation
const_iterator
template<typename T , size_t Extent = size_t(-1)> typedef const_pointer kcenon::thread::utils::span::const_iterator = const_pointer
Definition at line 52 of file span.h.
const_pointer
template<typename T , size_t Extent = size_t(-1)> typedef const T * kcenon::thread::utils::span::const_pointer = const T*
Definition at line 48 of file span.h.
const_reference
template<typename T , size_t Extent = size_t(-1)> typedef const T & kcenon::thread::utils::span::const_reference = const T&
Definition at line 50 of file span.h.
const_reverse_iterator
template<typename T , size_t Extent = size_t(-1)> typedef std::reverse_iterator< const_iterator > kcenon::thread::utils::span::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 54 of file span.h.
difference_type
template<typename T , size_t Extent = size_t(-1)> typedef ptrdiff_t kcenon::thread::utils::span::difference_type = ptrdiff_t
Definition at line 46 of file span.h.
element_type
template<typename T , size_t Extent = size_t(-1)> typedef T kcenon::thread::utils::span::element_type = T
Definition at line 43 of file span.h.
iterator
template<typename T , size_t Extent = size_t(-1)> typedef pointer kcenon::thread::utils::span::iterator = pointer
Definition at line 51 of file span.h.
pointer
template<typename T , size_t Extent = size_t(-1)> typedef T * kcenon::thread::utils::span::pointer = T*
Definition at line 47 of file span.h.
reference
template<typename T , size_t Extent = size_t(-1)> typedef T & kcenon::thread::utils::span::reference = T&
Definition at line 49 of file span.h.
reverse_iterator
template<typename T , size_t Extent = size_t(-1)> typedef std::reverse_iterator< iterator > kcenon::thread::utils::span::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 53 of file span.h.
size_type
template<typename T , size_t Extent = size_t(-1)> typedef size_t kcenon::thread::utils::span::size_type = size_t
Definition at line 45 of file span.h.
value_type
template<typename T , size_t Extent = size_t(-1)> typedef std::remove_cv_t< T > kcenon::thread::utils::span::value_type = std::remove_cv_t<T>
Definition at line 44 of file span.h.
Constructor & Destructor Documentation
span() [1/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span () inline constexpr noexcept
Definition at line 60 of file span.h.
                                  : data_(nullptr), size_(0)
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Default-constructed span must have dynamic extent or zero extent");
        }
span() [2/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span (pointer ptr, size_type count) inline constexpr noexcept
Definition at line 66 of file span.h.
                                                              : data_(ptr), size_(count)
        {
            static_assert(Extent == dynamic_extent || Extent == count,
                        "Size mismatch in span construction");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [3/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span (pointer first, pointer last) inline constexpr noexcept
Definition at line 72 of file span.h.
                                                             : data_(first), size_(last - first)
        {
            static_assert(Extent == dynamic_extent || Extent == size_,
                        "Size mismatch in span construction");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [4/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 80 of file span.h.
            : data_(arr.data()), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [5/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (const std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 88 of file span.h.
            : data_(arr.data()), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from const array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [6/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > utility_module::span< T, Extent >::span (std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 97 of file span.h.
            : data_(vec.data()), size_(vec.size())
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Non-dynamic extent not supported for std::vector constructor");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [7/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > utility_module::span< T, Extent >::span (const std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 105 of file span.h.
            : data_(vec.data()), size_(vec.size())
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Non-dynamic extent not supported for std::vector constructor");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [8/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (element_type(&) arr[N]) inline constexpr noexcept
Definition at line 114 of file span.h.
            : data_(arr), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [9/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span () inline constexpr noexcept
Definition at line 66 of file span.h.
                                  : data_(nullptr), size_(0)
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Default-constructed span must have dynamic extent or zero extent");
        }
span() [10/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span (pointer ptr, size_type count) inline constexpr noexcept
Definition at line 72 of file span.h.
                                                              : data_(ptr), size_(count)
        {
            static_assert(Extent == dynamic_extent || Extent == count,
                        "Size mismatch in span construction");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [11/16]
template<typename T , size_t Extent = size_t(-1)> utility_module::span< T, Extent >::span (pointer first, pointer last) inline constexpr noexcept
Definition at line 78 of file span.h.
                                                             : data_(first), size_(last - first)
        {
            static_assert(Extent == dynamic_extent || Extent == size_,
                        "Size mismatch in span construction");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [12/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 86 of file span.h.
            : data_(arr.data()), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [13/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (const std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 94 of file span.h.
            : data_(arr.data()), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from const array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [14/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > utility_module::span< T, Extent >::span (std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 103 of file span.h.
            : data_(vec.data()), size_(vec.size())
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Non-dynamic extent not supported for std::vector constructor");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [15/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > utility_module::span< T, Extent >::span (const std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 111 of file span.h.
            : data_(vec.data()), size_(vec.size())
        {
            static_assert(Extent == dynamic_extent || Extent == 0,
                        "Non-dynamic extent not supported for std::vector constructor");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
span() [16/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> utility_module::span< T, Extent >::span (element_type(&) arr[N]) inline constexpr noexcept
Definition at line 120 of file span.h.
            : data_(arr), size_(N)
        {
            static_assert(Extent == dynamic_extent || Extent == N,
                        "Size mismatch in span construction from array");
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
Member Function Documentation
back() [1/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::back () const inline nodiscard constexpr noexcept
Definition at line 146 of file span.h.
        {
            return data_[size_ - 1];
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
back() [2/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::back () const inline nodiscard constexpr noexcept
Definition at line 140 of file span.h.
        {
            return data_[size_ - 1];
        }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
begin() [1/2]
template<typename T , size_t Extent = size_t(-1)> iterator utility_module::span< T, Extent >::begin () const inline nodiscard constexpr noexcept
Definition at line 154 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
begin() [2/2]
template<typename T , size_t Extent = size_t(-1)> iterator utility_module::span< T, Extent >::begin () const inline nodiscard constexpr noexcept
Definition at line 148 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
Referenced by utility_module::span< T, Extent >::rend().
cbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> const_iterator utility_module::span< T, Extent >::cbegin () const inline nodiscard constexpr noexcept
Definition at line 156 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
cbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> const_iterator utility_module::span< T, Extent >::cbegin () const inline nodiscard constexpr noexcept
Definition at line 150 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
Referenced by utility_module::span< T, Extent >::crend().
cend() [1/2]
template<typename T , size_t Extent = size_t(-1)> const_iterator utility_module::span< T, Extent >::cend () const inline nodiscard constexpr noexcept
Definition at line 157 of file span.h.
{ return data_ + size_; }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
cend() [2/2]
template<typename T , size_t Extent = size_t(-1)> const_iterator utility_module::span< T, Extent >::cend () const inline nodiscard constexpr noexcept
Definition at line 151 of file span.h.
{ return data_ + size_; }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
Referenced by utility_module::span< T, Extent >::crbegin().
crbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> const_reverse_iterator utility_module::span< T, Extent >::crbegin () const inline nodiscard constexpr noexcept
Definition at line 160 of file span.h.
{ return const_reverse_iterator(cend()); }
References utility_module::span< T, Extent >::cend().
crbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> const_reverse_iterator utility_module::span< T, Extent >::crbegin () const inline nodiscard constexpr noexcept
Definition at line 154 of file span.h.
{ return const_reverse_iterator(cend()); }
References utility_module::span< T, Extent >::cend().
crend() [1/2]
template<typename T , size_t Extent = size_t(-1)> const_reverse_iterator utility_module::span< T, Extent >::crend () const inline nodiscard constexpr noexcept
Definition at line 161 of file span.h.
{ return const_reverse_iterator(cbegin()); }
References utility_module::span< T, Extent >::cbegin().
crend() [2/2]
template<typename T , size_t Extent = size_t(-1)> const_reverse_iterator utility_module::span< T, Extent >::crend () const inline nodiscard constexpr noexcept
Definition at line 155 of file span.h.
{ return const_reverse_iterator(cbegin()); }
References utility_module::span< T, Extent >::cbegin().
data() [1/2]
template<typename T , size_t Extent = size_t(-1)> pointer utility_module::span< T, Extent >::data () const inline nodiscard constexpr noexcept
Definition at line 151 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
data() [2/2]
template<typename T , size_t Extent = size_t(-1)> pointer utility_module::span< T, Extent >::data () const inline nodiscard constexpr noexcept
Definition at line 145 of file span.h.
{ return data_; }
References utility_module::span< T, Extent >::data_.
empty() [1/2]
template<typename T , size_t Extent = size_t(-1)> bool utility_module::span< T, Extent >::empty () const inline nodiscard constexpr noexcept
Definition at line 133 of file span.h.
{ return size_ == 0; }
References utility_module::span< T, Extent >::size_.
empty() [2/2]
template<typename T , size_t Extent = size_t(-1)> bool utility_module::span< T, Extent >::empty () const inline nodiscard constexpr noexcept
Definition at line 127 of file span.h.
{ return size_ == 0; }
References utility_module::span< T, Extent >::size_.
end() [1/2]
template<typename T , size_t Extent = size_t(-1)> iterator utility_module::span< T, Extent >::end () const inline nodiscard constexpr noexcept
Definition at line 155 of file span.h.
{ return data_ + size_; }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
end() [2/2]
template<typename T , size_t Extent = size_t(-1)> iterator utility_module::span< T, Extent >::end () const inline nodiscard constexpr noexcept
Definition at line 149 of file span.h.
{ return data_ + size_; }
References utility_module::span< T, Extent >::data_, and utility_module::span< T, Extent >::size_.
Referenced by utility_module::span< T, Extent >::rbegin().
first() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> span< element_type, Count > utility_module::span< T, Extent >::first () const inline nodiscard constexpr noexcept
Definition at line 165 of file span.h.
        {
            return span<element_type, Count>(data_, Count);
        }
References utility_module::span< T, Extent >::data_, and kcenon::thread::utils::span().
first() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> span< element_type, Count > utility_module::span< T, Extent >::first () const inline nodiscard constexpr noexcept
Definition at line 159 of file span.h.
        {
            return span<element_type, Count>(data_, Count);
        }
References utility_module::span< T, Extent >::data_, and kcenon::thread::utils::span().
first() [3/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::first (size_type count) const inline nodiscard constexpr noexcept
Definition at line 170 of file span.h.
        {
            return span<element_type, dynamic_extent>(data_, count);
        }
References utility_module::span< T, Extent >::data_, and kcenon::thread::utils::span().
first() [4/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::first (size_type count) const inline nodiscard constexpr noexcept
Definition at line 164 of file span.h.
        {
            return span<element_type, dynamic_extent>(data_, count);
        }
References utility_module::span< T, Extent >::data_, and kcenon::thread::utils::span().
front() [1/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::front () const inline nodiscard constexpr noexcept
Definition at line 141 of file span.h.
        {
            return data_[0];
        }
References utility_module::span< T, Extent >::data_.
front() [2/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::front () const inline nodiscard constexpr noexcept
Definition at line 135 of file span.h.
        {
            return data_[0];
        }
References utility_module::span< T, Extent >::data_.
last() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> span< element_type, Count > utility_module::span< T, Extent >::last () const inline nodiscard constexpr noexcept
Definition at line 176 of file span.h.
        {
            return span<element_type, Count>(data_ + (size_ - Count), Count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
last() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> span< element_type, Count > utility_module::span< T, Extent >::last () const inline nodiscard constexpr noexcept
Definition at line 170 of file span.h.
        {
            return span<element_type, Count>(data_ + (size_ - Count), Count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
last() [3/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::last (size_type count) const inline nodiscard constexpr noexcept
Definition at line 181 of file span.h.
        {
            return span<element_type, dynamic_extent>(data_ + (size_ - count), count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
last() [4/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::last (size_type count) const inline nodiscard constexpr noexcept
Definition at line 175 of file span.h.
        {
            return span<element_type, dynamic_extent>(data_ + (size_ - count), count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
operator=() [1/2]
template<typename T , size_t Extent = size_t(-1)> span & utility_module::span< T, Extent >::operator= (const span< T, Extent > & other) constexpr default noexcept
operator=() [2/2]
template<typename T , size_t Extent = size_t(-1)> span & utility_module::span< T, Extent >::operator= (const span< T, Extent > & other) constexpr default noexcept
operator[]() [1/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::operator[] (size_type idx) const inline nodiscard constexpr noexcept
Definition at line 136 of file span.h.
        {
            return data_[idx];
        }
References utility_module::span< T, Extent >::data_.
operator[]() [2/2]
template<typename T , size_t Extent = size_t(-1)> reference utility_module::span< T, Extent >::operator[] (size_type idx) const inline nodiscard constexpr noexcept
Definition at line 130 of file span.h.
        {
            return data_[idx];
        }
References utility_module::span< T, Extent >::data_.
rbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> reverse_iterator utility_module::span< T, Extent >::rbegin () const inline nodiscard constexpr noexcept
Definition at line 158 of file span.h.
{ return reverse_iterator(end()); }
References utility_module::span< T, Extent >::end().
rbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> reverse_iterator utility_module::span< T, Extent >::rbegin () const inline nodiscard constexpr noexcept
Definition at line 152 of file span.h.
{ return reverse_iterator(end()); }
References utility_module::span< T, Extent >::end().
rend() [1/2]
template<typename T , size_t Extent = size_t(-1)> reverse_iterator utility_module::span< T, Extent >::rend () const inline nodiscard constexpr noexcept
Definition at line 159 of file span.h.
{ return reverse_iterator(begin()); }
References utility_module::span< T, Extent >::begin().
rend() [2/2]
template<typename T , size_t Extent = size_t(-1)> reverse_iterator utility_module::span< T, Extent >::rend () const inline nodiscard constexpr noexcept
Definition at line 153 of file span.h.
{ return reverse_iterator(begin()); }
References utility_module::span< T, Extent >::begin().
size() [1/2]
template<typename T , size_t Extent = size_t(-1)> size_type utility_module::span< T, Extent >::size () const inline nodiscard constexpr noexcept
Definition at line 131 of file span.h.
{ return size_; }
References utility_module::span< T, Extent >::size_.
size() [2/2]
template<typename T , size_t Extent = size_t(-1)> size_type utility_module::span< T, Extent >::size () const inline nodiscard constexpr noexcept
Definition at line 125 of file span.h.
{ return size_; }
References utility_module::span< T, Extent >::size_.
size_bytes() [1/2]
template<typename T , size_t Extent = size_t(-1)> size_type utility_module::span< T, Extent >::size_bytes () const inline nodiscard constexpr noexcept
Definition at line 132 of file span.h.
{ return size_ * sizeof(element_type); }
References utility_module::span< T, Extent >::size_.
size_bytes() [2/2]
template<typename T , size_t Extent = size_t(-1)> size_type utility_module::span< T, Extent >::size_bytes () const inline nodiscard constexpr noexcept
Definition at line 126 of file span.h.
{ return size_ * sizeof(element_type); }
References utility_module::span< T, Extent >::size_.
subspan() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Offset, size_t Count = dynamic_extent> auto utility_module::span< T, Extent >::subspan () const inline nodiscard constexpr noexcept
Definition at line 187 of file span.h.
        {
            constexpr size_t new_extent = Count != dynamic_extent ? Count :
                                        (Extent != dynamic_extent ? Extent - Offset : dynamic_extent);
            return span<element_type, new_extent>(
                data_ + Offset,
                Count != dynamic_extent ? Count : (size_ - Offset));
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
subspan() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Offset, size_t Count = dynamic_extent> auto utility_module::span< T, Extent >::subspan () const inline nodiscard constexpr noexcept
Definition at line 181 of file span.h.
        {
            constexpr size_t new_extent = Count != dynamic_extent ? Count :
                                        (Extent != dynamic_extent ? Extent - Offset : dynamic_extent);
            return span<element_type, new_extent>(
                data_ + Offset,
                Count != dynamic_extent ? Count : (size_ - Offset));
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
subspan() [3/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::subspan (size_type offset, size_type count = dynamic_extent) const inline nodiscard constexpr noexcept
Definition at line 197 of file span.h.
        {
            size_type new_count = count == dynamic_extent ? size_ - offset : count;
            return span<element_type, dynamic_extent>(data_ + offset, new_count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
subspan() [4/4]
template<typename T , size_t Extent = size_t(-1)> span< element_type, dynamic_extent > utility_module::span< T, Extent >::subspan (size_type offset, size_type count = dynamic_extent) const inline nodiscard constexpr noexcept
Definition at line 191 of file span.h.
        {
            size_type new_count = count == dynamic_extent ? size_ - offset : count;
            return span<element_type, dynamic_extent>(data_ + offset, new_count);
        }
References utility_module::span< T, Extent >::data_, utility_module::span< T, Extent >::size_, and kcenon::thread::utils::span().
Member Data Documentation
data_
template<typename T , size_t Extent = size_t(-1)> pointer kcenon::thread::utils::span::data_ private
Definition at line 198 of file span.h.
Referenced by utility_module::span< T, Extent >::back(), utility_module::span< T, Extent >::begin(), utility_module::span< T, Extent >::cbegin(), utility_module::span< T, Extent >::cend(), utility_module::span< T, Extent >::data(), utility_module::span< T, Extent >::end(), utility_module::span< T, Extent >::first(), utility_module::span< T, Extent >::first(), utility_module::span< T, Extent >::front(), utility_module::span< T, Extent >::last(), utility_module::span< T, Extent >::last(), utility_module::span< T, Extent >::operator[](), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::subspan(), and utility_module::span< T, Extent >::subspan().
dynamic_extent
template<typename T , size_t Extent = size_t(-1)> static constexpr size_t kcenon::thread::utils::span::dynamic_extent = size_t(-1) static constexpr
Definition at line 57 of file span.h.
size_
template<typename T , size_t Extent = size_t(-1)> size_type kcenon::thread::utils::span::size_ private
Definition at line 199 of file span.h.
Referenced by utility_module::span< T, Extent >::back(), utility_module::span< T, Extent >::cend(), utility_module::span< T, Extent >::empty(), utility_module::span< T, Extent >::end(), utility_module::span< T, Extent >::last(), utility_module::span< T, Extent >::last(), utility_module::span< T, Extent >::size(), utility_module::span< T, Extent >::size_bytes(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::span(), utility_module::span< T, Extent >::subspan(), and utility_module::span< T, Extent >::subspan().
The documentation for this class was generated from the following files:
utilities/include/span.h
include/kcenon/thread/utils/span.h