Thread System: SmartJobProcessor Class Reference
SmartJobProcessor Class Reference
Smart job processor that adapts to queue capabilities.
Public Member Functions
SmartJobProcessor (bool need_exact_metrics)
void log_status () const
bool has_exact_metrics () const
Private Member Functions
size_t get_size () const
Private Attributes
std::unique_ptr< scheduler_interface > queue_
bool exact_metrics_available_
Detailed Description
Smart job processor that adapts to queue capabilities.
Demonstrates capability-driven queue selection and usage.
Examples
queue_capabilities_sample.cpp.
Definition at line 157 of file queue_capabilities_sample.cpp.
Constructor & Destructor Documentation
SmartJobProcessor()
SmartJobProcessor::SmartJobProcessor (bool need_exact_metrics) inline explicit
Examples
queue_capabilities_sample.cpp.
Definition at line 162 of file queue_capabilities_sample.cpp.
    {
        if (need_exact_metrics) {
            auto jq = std::make_unique<job_queue>();
            exact_metrics_available_ = true;
            queue_ = std::move(jq);
        } else {
            auto lfq = std::make_unique<detail::lockfree_job_queue>();
            exact_metrics_available_ = false;
            queue_ = std::move(lfq);
        }
    }
References exact_metrics_available_, and queue_.
Member Function Documentation
get_size()
size_t SmartJobProcessor::get_size () const inline nodiscard private
Examples
queue_capabilities_sample.cpp.
Definition at line 189 of file queue_capabilities_sample.cpp.
    {
        if (auto* cap = dynamic_cast<queue_capabilities_interface*>(queue_.get())) {
            // Use the polymorphic interface for demonstration
            if (auto* jq = dynamic_cast<job_queue*>(queue_.get())) {
                return jq->size();
            }
            if (auto* lfq = dynamic_cast<detail::lockfree_job_queue*>(queue_.get())) {
                return lfq->size();
            }
        }
        return 0;
    }
References queue_.
Referenced by log_status().
has_exact_metrics()
bool SmartJobProcessor::has_exact_metrics () const inline nodiscard
Examples
queue_capabilities_sample.cpp.
Definition at line 186 of file queue_capabilities_sample.cpp.
{ return exact_metrics_available_; }
References exact_metrics_available_.
Referenced by capability_driven_selection().
log_status()
void SmartJobProcessor::log_status () const inline
Examples
queue_capabilities_sample.cpp.
Definition at line 175 of file queue_capabilities_sample.cpp.
    {
        if (exact_metrics_available_) {
            // Safe to use for monitoring/alerting
            std::cout << "  Exact queue size: " << get_size() << std::endl;
        } else {
            // Approximate, for logging only
            std::cout << "  Approximate queue size: ~" << get_size() << std::endl;
        }
    }
References exact_metrics_available_, and get_size().
Referenced by capability_driven_selection().
Member Data Documentation
exact_metrics_available_
bool SmartJobProcessor::exact_metrics_available_ private
Examples
queue_capabilities_sample.cpp.
Definition at line 159 of file queue_capabilities_sample.cpp.
Referenced by has_exact_metrics(), log_status(), and SmartJobProcessor().
queue_
std::unique_ptr<scheduler_interface> SmartJobProcessor::queue_ private
Examples
queue_capabilities_sample.cpp.
Definition at line 158 of file queue_capabilities_sample.cpp.
Referenced by get_size(), and SmartJobProcessor().
The documentation for this class was generated from the following file:
examples/queue_capabilities_sample/queue_capabilities_sample.cpp