Thread System: kcenon::thread::metrics::LatencyHistogram Class Reference
kcenon::thread::metrics::LatencyHistogram Class Reference
Metrics
HDR-style histogram for latency distribution with logarithmic buckets.
#include <latency_histogram.h>
Public Member Functions
LatencyHistogram ()
Default constructor - initializes all buckets to zero.
LatencyHistogram (const LatencyHistogram &other)
Copy constructor.
LatencyHistogram (LatencyHistogram &&other) noexcept
Move constructor.
LatencyHistogram & operator= (const LatencyHistogram &other)
Copy assignment operator.
LatencyHistogram & operator= (LatencyHistogram &&other) noexcept
Move assignment operator.
~LatencyHistogram ()=default
Destructor.
void record (std::chrono::nanoseconds value)
Record a latency value.
void record_ns (std::uint64_t nanoseconds)
Record a raw nanosecond value.
double percentile (double p) const
Calculate the value at a given percentile.
double p50 () const
Get the 50th percentile (median).
double p90 () const
Get the 90th percentile.
double p95 () const
Get the 95th percentile.
double p99 () const
Get the 99th percentile.
double p999 () const
Get the 99.9th percentile.
double mean () const
Calculate the arithmetic mean.
double stddev () const
Calculate the standard deviation.
std::uint64_t min () const
Get the minimum recorded value.
std::uint64_t max () const
Get the maximum recorded value.
std::uint64_t count () const
Get the total count of recorded values.
std::uint64_t sum () const
Get the sum of all recorded values.
void reset ()
Reset all buckets and counters to zero.
bool empty () const
Check if the histogram is empty.
void merge (const LatencyHistogram &other)
Merge another histogram into this one.
std::uint64_t bucket_count (std::size_t bucket_index) const
Get the bucket count at a specific index.
Static Public Member Functions
static std::uint64_t bucket_lower_bound (std::size_t bucket_index)
Get the lower bound of a bucket.
static std::uint64_t bucket_upper_bound (std::size_t bucket_index)
Get the upper bound of a bucket.
Static Public Attributes
static constexpr std::size_t BUCKET_COUNT = 64
Number of histogram buckets.
Static Private Member Functions
static std::size_t compute_bucket_index (std::uint64_t value)
Compute the bucket index for a given value.
static double bucket_midpoint (std::size_t bucket_index)
Get the midpoint value of a bucket for estimation.
Private Attributes
std::array< std::atomic< std::uint64_t >, BUCKET_COUNT > buckets_
Histogram buckets using logarithmic distribution.
std::atomic< std::uint64_t > total_count_ {0}
Total number of recorded values.
std::atomic< std::uint64_t > total_sum_ {0}
Sum of all recorded values.
std::atomic< std::uint64_t > min_value_ {std::numeric_limits<std::uint64_t>::max()}
Minimum recorded value.
std::atomic< std::uint64_t > max_value_ {0}
Maximum recorded value.
Detailed Description
HDR-style histogram for latency distribution with logarithmic buckets.
This class provides a lock-free, thread-safe histogram for recording latency measurements. It uses logarithmic bucketing to efficiently represent a wide range of values (from nanoseconds to seconds) with bounded memory usage.
Design Principles
Lock-free: All operations use atomic instructions, no mutexes
Low overhead: < 100ns per record operation
Memory efficient: Fixed-size bucket array (< 1KB total)
High accuracy: Accurate percentile calculations within 1%
Bucket Design
Uses 64 logarithmic buckets covering the range from 0 to ~10^19 nanoseconds:
Bucket 0: [0, 1) ns
Bucket 1: [1, 2) ns
Bucket 2: [2, 4) ns
Bucket 3: [4, 8) ns
...
Bucket 63: [2^62, 2^63) ns
Thread Safety:
Thread-safe for concurrent recording and reading.
See also
EnhancedThreadPoolMetrics
Definition at line 51 of file latency_histogram.h.
Constructor & Destructor Documentation
LatencyHistogram() [1/3]
kcenon::thread::metrics::LatencyHistogram::LatencyHistogram ()
Default constructor - initializes all buckets to zero.
Definition at line 13 of file latency_histogram.cpp.
{
    for (auto& bucket : buckets_) {
        bucket.store(0, std::memory_order_relaxed);
    }
}
References buckets_.
LatencyHistogram() [2/3]
kcenon::thread::metrics::LatencyHistogram::LatencyHistogram (const LatencyHistogram & other)
Copy constructor.
Parameters
other The histogram to copy from.
Definition at line 19 of file latency_histogram.cpp.
{
    for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
        buckets_[i].store(other.buckets_[i].load(std::memory_order_relaxed),
                          std::memory_order_relaxed);
    }
    total_count_.store(other.total_count_.load(std::memory_order_relaxed),
                       std::memory_order_relaxed);
    total_sum_.store(other.total_sum_.load(std::memory_order_relaxed),
                     std::memory_order_relaxed);
    min_value_.store(other.min_value_.load(std::memory_order_relaxed),
                     std::memory_order_relaxed);
    max_value_.store(other.max_value_.load(std::memory_order_relaxed),
                     std::memory_order_relaxed);
}
References BUCKET_COUNT, buckets_, max_value_, min_value_, total_count_, and total_sum_.
LatencyHistogram() [3/3]
kcenon::thread::metrics::LatencyHistogram::LatencyHistogram (LatencyHistogram && other) noexcept
Move constructor.
Parameters
other The histogram to move from.
Definition at line 34 of file latency_histogram.cpp.
{
    for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
        buckets_[i].store(other.buckets_[i].load(std::memory_order_relaxed),
                          std::memory_order_relaxed);
        other.buckets_[i].store(0, std::memory_order_relaxed);
    }
    total_count_.store(other.total_count_.exchange(0, std::memory_order_relaxed),
                       std::memory_order_relaxed);
    total_sum_.store(other.total_sum_.exchange(0, std::memory_order_relaxed),
                     std::memory_order_relaxed);
    min_value_.store(other.min_value_.exchange(
                         std::numeric_limits<std::uint64_t>::max(),
                         std::memory_order_relaxed),
                     std::memory_order_relaxed);
    max_value_.store(other.max_value_.exchange(0, std::memory_order_relaxed),
                     std::memory_order_relaxed);
}
~LatencyHistogram()
kcenon::thread::metrics::LatencyHistogram::~LatencyHistogram () default
Destructor.
Member Function Documentation
bucket_count()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::bucket_count (std::size_t bucket_index) const nodiscard
Get the bucket count at a specific index.
Parameters
bucket_index The bucket index (0 to BUCKET_COUNT-1).
Returns
The count in the specified bucket.
Definition at line 259 of file latency_histogram.cpp.
{
    if (bucket_index >= BUCKET_COUNT) {
        return 0;
    }
    return buckets_[bucket_index].load(std::memory_order_relaxed);
}
References BUCKET_COUNT, and buckets_.
bucket_lower_bound()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::bucket_lower_bound (std::size_t bucket_index) static nodiscard
Get the lower bound of a bucket.
Parameters
bucket_index The bucket index.
Returns
The lower bound in nanoseconds.
Definition at line 266 of file latency_histogram.cpp.
{
    if (bucket_index == 0) {
        return 0;
    }
    if (bucket_index >= BUCKET_COUNT) {
        return std::numeric_limits<std::uint64_t>::max();
    }
    return static_cast<std::uint64_t>(1ULL << (bucket_index - 1));
}
References BUCKET_COUNT.
Referenced by bucket_midpoint(), and percentile().
bucket_midpoint()
double kcenon::thread::metrics::LatencyHistogram::bucket_midpoint (std::size_t bucket_index) static nodiscard private
Get the midpoint value of a bucket for estimation.
Parameters
bucket_index The bucket index.
Returns
The midpoint value in nanoseconds.
Definition at line 309 of file latency_histogram.cpp.
{
    const auto lower = bucket_lower_bound(bucket_index);
    const auto upper = bucket_upper_bound(bucket_index);
    if (upper == std::numeric_limits<std::uint64_t>::max()) {
        // For the last bucket, use lower bound as estimate
        return static_cast<double>(lower);
    }
    return (static_cast<double>(lower) + static_cast<double>(upper)) / 2.0;
}
References bucket_lower_bound(), and bucket_upper_bound().
Referenced by percentile(), and stddev().
bucket_upper_bound()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::bucket_upper_bound (std::size_t bucket_index) static nodiscard
Get the upper bound of a bucket.
Parameters
bucket_index The bucket index.
Returns
The upper bound in nanoseconds.
Definition at line 276 of file latency_histogram.cpp.
{
    if (bucket_index >= BUCKET_COUNT - 1) {
        return std::numeric_limits<std::uint64_t>::max();
    }
    return static_cast<std::uint64_t>(1ULL << bucket_index);
}
References BUCKET_COUNT.
Referenced by bucket_midpoint(), and percentile().
compute_bucket_index()
std::size_t kcenon::thread::metrics::LatencyHistogram::compute_bucket_index (std::uint64_t value) static nodiscard private
Compute the bucket index for a given value.
Parameters
value The value in nanoseconds.
Returns
The bucket index (0 to BUCKET_COUNT-1).
Definition at line 283 of file latency_histogram.cpp.
{
    if (value == 0) {
        return 0;
    }
    // Use bit manipulation to find the highest set bit (floor of log2)
    // This gives us the bucket index directly
#if defined(__GNUC__) || defined(__clang__)
    const auto leading_zeros = __builtin_clzll(value);
    const auto highest_bit = 63 - leading_zeros;
#elif defined(_MSC_VER)
    unsigned long highest_bit;
    _BitScanReverse64(&highest_bit, value);
#else
    // Fallback: portable implementation
    std::size_t highest_bit = 0;
    auto temp = value;
    while (temp >>= 1) {
        ++highest_bit;
    }
#endif
    // Bucket index is highest_bit + 1, capped at BUCKET_COUNT - 1
    return std::min(static_cast<std::size_t>(highest_bit + 1), BUCKET_COUNT - 1);
}
References BUCKET_COUNT.
Referenced by record_ns().
count()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::count () const nodiscard
Get the total count of recorded values.
Returns
The number of recorded values.
Definition at line 203 of file latency_histogram.cpp.
{
    return total_count_.load(std::memory_order_relaxed);
}
References total_count_.
empty()
bool kcenon::thread::metrics::LatencyHistogram::empty () const nodiscard
Check if the histogram is empty.
Returns
True if no values have been recorded.
Definition at line 222 of file latency_histogram.cpp.
{
    return total_count_.load(std::memory_order_relaxed) == 0;
}
References total_count_.
max()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::max () const nodiscard
Get the maximum recorded value.
Returns
The maximum latency in nanoseconds.
Returns 0 if the histogram is empty.
Definition at line 195 of file latency_histogram.cpp.
{
    const auto total = total_count_.load(std::memory_order_relaxed);
    if (total == 0) {
        return 0;
    }
    return max_value_.load(std::memory_order_relaxed);
}
References max_value_, and total_count_.
mean()
double kcenon::thread::metrics::LatencyHistogram::mean () const nodiscard
Calculate the arithmetic mean.
Returns
The mean latency in nanoseconds.
Returns 0.0 if the histogram is empty. Note: The mean is approximated using bucket midpoints.
Definition at line 158 of file latency_histogram.cpp.
{
    const auto total = total_count_.load(std::memory_order_relaxed);
    if (total == 0) {
        return 0.0;
    }
    return static_cast<double>(total_sum_.load(std::memory_order_relaxed)) / total;
}
References total_count_, and total_sum_.
Referenced by stddev().
merge()
void kcenon::thread::metrics::LatencyHistogram::merge (const LatencyHistogram & other)
Merge another histogram into this one.
Parameters
other The histogram to merge.
All bucket counts from other are added to this histogram.
Definition at line 226 of file latency_histogram.cpp.
{
    for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
        buckets_[i].fetch_add(other.buckets_[i].load(std::memory_order_relaxed),
                              std::memory_order_relaxed);
    }
    total_count_.fetch_add(other.total_count_.load(std::memory_order_relaxed),
                           std::memory_order_relaxed);
    total_sum_.fetch_add(other.total_sum_.load(std::memory_order_relaxed),
                         std::memory_order_relaxed);
    // Update min atomically
    auto other_min = other.min_value_.load(std::memory_order_relaxed);
    auto current_min = min_value_.load(std::memory_order_relaxed);
    while (other_min < current_min) {
        if (min_value_.compare_exchange_weak(current_min, other_min,
                                              std::memory_order_relaxed,
                                              std::memory_order_relaxed)) {
            break;
        }
    }
    // Update max atomically
    auto other_max = other.max_value_.load(std::memory_order_relaxed);
    auto current_max = max_value_.load(std::memory_order_relaxed);
    while (other_max > current_max) {
        if (max_value_.compare_exchange_weak(current_max, other_max,
                                              std::memory_order_relaxed,
                                              std::memory_order_relaxed)) {
            break;
        }
    }
}
References BUCKET_COUNT, buckets_, max_value_, min_value_, total_count_, and total_sum_.
min()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::min () const nodiscard
Get the minimum recorded value.
Returns
The minimum latency in nanoseconds.
Returns 0 if the histogram is empty.
Definition at line 187 of file latency_histogram.cpp.
{
    const auto total = total_count_.load(std::memory_order_relaxed);
    if (total == 0) {
        return 0;
    }
    return min_value_.load(std::memory_order_relaxed);
}
References min_value_, and total_count_.
operator=() [1/2]
LatencyHistogram & kcenon::thread::metrics::LatencyHistogram::operator= (const LatencyHistogram & other)
Copy assignment operator.
Parameters
other The histogram to copy from.
Returns
Reference to this histogram.
Definition at line 52 of file latency_histogram.cpp.
{
    if (this != &other) {
        for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
            buckets_[i].store(other.buckets_[i].load(std::memory_order_relaxed),
                              std::memory_order_relaxed);
        }
        total_count_.store(other.total_count_.load(std::memory_order_relaxed),
                           std::memory_order_relaxed);
        total_sum_.store(other.total_sum_.load(std::memory_order_relaxed),
                         std::memory_order_relaxed);
        min_value_.store(other.min_value_.load(std::memory_order_relaxed),
                         std::memory_order_relaxed);
        max_value_.store(other.max_value_.load(std::memory_order_relaxed),
                         std::memory_order_relaxed);
    }
    return *this;
}
References BUCKET_COUNT, buckets_, max_value_, min_value_, total_count_, and total_sum_.
operator=() [2/2]
LatencyHistogram & kcenon::thread::metrics::LatencyHistogram::operator= (LatencyHistogram && other) noexcept
Move assignment operator.
Parameters
other The histogram to move from.
Returns
Reference to this histogram.
Definition at line 70 of file latency_histogram.cpp.
{
    if (this != &other) {
        for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
            buckets_[i].store(other.buckets_[i].load(std::memory_order_relaxed),
                              std::memory_order_relaxed);
            other.buckets_[i].store(0, std::memory_order_relaxed);
        }
        total_count_.store(other.total_count_.exchange(0, std::memory_order_relaxed),
                           std::memory_order_relaxed);
        total_sum_.store(other.total_sum_.exchange(0, std::memory_order_relaxed),
                         std::memory_order_relaxed);
        min_value_.store(other.min_value_.exchange(
                             std::numeric_limits<std::uint64_t>::max(),
                             std::memory_order_relaxed),
                         std::memory_order_relaxed);
        max_value_.store(other.max_value_.exchange(0, std::memory_order_relaxed),
                         std::memory_order_relaxed);
    }
    return *this;
}
p50()
double kcenon::thread::metrics::LatencyHistogram::p50 () const inline nodiscard
Get the 50th percentile (median).
Returns
The median latency in nanoseconds.
Definition at line 124 of file latency_histogram.h.
{ return percentile(0.50); }
References percentile().
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::snapshot().
p90()
double kcenon::thread::metrics::LatencyHistogram::p90 () const inline nodiscard
Get the 90th percentile.
Returns
The P90 latency in nanoseconds.
Definition at line 130 of file latency_histogram.h.
{ return percentile(0.90); }
References percentile().
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::snapshot().
p95()
double kcenon::thread::metrics::LatencyHistogram::p95 () const inline nodiscard
Get the 95th percentile.
Returns
The P95 latency in nanoseconds.
Definition at line 136 of file latency_histogram.h.
{ return percentile(0.95); }
References percentile().
p99()
double kcenon::thread::metrics::LatencyHistogram::p99 () const inline nodiscard
Get the 99th percentile.
Returns
The P99 latency in nanoseconds.
Definition at line 142 of file latency_histogram.h.
{ return percentile(0.99); }
References percentile().
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::snapshot().
p999()
double kcenon::thread::metrics::LatencyHistogram::p999 () const inline nodiscard
Get the 99.9th percentile.
Returns
The P99.9 latency in nanoseconds.
Definition at line 148 of file latency_histogram.h.
{ return percentile(0.999); }
References percentile().
percentile()
double kcenon::thread::metrics::LatencyHistogram::percentile (double p) const nodiscard
Calculate the value at a given percentile.
Parameters
p The percentile (0.0 to 1.0, e.g., 0.99 for P99).
Returns
The latency value in nanoseconds at the given percentile.
Returns 0 if the histogram is empty. For an empty bucket at the target percentile, returns the bucket's upper bound to provide an upper estimate.
Definition at line 122 of file latency_histogram.cpp.
{
    const auto total = total_count_.load(std::memory_order_relaxed);
    if (total == 0) {
        return 0.0;
    }
    // Clamp percentile to valid range
    p = std::clamp(p, 0.0, 1.0);
    const auto target_count = static_cast<std::uint64_t>(std::ceil(p * total));
    std::uint64_t cumulative = 0;
    for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
        cumulative += buckets_[i].load(std::memory_order_relaxed);
        if (cumulative >= target_count) {
            // Linear interpolation within the bucket
            const auto bucket_count_val = buckets_[i].load(std::memory_order_relaxed);
            if (bucket_count_val == 0) {
                return bucket_midpoint(i);
            }
            const auto prev_cumulative = cumulative - bucket_count_val;
            const auto target_in_bucket = target_count - prev_cumulative;
            const auto fraction =
                static_cast<double>(target_in_bucket) / bucket_count_val;
            const auto lower = bucket_lower_bound(i);
            const auto upper = bucket_upper_bound(i);
            return lower + fraction * (upper - lower);
        }
    }
    // Should not reach here, but return max bucket value
    return static_cast<double>(bucket_upper_bound(BUCKET_COUNT - 1));
}
References BUCKET_COUNT, bucket_lower_bound(), bucket_midpoint(), bucket_upper_bound(), buckets_, and total_count_.
Referenced by p50(), p90(), p95(), p99(), and p999().
record()
void kcenon::thread::metrics::LatencyHistogram::record (std::chrono::nanoseconds value)
Record a latency value.
Parameters
value The latency duration to record.
This operation is lock-free and thread-safe. Complexity: O(1) - single atomic increment.
Definition at line 91 of file latency_histogram.cpp.
{
    record_ns(static_cast<std::uint64_t>(value.count()));
}
References record_ns().
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::record_enqueue(), kcenon::thread::metrics::EnhancedThreadPoolMetrics::record_execution(), and kcenon::thread::metrics::EnhancedThreadPoolMetrics::record_wait_time().
record_ns()
void kcenon::thread::metrics::LatencyHistogram::record_ns (std::uint64_t nanoseconds)
Record a raw nanosecond value.
Parameters
nanoseconds The latency in nanoseconds.
Definition at line 95 of file latency_histogram.cpp.
{
    const auto bucket_index = compute_bucket_index(nanoseconds);
    buckets_[bucket_index].fetch_add(1, std::memory_order_relaxed);
    total_count_.fetch_add(1, std::memory_order_relaxed);
    total_sum_.fetch_add(nanoseconds, std::memory_order_relaxed);
    // Update min atomically using CAS
    auto current_min = min_value_.load(std::memory_order_relaxed);
    while (nanoseconds < current_min) {
        if (min_value_.compare_exchange_weak(current_min, nanoseconds,
                                              std::memory_order_relaxed,
                                              std::memory_order_relaxed)) {
            break;
        }
    }
    // Update max atomically using CAS
    auto current_max = max_value_.load(std::memory_order_relaxed);
    while (nanoseconds > current_max) {
        if (max_value_.compare_exchange_weak(current_max, nanoseconds,
                                              std::memory_order_relaxed,
                                              std::memory_order_relaxed)) {
            break;
        }
    }
}
References buckets_, compute_bucket_index(), max_value_, min_value_, total_count_, and total_sum_.
Referenced by record().
reset()
void kcenon::thread::metrics::LatencyHistogram::reset ()
Reset all buckets and counters to zero.
This operation is thread-safe but not atomic with respect to concurrent records. Some in-flight records may be lost during reset.
Definition at line 211 of file latency_histogram.cpp.
{
    for (auto& bucket : buckets_) {
        bucket.store(0, std::memory_order_relaxed);
    }
    total_count_.store(0, std::memory_order_relaxed);
    total_sum_.store(0, std::memory_order_relaxed);
    min_value_.store(std::numeric_limits<std::uint64_t>::max(),
                     std::memory_order_relaxed);
    max_value_.store(0, std::memory_order_relaxed);
}
References buckets_, max_value_, min_value_, total_count_, and total_sum_.
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::reset().
stddev()
double kcenon::thread::metrics::LatencyHistogram::stddev () const nodiscard
Calculate the standard deviation.
Returns
The standard deviation in nanoseconds.
Returns 0.0 if the histogram has fewer than 2 samples.
Definition at line 166 of file latency_histogram.cpp.
{
    const auto total = total_count_.load(std::memory_order_relaxed);
    if (total < 2) {
        return 0.0;
    }
    const auto mean_val = mean();
    double sum_squared_diff = 0.0;
    for (std::size_t i = 0; i < BUCKET_COUNT; ++i) {
        const auto bucket_count_val = buckets_[i].load(std::memory_order_relaxed);
        if (bucket_count_val > 0) {
            const auto midpoint = bucket_midpoint(i);
            const auto diff = midpoint - mean_val;
            sum_squared_diff += bucket_count_val * diff * diff;
        }
    }
    return std::sqrt(sum_squared_diff / (total - 1));
}
References BUCKET_COUNT, bucket_midpoint(), buckets_, mean(), and total_count_.
sum()
std::uint64_t kcenon::thread::metrics::LatencyHistogram::sum () const nodiscard
Get the sum of all recorded values.
Returns
The sum of all latencies in nanoseconds.
Definition at line 207 of file latency_histogram.cpp.
{
    return total_sum_.load(std::memory_order_relaxed);
}
References total_sum_.
Member Data Documentation
BUCKET_COUNT
std::size_t kcenon::thread::metrics::LatencyHistogram::BUCKET_COUNT = 64 static constexpr
Number of histogram buckets.
Definition at line 56 of file latency_histogram.h.
Referenced by bucket_count(), bucket_lower_bound(), bucket_upper_bound(), compute_bucket_index(), LatencyHistogram(), merge(), operator=(), percentile(), and stddev().
buckets_
std::array<std::atomic<std::uint64_t>, BUCKET_COUNT> kcenon::thread::metrics::LatencyHistogram::buckets_ private
Histogram buckets using logarithmic distribution.
Definition at line 242 of file latency_histogram.h.
Referenced by bucket_count(), LatencyHistogram(), LatencyHistogram(), merge(), operator=(), percentile(), record_ns(), reset(), and stddev().
max_value_
std::atomic<std::uint64_t> kcenon::thread::metrics::LatencyHistogram::max_value_ {0} private
Maximum recorded value.
Definition at line 262 of file latency_histogram.h.
{0};
Referenced by LatencyHistogram(), max(), merge(), operator=(), record_ns(), and reset().
min_value_
std::atomic<std::uint64_t> kcenon::thread::metrics::LatencyHistogram::min_value_ {std::numeric_limits<std::uint64_t>::max()} private
Minimum recorded value.
Definition at line 257 of file latency_histogram.h.
{std::numeric_limits<std::uint64_t>::max()};
Referenced by LatencyHistogram(), merge(), min(), operator=(), record_ns(), and reset().
total_count_
std::atomic<std::uint64_t> kcenon::thread::metrics::LatencyHistogram::total_count_ {0} private
Total number of recorded values.
Definition at line 247 of file latency_histogram.h.
{0};
Referenced by count(), empty(), LatencyHistogram(), max(), mean(), merge(), min(), operator=(), percentile(), record_ns(), reset(), and stddev().
total_sum_
std::atomic<std::uint64_t> kcenon::thread::metrics::LatencyHistogram::total_sum_ {0} private
Sum of all recorded values.
Definition at line 252 of file latency_histogram.h.
{0};
Referenced by LatencyHistogram(), mean(), merge(), operator=(), record_ns(), reset(), and sum().
The documentation for this class was generated from the following files:
include/kcenon/thread/metrics/latency_histogram.h
src/metrics/latency_histogram.cpp