Thread System: mock_logger Class Reference
mock_logger Class Reference
Mock logger implementation for demonstration.
#include <mock_logger.h>
Public Types
using log_level = kcenon::common::interfaces::log_level
using log_entry = kcenon::common::interfaces::log_entry
using VoidResult = kcenon::common::VoidResult
using source_location = kcenon::common::source_location
Public Member Functions
mock_logger ()
VoidResult log (log_level level, const std::string &message) override
VoidResult log (log_level level, std::string_view message, const source_location &loc=source_location::current()) override
VoidResult log (const log_entry &entry) override
bool is_enabled (log_level level) const override
VoidResult set_level (log_level level) override
log_level get_level () const override
VoidResult flush () override
void start ()
void stop ()
Private Member Functions
std::string format_time () const
std::string level_to_string (log_level level) const
Private Attributes
log_level min_level_
std::mutex mutex_
Detailed Description
Mock logger implementation for demonstration.
Implements common::interfaces::ILogger for use in examples. In a real application, this would be replaced with logger_system.
Note
Issue #261: Updated to use common_system's ILogger interface.
Definition at line 23 of file mock_logger.h.
Member Typedef Documentation
log_entry
using mock_logger::log_entry = kcenon::common::interfaces::log_entry
Definition at line 26 of file mock_logger.h.
log_level
using mock_logger::log_level = kcenon::common::interfaces::log_level
Definition at line 25 of file mock_logger.h.
source_location
using mock_logger::source_location = kcenon::common::source_location
Definition at line 28 of file mock_logger.h.
VoidResult
using mock_logger::VoidResult = kcenon::common::VoidResult
Definition at line 27 of file mock_logger.h.
Constructor & Destructor Documentation
mock_logger()
mock_logger::mock_logger () inline
Definition at line 30 of file mock_logger.h.
: min_level_(log_level::trace) {}
Member Function Documentation
flush()
VoidResult mock_logger::flush () inline override
Definition at line 107 of file mock_logger.h.
{
        std::cout.flush();
        std::cerr.flush();
        return VoidResult::ok({});
    }
Referenced by stop().
format_time()
std::string mock_logger::format_time () const inline private
Definition at line 123 of file mock_logger.h.
{
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
            now.time_since_epoch()) % 1000;
        std::ostringstream oss;
        oss << std::put_time(std::localtime(&time_t), "%H:%M:%S");
        oss << "." << std::setfill('0') << std::setw(3) << ms.count();
        return oss.str();
    }
Referenced by log(), log(), and log().
get_level()
log_level mock_logger::get_level () const inline override
Definition at line 103 of file mock_logger.h.
{
        return min_level_;
    }
References min_level_.
is_enabled()
bool mock_logger::is_enabled (log_level level) const inline override
Definition at line 94 of file mock_logger.h.
{
        return static_cast<int>(level) >= static_cast<int>(min_level_);
    }
References min_level_.
Referenced by log(), log(), and log().
level_to_string()
std::string mock_logger::level_to_string (log_level level) const inline private
Definition at line 135 of file mock_logger.h.
{
        return std::string(kcenon::common::interfaces::to_string(level));
    }
Referenced by log(), log(), and log().
log() [1/3]
VoidResult mock_logger::log (const log_entry & entry) inline override
Definition at line 72 of file mock_logger.h.
{
        if (!is_enabled(entry.level)) {
            return VoidResult::ok({});
        }
        std::lock_guard<std::mutex> lock(mutex_);
        auto& stream = (entry.level >= log_level::error) ? std::cerr : std::cout;
        stream << "[" << format_time() << "] "
               << "[" << level_to_string(entry.level) << "] ";
        if (!entry.file.empty()) {
            size_t pos = entry.file.find_last_of("/\\");
            std::string filename = (pos != std::string::npos) ? entry.file.substr(pos + 1) : entry.file;
            stream << filename << ":" << entry.line << " (" << entry.function << ") ";
        }
        stream << entry.message << std::endl;
        return VoidResult::ok({});
    }
References format_time(), is_enabled(), level_to_string(), and mutex_.
log() [2/3]
VoidResult mock_logger::log (log_level level, const std::string & message) inline override
Definition at line 32 of file mock_logger.h.
{
        if (!is_enabled(level)) {
            return VoidResult::ok({});
        }
        std::lock_guard<std::mutex> lock(mutex_);
        auto& stream = (level >= log_level::error) ? std::cerr : std::cout;
        stream << "[" << format_time() << "] "
               << "[" << level_to_string(level) << "] "
               << message << std::endl;
        return VoidResult::ok({});
    }
References format_time(), is_enabled(), level_to_string(), and mutex_.
log() [3/3]
VoidResult mock_logger::log (log_level level, std::string_view message, const source_location & loc = source_location::current()) inline override
Definition at line 47 of file mock_logger.h.
{
        if (!is_enabled(level)) {
            return VoidResult::ok({});
        }
        std::lock_guard<std::mutex> lock(mutex_);
        auto& stream = (level >= log_level::error) ? std::cerr : std::cout;
        stream << "[" << format_time() << "] "
               << "[" << level_to_string(level) << "] ";
        std::string file = loc.file_name();
        if (!file.empty()) {
            size_t pos = file.find_last_of("/\\");
            std::string filename = (pos != std::string::npos) ? file.substr(pos + 1) : file;
            stream << filename << ":" << loc.line() << " (" << loc.function_name() << ") ";
        }
        stream << message << std::endl;
        return VoidResult::ok({});
    }
References format_time(), is_enabled(), level_to_string(), and mutex_.
set_level()
VoidResult mock_logger::set_level (log_level level) inline override
Definition at line 98 of file mock_logger.h.
{
        min_level_ = level;
        return VoidResult::ok({});
    }
References min_level_.
start()
void mock_logger::start () inline
Definition at line 113 of file mock_logger.h.
                 {
        std::cout << "[MockLogger] Started" << std::endl;
    }
stop()
void mock_logger::stop () inline
Definition at line 117 of file mock_logger.h.
                {
        flush();
        std::cout << "[MockLogger] Stopped" << std::endl;
    }
References flush().
Member Data Documentation
min_level_
log_level mock_logger::min_level_ private
Definition at line 140 of file mock_logger.h.
Referenced by get_level(), is_enabled(), and set_level().
mutex_
std::mutex mock_logger::mutex_ mutable private
Definition at line 141 of file mock_logger.h.
Referenced by log(), log(), and log().
The documentation for this class was generated from the following file:
examples/integration_example/mock_logger.h