Thread System: kcenon::thread::atomic_with_wait< T > Class Template Reference
kcenon::thread::atomic_with_wait< T > Class Template Reference
RAII wrapper to add wait/notify to atomic variables.
#include <atomic_wait.h>
Public Member Functions
atomic_with_wait () noexcept
atomic_with_wait (T initial) noexcept
atomic_with_wait (const atomic_with_wait &)=delete
atomic_with_wait & operator= (const atomic_with_wait &)=delete
T load (std::memory_order order=std::memory_order_seq_cst) const noexcept
void store (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
T exchange (T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_weak (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
bool compare_exchange_strong (T &expected, T desired, std::memory_order order=std::memory_order_seq_cst) noexcept
void wait (T old, std::memory_order order=std::memory_order_seq_cst) noexcept
void notify_one () noexcept
void notify_all () noexcept
operator T () const noexcept
T operator= (T desired) noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type fetch_add (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type fetch_sub (T arg, std::memory_order order=std::memory_order_seq_cst) noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type operator++ () noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type operator++ (int) noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type operator-- () noexcept
template<typename U = T>
std::enable_if< std::is_integral< U >::value, U >::type operator-- (int) noexcept
Private Attributes
std::atomic< T > value_
atomic_wait_helper< T > waiter_
Detailed Description
template<typename T>
class kcenon::thread::atomic_with_wait< T >
RAII wrapper to add wait/notify to atomic variables.
This class combines std::atomic with atomic_wait_helper to provide a drop-in replacement for C++20's atomic with wait/notify support.
Template Parameters
T The value type
Usage:
atomic_with_wait<int> value{0};
// Thread 1
value.wait(0);
// Thread 2
value.store(1);
value.notify_one();
Definition at line 169 of file atomic_wait.h.
Constructor & Destructor Documentation
atomic_with_wait() [1/3]
template<typename T > kcenon::thread::atomic_with_wait< T >::atomic_with_wait () inline noexcept
Definition at line 171 of file atomic_wait.h.
: value_(T{}) {}
atomic_with_wait() [2/3]
template<typename T > kcenon::thread::atomic_with_wait< T >::atomic_with_wait (T initial) inline explicit noexcept
Definition at line 172 of file atomic_wait.h.
: value_(initial) {}
atomic_with_wait() [3/3]
template<typename T > kcenon::thread::atomic_with_wait< T >::atomic_with_wait (const atomic_with_wait< T > &) delete
Member Function Documentation
compare_exchange_strong()
template<typename T > bool kcenon::thread::atomic_with_wait< T >::compare_exchange_strong (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 196 of file atomic_wait.h.
{
        return value_.compare_exchange_strong(expected, desired, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
compare_exchange_weak()
template<typename T > bool kcenon::thread::atomic_with_wait< T >::compare_exchange_weak (T & expected, T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 191 of file atomic_wait.h.
{
        return value_.compare_exchange_weak(expected, desired, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
exchange()
template<typename T > T kcenon::thread::atomic_with_wait< T >::exchange (T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 187 of file atomic_wait.h.
{
        return value_.exchange(desired, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
fetch_add()
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::fetch_add (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 266 of file atomic_wait.h.
{
        return value_.fetch_add(arg, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
Referenced by kcenon::thread::atomic_with_wait< T >::operator++(), and kcenon::thread::atomic_with_wait< T >::operator++().
fetch_sub()
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::fetch_sub (T arg, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 272 of file atomic_wait.h.
{
        return value_.fetch_sub(arg, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
Referenced by kcenon::thread::atomic_with_wait< T >::operator--(), and kcenon::thread::atomic_with_wait< T >::operator--().
load()
template<typename T > T kcenon::thread::atomic_with_wait< T >::load (std::memory_order order = std::memory_order_seq_cst) const inline noexcept
Definition at line 179 of file atomic_wait.h.
{
        return value_.load(order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
Referenced by kcenon::thread::atomic_with_wait< T >::operator T().
notify_all()
template<typename T > void kcenon::thread::atomic_with_wait< T >::notify_all () inline noexcept
Definition at line 210 of file atomic_wait.h.
{
        waiter_.notify_all();
    }
References kcenon::thread::atomic_with_wait< T >::waiter_.
notify_one()
template<typename T > void kcenon::thread::atomic_with_wait< T >::notify_one () inline noexcept
Definition at line 206 of file atomic_wait.h.
{
        waiter_.notify_one();
    }
References kcenon::thread::atomic_with_wait< T >::waiter_.
operator T()
template<typename T > kcenon::thread::atomic_with_wait< T >::operator T () const inline noexcept
Definition at line 215 of file atomic_wait.h.
{
        return load();
    }
References kcenon::thread::atomic_with_wait< T >::load().
operator++() [1/2]
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::operator++ () inline noexcept
Definition at line 278 of file atomic_wait.h.
{
        return fetch_add(1) + 1;
    }
References kcenon::thread::atomic_with_wait< T >::fetch_add().
operator++() [2/2]
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::operator++ (int) inline noexcept
Definition at line 284 of file atomic_wait.h.
{
        return fetch_add(1);
    }
References kcenon::thread::atomic_with_wait< T >::fetch_add().
operator--() [1/2]
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::operator-- () inline noexcept
Definition at line 290 of file atomic_wait.h.
{
        return fetch_sub(1) - 1;
    }
References kcenon::thread::atomic_with_wait< T >::fetch_sub().
operator--() [2/2]
template<typename T > template<typename U = T> std::enable_if< std::is_integral< U >::value, U >::type kcenon::thread::atomic_with_wait< T >::operator-- (int) inline noexcept
Definition at line 296 of file atomic_wait.h.
{
        return fetch_sub(1);
    }
References kcenon::thread::atomic_with_wait< T >::fetch_sub().
operator=() [1/2]
template<typename T > atomic_with_wait & kcenon::thread::atomic_with_wait< T >::operator= (const atomic_with_wait< T > &) delete
operator=() [2/2]
template<typename T > T kcenon::thread::atomic_with_wait< T >::operator= (T desired) inline noexcept
Definition at line 220 of file atomic_wait.h.
{
        store(desired);
        return desired;
    }
References kcenon::thread::atomic_with_wait< T >::store().
store()
template<typename T > void kcenon::thread::atomic_with_wait< T >::store (T desired, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 183 of file atomic_wait.h.
{
        value_.store(desired, order);
    }
References kcenon::thread::atomic_with_wait< T >::value_.
Referenced by kcenon::thread::atomic_with_wait< T >::operator=().
wait()
template<typename T > void kcenon::thread::atomic_with_wait< T >::wait (T old, std::memory_order order = std::memory_order_seq_cst) inline noexcept
Definition at line 202 of file atomic_wait.h.
{
        waiter_.wait(value_, old);
    }
References kcenon::thread::atomic_with_wait< T >::value_, and kcenon::thread::atomic_with_wait< T >::waiter_.
Member Data Documentation
value_
template<typename T > std::atomic<T> kcenon::thread::atomic_with_wait< T >::value_ private
Definition at line 302 of file atomic_wait.h.
Referenced by kcenon::thread::atomic_with_wait< T >::compare_exchange_strong(), kcenon::thread::atomic_with_wait< T >::compare_exchange_weak(), kcenon::thread::atomic_with_wait< T >::exchange(), kcenon::thread::atomic_with_wait< T >::fetch_add(), kcenon::thread::atomic_with_wait< T >::fetch_sub(), kcenon::thread::atomic_with_wait< T >::load(), kcenon::thread::atomic_with_wait< T >::store(), and kcenon::thread::atomic_with_wait< T >::wait().
waiter_
template<typename T > atomic_wait_helper<T> kcenon::thread::atomic_with_wait< T >::waiter_ private
Definition at line 303 of file atomic_wait.h.
Referenced by kcenon::thread::atomic_with_wait< T >::notify_all(), kcenon::thread::atomic_with_wait< T >::notify_one(), and kcenon::thread::atomic_with_wait< T >::wait().
The documentation for this class was generated from the following file:
include/kcenon/thread/utils/atomic_wait.h