Thread System: kcenon::thread::utils::formatter Class Reference
kcenon::thread::utils::formatter Class Reference
Provides convenience methods for string formatting using C++20 <format>.
#include <formatter.h>
Static Public Member Functions
template<typename... FormatArgs>
static auto format (const char *formats, const FormatArgs &... args) -> std::string
Formats a narrow-character string with the given arguments.
template<typename... FormatArgs>
static auto format (const wchar_t *formats, const FormatArgs &... args) -> std::wstring
Formats a wide-character string with the given arguments.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const char *formats, const FormatArgs &... args) -> OutputIt
Formats a narrow-character string directly to an output iterator.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const wchar_t *formats, const FormatArgs &... args) -> OutputIt
Formats a wide-character string directly to an output iterator.
Detailed Description
Provides convenience methods for string formatting using C++20 <format>.
The formatter class offers static functions to format strings (both narrow and wide) into a std::string / std::wstring, or directly to an output iterator.
Example
// Basic usage:
std::string result = formatter::format("Hello, {}", "World");
// Writing directly to a buffer:
std::array<char, 50> buffer;
auto it = formatter::format_to(buffer.begin(), "Number: {}", 42);
// 'it' now points to the end of the written text
Examples
job_cancellation_example.cpp, logger_sample.cpp, multi_process_monitoring_integration.cpp, thread_pool_sample.cpp, typed_thread_pool_sample.cpp, and typed_thread_pool_sample_2.cpp.
Definition at line 121 of file formatter.h.
Member Function Documentation
format() [1/2]
template<typename... FormatArgs> static auto kcenon::thread::utils::formatter::format (const char * formats, const FormatArgs &... args) -> std::string inline static
Formats a narrow-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A format string (e.g. "Name: {}, Age: {}").
args The arguments to substitute into formats.
Returns
A std::string containing the formatted result.
Definition at line 132 of file formatter.h.
        {
            return std::vformat(formats, std::make_format_args(args...));
        }
Referenced by create_default(), create_default(), demo_basic_cancellation(), demo_immediate_vs_graceful(), demo_non_cooperative_job(), demo_pool_level_cancellation(), kcenon::thread::thread_worker::do_work(), initialize_logger(), main(), main(), kcenon::thread::thread_worker::on_stop_requested(), kcenon::thread::thread_pool::remove_workers_internal(), kcenon::thread::thread_pool::stop(), store_job(), store_job(), and kcenon::thread::job::to_string().
format() [2/2]
template<typename... FormatArgs> static auto kcenon::thread::utils::formatter::format (const wchar_t * formats, const FormatArgs &... args) -> std::wstring inline static
Formats a wide-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A wide format string (e.g. L"Count: {}, Value: {}").
args The arguments to substitute into formats.
Returns
A std::wstring containing the formatted result.
Definition at line 145 of file formatter.h.
        {
            return std::vformat(formats, std::make_wformat_args(args...));
        }
format_to() [1/2]
template<typename OutputIt , typename... FormatArgs> static auto kcenon::thread::utils::formatter::format_to (OutputIt out, const char * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a narrow-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a container).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The narrow format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
This method is useful when writing to a buffer, a container, or custom iterators.
Definition at line 162 of file formatter.h.
        {
            return std::vformat_to(out, formats, std::make_format_args(args...));
        }
Referenced by kcenon::thread::thread_pool::to_string().
format_to() [2/2]
template<typename OutputIt , typename... FormatArgs> static auto kcenon::thread::utils::formatter::format_to (OutputIt out, const wchar_t * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a wide-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a wstring).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The wide format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
Definition at line 178 of file formatter.h.
        {
            return std::vformat_to(out, formats, std::make_wformat_args(args...));
        }
The documentation for this class was generated from the following file:
include/kcenon/thread/utils/formatter.h