Thread System: kcenon::thread::typed_safe_hazard_domain< T > Class Template Reference
kcenon::thread::typed_safe_hazard_domain< T > Class Template Reference
Typed hazard pointer domain.
#include <safe_hazard_pointer.h>
Public Member Functions
void retire (T *p)
void collect ()
Static Public Member Functions
static typed_safe_hazard_domain & instance ()
Private Member Functions
typed_safe_hazard_domain ()=default
Detailed Description
template<typename T>
class kcenon::thread::typed_safe_hazard_domain< T >
Typed hazard pointer domain.
Template Parameters
T Type of objects managed
Provides type-safe retire and reclaim operations.
Definition at line 478 of file safe_hazard_pointer.h.
Constructor & Destructor Documentation
typed_safe_hazard_domain()
template<typename T > kcenon::thread::typed_safe_hazard_domain< T >::typed_safe_hazard_domain () private default
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Member Function Documentation
collect()
template<typename T > void kcenon::thread::typed_safe_hazard_domain< T >::collect () inline
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 489 of file safe_hazard_pointer.h.
                   {
        safe_hazard_pointer_domain::instance().collect();
    }
References kcenon::thread::safe_hazard_pointer_domain::collect(), and kcenon::thread::safe_hazard_pointer_domain::instance().
instance()
template<typename T > static typed_safe_hazard_domain & kcenon::thread::typed_safe_hazard_domain< T >::instance () inline static
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 480 of file safe_hazard_pointer.h.
{
        static typed_safe_hazard_domain domain;
        return domain;
    }
retire()
template<typename T > void kcenon::thread::typed_safe_hazard_domain< T >::retire (T * p) inline
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 485 of file safe_hazard_pointer.h.
                      {
        safe_retire_hazard(p);
    }
References kcenon::thread::safe_retire_hazard().
The documentation for this class was generated from the following file:
include/kcenon/thread/core/safe_hazard_pointer.h