Thread System: kcenon::thread::typed_job_interface< job_type > Class Template Reference
kcenon::thread::typed_job_interface< job_type > Class Template Reference abstract
Typed job interface template.
#include <typed_job_interface.h>
Public Member Functions
virtual ~typed_job_interface ()=default
virtual job_type type () const noexcept=0
Get the type/priority of this job.
virtual common::VoidResult execute ()=0
Execute the job's work.
virtual std::string description () const =0
Get a human-readable description of this job.
virtual bool is_ready () const noexcept
Check if this job can be executed.
virtual bool is_cancelled () const noexcept
Check if this job has been cancelled.
virtual bool cancel () noexcept
Cancel this job if possible.
virtual uint64_t estimated_execution_time_us () const noexcept
Get the estimated execution time for this job.
virtual bool has_higher_priority (const typed_job_interface &other) const noexcept
Check if this job has higher priority than another job.
Detailed Description
template<detail::JobType job_type>
class kcenon::thread::typed_job_interface< job_type >
Typed job interface template.
Base interface for all typed jobs.
This interface defines the contract that all typed jobs must follow. It provides type information and execution capabilities while maintaining type safety through templates.
Definition at line 31 of file typed_job_interface.h.
Constructor & Destructor Documentation
~typed_job_interface()
template<detail::JobType job_type> virtual kcenon::thread::typed_job_interface< job_type >::~typed_job_interface () virtual default
Member Function Documentation
cancel()
template<detail::JobType job_type> virtual bool kcenon::thread::typed_job_interface< job_type >::cancel () inline virtual noexcept
Cancel this job if possible.
Returns
true if job was successfully cancelled
Definition at line 73 of file typed_job_interface.h.
{
            return false; // Default implementation - job cannot be cancelled
        }
description()
template<detail::JobType job_type> virtual std::string kcenon::thread::typed_job_interface< job_type >::description () const nodiscard pure virtual
Get a human-readable description of this job.
Returns
Description string for debugging/logging
estimated_execution_time_us()
template<detail::JobType job_type> virtual uint64_t kcenon::thread::typed_job_interface< job_type >::estimated_execution_time_us () const inline nodiscard virtual noexcept
Get the estimated execution time for this job.
Returns
Estimated execution time in microseconds, 0 if unknown
Definition at line 81 of file typed_job_interface.h.
{
            return 0; // Default implementation - unknown execution time
        }
execute()
template<detail::JobType job_type> virtual common::VoidResult kcenon::thread::typed_job_interface< job_type >::execute () nodiscard pure virtual
Execute the job's work.
Returns
Result indicating success or failure
has_higher_priority()
template<detail::JobType job_type> virtual bool kcenon::thread::typed_job_interface< job_type >::has_higher_priority (const typed_job_interface< job_type > & other) const inline nodiscard virtual noexcept
Check if this job has higher priority than another job.
Parameters
other The other job to compare against
Returns
true if this job should be executed before the other job
Definition at line 90 of file typed_job_interface.h.
{
            return detail::higher_priority(type(), other.type());
        }
References kcenon::thread::detail::higher_priority(), and kcenon::thread::typed_job_interface< job_type >::type().
is_cancelled()
template<detail::JobType job_type> virtual bool kcenon::thread::typed_job_interface< job_type >::is_cancelled () const inline nodiscard virtual noexcept
Check if this job has been cancelled.
Returns
true if job execution should be skipped
Definition at line 65 of file typed_job_interface.h.
{
            return false; // Default implementation - job is not cancellable
        }
is_ready()
template<detail::JobType job_type> virtual bool kcenon::thread::typed_job_interface< job_type >::is_ready () const inline nodiscard virtual noexcept
Check if this job can be executed.
Returns
true if job is ready for execution
Definition at line 57 of file typed_job_interface.h.
{
            return true; // Default implementation - job is always ready
        }
type()
template<detail::JobType job_type> virtual job_type kcenon::thread::typed_job_interface< job_type >::type () const nodiscard pure virtual noexcept
Get the type/priority of this job.
Returns
The job type used for scheduling decisions
Referenced by kcenon::thread::typed_job_interface< job_type >::has_higher_priority().
The documentation for this class was generated from the following files:
include/kcenon/thread/forward.h
include/kcenon/thread/impl/typed_pool/typed_job_interface.h