Thread System: kcenon::thread::safe_hazard_guard Class Reference
kcenon::thread::safe_hazard_guard Class Reference
#include <safe_hazard_pointer.h>
Public Member Functions
safe_hazard_guard (void *p=nullptr, size_t slot=0)
Construct guard, optionally protecting a pointer.
~safe_hazard_guard ()
Destructor - releases the record.
safe_hazard_guard (const safe_hazard_guard &)=delete
safe_hazard_guard & operator= (const safe_hazard_guard &)=delete
safe_hazard_guard (safe_hazard_guard &&other) noexcept
safe_hazard_guard & operator= (safe_hazard_guard &&other) noexcept
void protect (void *p) noexcept
Protect a pointer.
void clear () noexcept
Clear protection.
void * get () const noexcept
Get protected pointer.
operator bool () const noexcept
Check if valid.
Private Attributes
safe_hazard_pointer_record * record_
size_t slot_
Detailed Description
Definition at line 360 of file safe_hazard_pointer.h.
Constructor & Destructor Documentation
safe_hazard_guard() [1/3]
kcenon::thread::safe_hazard_guard::safe_hazard_guard (void * p = nullptr, size_t slot = 0) inline explicit
Construct guard, optionally protecting a pointer.
Parameters
p Pointer to protect (optional)
slot Slot index (0 or 1)
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 367 of file safe_hazard_pointer.h.
        : record_(safe_hazard_pointer_domain::instance().acquire())
        , slot_(slot) {
        if (p != nullptr) {
            record_->protect(p, slot_);
        }
    }
References kcenon::thread::safe_hazard_pointer_record::protect(), record_, and slot_.
~safe_hazard_guard()
kcenon::thread::safe_hazard_guard::~safe_hazard_guard () inline
Destructor - releases the record.
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 378 of file safe_hazard_pointer.h.
{
        if (record_ != nullptr) {
            safe_hazard_pointer_domain::instance().release(record_);
        }
    }
References kcenon::thread::safe_hazard_pointer_domain::instance(), record_, and kcenon::thread::safe_hazard_pointer_domain::release().
safe_hazard_guard() [2/3]
kcenon::thread::safe_hazard_guard::safe_hazard_guard (const safe_hazard_guard &) delete
safe_hazard_guard() [3/3]
kcenon::thread::safe_hazard_guard::safe_hazard_guard (safe_hazard_guard && other) inline noexcept
Definition at line 389 of file safe_hazard_pointer.h.
        : record_(other.record_)
        , slot_(other.slot_) {
        other.record_ = nullptr;
    }
Member Function Documentation
clear()
void kcenon::thread::safe_hazard_guard::clear () inline noexcept
Clear protection.
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 420 of file safe_hazard_pointer.h.
{
        if (record_ != nullptr) {
            record_->clear(slot_);
        }
    }
References kcenon::thread::safe_hazard_pointer_record::clear(), record_, and slot_.
get()
void * kcenon::thread::safe_hazard_guard::get () const inline nodiscard noexcept
Get protected pointer.
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 429 of file safe_hazard_pointer.h.
{
        return record_ != nullptr ? record_->get(slot_) : nullptr;
    }
References kcenon::thread::safe_hazard_pointer_record::get(), record_, and slot_.
operator bool()
kcenon::thread::safe_hazard_guard::operator bool () const inline explicit nodiscard noexcept
Check if valid.
Definition at line 436 of file safe_hazard_pointer.h.
{
        return record_ != nullptr;
    }
References record_.
operator=() [1/2]
safe_hazard_guard & kcenon::thread::safe_hazard_guard::operator= (const safe_hazard_guard &) delete
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
operator=() [2/2]
safe_hazard_guard & kcenon::thread::safe_hazard_guard::operator= (safe_hazard_guard && other) inline noexcept
Definition at line 395 of file safe_hazard_pointer.h.
{
        if (this != &other) {
            if (record_ != nullptr) {
                safe_hazard_pointer_domain::instance().release(record_);
            }
            record_ = other.record_;
            slot_ = other.slot_;
            other.record_ = nullptr;
        }
        return *this;
    }
References kcenon::thread::safe_hazard_pointer_domain::instance(), record_, kcenon::thread::safe_hazard_pointer_domain::release(), and slot_.
protect()
void kcenon::thread::safe_hazard_guard::protect (void * p) inline noexcept
Protect a pointer.
Parameters
p Pointer to protect
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 411 of file safe_hazard_pointer.h.
{
        if (record_ != nullptr) {
            record_->protect(p, slot_);
        }
    }
References kcenon::thread::safe_hazard_pointer_record::protect(), record_, and slot_.
Referenced by kcenon::thread::detail::lockfree_job_queue::dequeue(), kcenon::thread::detail::lockfree_job_queue::empty(), and kcenon::thread::detail::lockfree_job_queue::enqueue().
Member Data Documentation
record_
safe_hazard_pointer_record* kcenon::thread::safe_hazard_guard::record_ private
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 441 of file safe_hazard_pointer.h.
Referenced by clear(), get(), operator bool(), operator=(), protect(), safe_hazard_guard(), and ~safe_hazard_guard().
slot_
size_t kcenon::thread::safe_hazard_guard::slot_ private
Examples
/home/runner/work/thread_system/thread_system/include/kcenon/thread/core/safe_hazard_pointer.h.
Definition at line 442 of file safe_hazard_pointer.h.
Referenced by clear(), get(), operator=(), protect(), and safe_hazard_guard().
The documentation for this class was generated from the following file:
include/kcenon/thread/core/safe_hazard_pointer.h