Thread System: kcenon::thread::thread_context Class Reference
kcenon::thread::thread_context Class Reference
Context object that provides access to optional services.
#include <thread_context.h>
Public Member Functions
thread_context ()
Default constructor - resolves services from global registry.
thread_context (std::shared_ptr< ILogger > logger, std::shared_ptr< IMonitor > monitoring=nullptr)
Constructor with explicit service injection.
std::shared_ptr< ILogger > logger () const
Get the logger service.
std::shared_ptr< IMonitor > monitoring () const
Get the monitoring service.
void log (common::interfaces::log_level level, const std::string &message) const
Log a message if logger is available.
void log (log_level_v2 level, const std::string &message) const
Log a message if logger is available (v2 API with conversion)
void log (common::interfaces::log_level level, std::string_view message, const common::source_location &loc=common::source_location::current()) const
Log a message with source location if logger is available.
void update_system_metrics (const common::interfaces::system_metrics &metrics) const
Update system metrics if monitoring is available.
void update_thread_pool_metrics (const common::interfaces::thread_pool_metrics &metrics) const
Update thread pool metrics if monitoring is available.
void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const common::interfaces::thread_pool_metrics &metrics) const
Update thread pool metrics with pool identifier.
void update_worker_metrics (std::size_t worker_id, const common::interfaces::worker_metrics &metrics) const
Update worker metrics if monitoring is available.
thread_context create_child () const
Create a child context with the same services.
auto get_context_name () const -> std::string
Get context name.
auto set_context_name (const std::string &name) -> bool
Set context name.
auto has_logger () const -> bool
Check if logger is available.
auto has_monitoring () const -> bool
Check if monitoring is available.
Static Private Member Functions
static common::interfaces::log_level to_common_level (log_level_v2 level)
Convert log_level_v2 to common::interfaces::log_level.
Private Attributes
std::shared_ptr< ILogger > logger_
std::shared_ptr< IMonitor > monitoring_
std::string context_name_
Detailed Description
Context object that provides access to optional services.
This class uses composition to provide thread system components with optional access to logger and monitoring services.
Note
Issue #261: Migrated to use common_system's ILogger interface.
Issue #312: Migrated to use common_system's IMonitor interface. The context now uses GlobalLoggerRegistry for default logger resolution.
Examples
composition_example.cpp, integration_example.cpp, minimal_thread_pool.cpp, and multi_process_monitoring_integration.cpp.
Definition at line 40 of file thread_context.h.
Constructor & Destructor Documentation
thread_context() [1/2]
kcenon::thread::thread_context::thread_context () inline
Default constructor - resolves services from global registry.
Definition at line 45 of file thread_context.h.
        : logger_(common::interfaces::GlobalLoggerRegistry::instance().get_default_logger())
        , monitoring_(service_container::global().resolve<common::interfaces::IMonitor>()) {
    }
Referenced by create_child().
thread_context() [2/2]
kcenon::thread::thread_context::thread_context (std::shared_ptr< ILogger > logger, std::shared_ptr< IMonitor > monitoring = nullptr) inline explicit
Constructor with explicit service injection.
Parameters
logger Optional logger service (ILogger from common_system)
monitoring Optional monitoring service (IMonitor from common_system)
Definition at line 55 of file thread_context.h.
        : logger_(std::move(logger))
        , monitoring_(std::move(monitoring)) {
    }
Member Function Documentation
create_child()
thread_context kcenon::thread::thread_context::create_child () const inline
Create a child context with the same services.
Returns
New context with shared services
Definition at line 244 of file thread_context.h.
{
        return thread_context(logger_, monitoring_);
    }
References logger_, monitoring_, and thread_context().
get_context_name()
auto kcenon::thread::thread_context::get_context_name () const -> std::string inline
Get context name.
Returns
Context name
Definition at line 252 of file thread_context.h.
{
        return context_name_;
    }
References context_name_.
has_logger()
auto kcenon::thread::thread_context::has_logger () const -> bool inline
Check if logger is available.
Returns
True if logger is set
Definition at line 270 of file thread_context.h.
{
        return logger_ != nullptr;
    }
References logger_.
has_monitoring()
auto kcenon::thread::thread_context::has_monitoring () const -> bool inline
Check if monitoring is available.
Returns
True if monitoring is set
Definition at line 278 of file thread_context.h.
{
        return monitoring_ != nullptr;
    }
References monitoring_.
log() [1/3]
void kcenon::thread::thread_context::log (common::interfaces::log_level level, const std::string & message) const inline
Log a message if logger is available.
Parameters
level Log level (common::interfaces::log_level)
message Log message
Note
Issue #261: Now uses common_system's ILogger interface.
Issue #295: Skips logging during static destruction to prevent SDOF.
Definition at line 86 of file thread_context.h.
{
        // Skip logging during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (logger_) {
            logger_->log(level, message);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and logger_.
log() [2/3]
void kcenon::thread::thread_context::log (common::interfaces::log_level level, std::string_view message, const common::source_location & loc = common::source_location::current()) const inline
Log a message with source location if logger is available.
Parameters
level Log level (common::interfaces::log_level)
message Log message
loc Source location (automatically captured)
Note
Issue #261: Now uses common_system's ILogger with source_location support.
Issue #295: Skips logging during static destruction to prevent SDOF.
Definition at line 123 of file thread_context.h.
{
        // Skip logging during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (logger_) {
            logger_->log(level, message, loc);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and logger_.
log() [3/3]
void kcenon::thread::thread_context::log (log_level_v2 level, const std::string & message) const inline
Log a message if logger is available (v2 API with conversion)
Parameters
level Log level (log_level_v2 with ascending order)
message Log message
Note
Provides backward compatibility for code using log_level_v2.
Issue #295: Skips logging during static destruction to prevent SDOF.
Definition at line 104 of file thread_context.h.
{
        // Skip logging during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (logger_) {
            logger_->log(to_common_level(level), message);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), logger_, and to_common_level().
logger()
std::shared_ptr< ILogger > kcenon::thread::thread_context::logger () const inline
Get the logger service.
Returns
Logger service or nullptr if not available
Definition at line 66 of file thread_context.h.
{
        return logger_;
    }
References logger_.
monitoring()
std::shared_ptr< IMonitor > kcenon::thread::thread_context::monitoring () const inline
Get the monitoring service.
Returns
Monitoring service or nullptr if not available
Definition at line 74 of file thread_context.h.
{
        return monitoring_;
    }
References monitoring_.
Referenced by kcenon::thread::thread_pool::report_metrics(), kcenon::thread::thread_pool::thread_pool(), kcenon::thread::thread_pool::thread_pool(), and kcenon::thread::thread_pool::thread_pool().
set_context_name()
auto kcenon::thread::thread_context::set_context_name (const std::string & name) -> bool inline
Set context name.
Parameters
name New context name
Returns
True if successful
Definition at line 261 of file thread_context.h.
{
        context_name_ = name;
        return true;
    }
References context_name_.
to_common_level()
static common::interfaces::log_level kcenon::thread::thread_context::to_common_level (log_level_v2 level) inline static private
Convert log_level_v2 to common::interfaces::log_level.
Definition at line 290 of file thread_context.h.
{
        switch (level) {
            case log_level_v2::trace: return common::interfaces::log_level::trace;
            case log_level_v2::debug: return common::interfaces::log_level::debug;
            case log_level_v2::info: return common::interfaces::log_level::info;
            case log_level_v2::warn: return common::interfaces::log_level::warning;
            case log_level_v2::error: return common::interfaces::log_level::error;
            case log_level_v2::critical: return common::interfaces::log_level::critical;
            case log_level_v2::off: return common::interfaces::log_level::off;
            default: return common::interfaces::log_level::info;
        }
    }
References kcenon::thread::critical, kcenon::thread::debug, kcenon::thread::error, kcenon::thread::info, kcenon::thread::off, kcenon::thread::trace, and kcenon::thread::warn.
Referenced by log().
update_system_metrics()
void kcenon::thread::thread_context::update_system_metrics (const common::interfaces::system_metrics & metrics) const inline
Update system metrics if monitoring is available.
Parameters
metrics System metrics to record
Note
Issue #295: Skips monitoring during static destruction to prevent SDOF.
Issue #312: Now uses common::interfaces::IMonitor::record_metric().
Definition at line 142 of file thread_context.h.
{
        // Skip monitoring during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (monitoring_) {
            std::unordered_map<std::string, std::string> tags{{"component", "system"}};
            monitoring_->record_metric("cpu_usage_percent", metrics.cpu_usage_percent.value, tags);
            monitoring_->record_metric("memory_usage_bytes", metrics.memory_usage_bytes.value, tags);
            monitoring_->record_metric("active_threads", metrics.active_threads.value, tags);
            monitoring_->record_metric("total_allocations", metrics.total_allocations.value, tags);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and monitoring_.
update_thread_pool_metrics() [1/2]
void kcenon::thread::thread_context::update_thread_pool_metrics (const common::interfaces::thread_pool_metrics & metrics) const inline
Update thread pool metrics if monitoring is available.
Parameters
metrics Thread pool metrics to record
Note
Issue #295: Skips monitoring during static destruction to prevent SDOF.
Issue #312: Now uses common::interfaces::IMonitor::record_metric().
Definition at line 163 of file thread_context.h.
{
        // Skip monitoring during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (monitoring_) {
            std::unordered_map<std::string, std::string> tags{
                {"component", "thread_pool"},
                {"pool_name", metrics.pool_name},
                {"pool_instance_id", std::to_string(metrics.pool_instance_id)}
            };
            monitoring_->record_metric("jobs_completed", metrics.jobs_completed.value, tags);
            monitoring_->record_metric("jobs_pending", metrics.jobs_pending.value, tags);
            monitoring_->record_metric("worker_threads", metrics.worker_threads.value, tags);
            monitoring_->record_metric("idle_threads", metrics.idle_threads.value, tags);
            monitoring_->record_metric("average_latency_ns", metrics.average_latency_ns.value, tags);
            monitoring_->record_metric("total_execution_time_ns", metrics.total_execution_time_ns.value, tags);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and monitoring_.
Referenced by kcenon::thread::thread_pool::report_metrics().
update_thread_pool_metrics() [2/2]
void kcenon::thread::thread_context::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const common::interfaces::thread_pool_metrics & metrics) const inline
Update thread pool metrics with pool identifier.
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools
metrics Thread pool metrics to record
Note
Issue #295: Skips monitoring during static destruction to prevent SDOF.
Issue #312: Now uses common::interfaces::IMonitor::record_metric().
Definition at line 192 of file thread_context.h.
{
        // Skip monitoring during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (monitoring_) {
            std::unordered_map<std::string, std::string> tags{
                {"component", "thread_pool"},
                {"pool_name", pool_name},
                {"pool_instance_id", std::to_string(pool_instance_id)}
            };
            monitoring_->record_metric("jobs_completed", metrics.jobs_completed.value, tags);
            monitoring_->record_metric("jobs_pending", metrics.jobs_pending.value, tags);
            monitoring_->record_metric("worker_threads", metrics.worker_threads.value, tags);
            monitoring_->record_metric("idle_threads", metrics.idle_threads.value, tags);
            monitoring_->record_metric("average_latency_ns", metrics.average_latency_ns.value, tags);
            monitoring_->record_metric("total_execution_time_ns", metrics.total_execution_time_ns.value, tags);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and monitoring_.
update_worker_metrics()
void kcenon::thread::thread_context::update_worker_metrics (std::size_t worker_id, const common::interfaces::worker_metrics & metrics) const inline
Update worker metrics if monitoring is available.
Parameters
worker_id Worker identifier
metrics Worker metrics to record
Note
Issue #295: Skips monitoring during static destruction to prevent SDOF.
Issue #312: Now uses common::interfaces::IMonitor::record_metric().
Definition at line 222 of file thread_context.h.
{
        // Skip monitoring during static destruction to prevent SDOF
        if (thread_logger::is_shutting_down()) {
            return;
        }
        if (monitoring_) {
            std::unordered_map<std::string, std::string> tags{
                {"component", "worker"},
                {"worker_id", std::to_string(worker_id)}
            };
            monitoring_->record_metric("jobs_processed", metrics.jobs_processed.value, tags);
            monitoring_->record_metric("total_processing_time_ns", metrics.total_processing_time_ns.value, tags);
            monitoring_->record_metric("idle_time_ns", metrics.idle_time_ns.value, tags);
            monitoring_->record_metric("context_switches", metrics.context_switches.value, tags);
        }
    }
References kcenon::thread::thread_logger::is_shutting_down(), and monitoring_.
Member Data Documentation
context_name_
std::string kcenon::thread::thread_context::context_name_ mutable private
Definition at line 285 of file thread_context.h.
Referenced by get_context_name(), and set_context_name().
logger_
std::shared_ptr<ILogger> kcenon::thread::thread_context::logger_ private
Definition at line 283 of file thread_context.h.
Referenced by create_child(), has_logger(), log(), log(), log(), and logger().
monitoring_
std::shared_ptr<IMonitor> kcenon::thread::thread_context::monitoring_ private
Definition at line 284 of file thread_context.h.
Referenced by create_child(), has_monitoring(), monitoring(), update_system_metrics(), update_thread_pool_metrics(), update_thread_pool_metrics(), and update_worker_metrics().
The documentation for this class was generated from the following file:
include/kcenon/thread/interfaces/thread_context.h