Thread System: kcenon::thread::metrics::MetricsBackend Class Reference
kcenon::thread::metrics::MetricsBackend Class Reference abstract
Metrics
Abstract interface for metrics export backends.
#include <metrics_backend.h>
Public Member Functions
virtual ~MetricsBackend ()=default
Virtual destructor for proper cleanup.
virtual std::string name () const =0
Get the backend name.
virtual std::string export_base (const BaseSnapshot &snapshot) const =0
Export base metrics snapshot.
virtual std::string export_enhanced (const EnhancedSnapshot &snapshot) const =0
Export enhanced metrics snapshot.
virtual void set_prefix (const std::string &prefix)
Set metric name prefix.
const std::string & prefix () const
Get current metric name prefix.
virtual void add_label (const std::string &key, const std::string &value)
Add a label to all exported metrics.
const std::map< std::string, std::string > & labels () const
Get all configured labels.
Protected Member Functions
MetricsBackend ()=default
Default constructor.
Protected Attributes
std::string prefix_ {"thread_pool"}
Metric name prefix.
std::map< std::string, std::string > labels_
Labels to attach to all metrics.
Detailed Description
Abstract interface for metrics export backends.
This interface defines the contract for exporting metrics to various monitoring systems (Prometheus, JSON, logging, etc.).
Implementation Guidelines
Implementations should be thread-safe
Export methods should not throw exceptions
Use canonical metric naming conventions
Example Implementation
class CustomBackend : public MetricsBackend {
public:
    std::string name() const override { return "custom"; }
    std::string export_base(const BaseSnapshot& snap) const override {
        // Export base metrics in custom format
    }
    std::string export_enhanced(const EnhancedSnapshot& snap) const override {
        // Export enhanced metrics in custom format
    }
};
See also
PrometheusBackend
JsonBackend
LoggingBackend
Definition at line 57 of file metrics_backend.h.
Constructor & Destructor Documentation
~MetricsBackend()
virtual kcenon::thread::metrics::MetricsBackend::~MetricsBackend () virtual default
Virtual destructor for proper cleanup.
MetricsBackend()
kcenon::thread::metrics::MetricsBackend::MetricsBackend () protected default
Default constructor.
Member Function Documentation
add_label()
virtual void kcenon::thread::metrics::MetricsBackend::add_label (const std::string & key, const std::string & value) inline virtual
Add a label to all exported metrics.
Parameters
key Label key.
value Label value.
Definition at line 107 of file metrics_backend.h.
{
        labels_[key] = value;
    }
References labels_.
export_base()
virtual std::string kcenon::thread::metrics::MetricsBackend::export_base (const BaseSnapshot & snapshot) const nodiscard pure virtual
Export base metrics snapshot.
Parameters
snapshot The base metrics snapshot to export.
Returns
Formatted string representation.
Implemented in kcenon::thread::metrics::JsonBackend, kcenon::thread::metrics::LoggingBackend, and kcenon::thread::metrics::PrometheusBackend.
export_enhanced()
virtual std::string kcenon::thread::metrics::MetricsBackend::export_enhanced (const EnhancedSnapshot & snapshot) const nodiscard pure virtual
Export enhanced metrics snapshot.
Parameters
snapshot The enhanced metrics snapshot to export.
Returns
Formatted string representation.
Implemented in kcenon::thread::metrics::JsonBackend, kcenon::thread::metrics::LoggingBackend, and kcenon::thread::metrics::PrometheusBackend.
labels()
const std::map< std::string, std::string > & kcenon::thread::metrics::MetricsBackend::labels () const inline nodiscard
Get all configured labels.
Returns
Map of label key-value pairs.
Definition at line 115 of file metrics_backend.h.
{
        return labels_;
    }
References labels_.
Referenced by kcenon::thread::metrics::PrometheusBackend::export_base(), and kcenon::thread::metrics::PrometheusBackend::export_enhanced().
name()
virtual std::string kcenon::thread::metrics::MetricsBackend::name () const nodiscard pure virtual
Get the backend name.
Returns
Human-readable backend identifier (e.g., "prometheus", "json").
Implemented in kcenon::thread::metrics::JsonBackend, kcenon::thread::metrics::LoggingBackend, and kcenon::thread::metrics::PrometheusBackend.
prefix()
const std::string & kcenon::thread::metrics::MetricsBackend::prefix () const inline nodiscard
Get current metric name prefix.
Returns
Current prefix string.
Definition at line 98 of file metrics_backend.h.
{
        return prefix_;
    }
References prefix_.
Referenced by set_prefix().
set_prefix()
virtual void kcenon::thread::metrics::MetricsBackend::set_prefix (const std::string & prefix) inline virtual
Set metric name prefix.
Parameters
prefix Prefix to prepend to all metric names.
Definition at line 90 of file metrics_backend.h.
{
        prefix_ = prefix;
    }
References prefix(), and prefix_.
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::to_prometheus().
Member Data Documentation
labels_
std::map<std::string, std::string> kcenon::thread::metrics::MetricsBackend::labels_ protected
Labels to attach to all metrics.
Definition at line 133 of file metrics_backend.h.
Referenced by add_label(), kcenon::thread::metrics::PrometheusBackend::export_enhanced(), kcenon::thread::metrics::PrometheusBackend::format_labels(), and labels().
prefix_
std::string kcenon::thread::metrics::MetricsBackend::prefix_ {"thread_pool"} protected
Metric name prefix.
Definition at line 128 of file metrics_backend.h.
{"thread_pool"};
Referenced by kcenon::thread::metrics::LoggingBackend::export_base(), kcenon::thread::metrics::PrometheusBackend::export_base(), kcenon::thread::metrics::LoggingBackend::export_enhanced(), kcenon::thread::metrics::PrometheusBackend::export_enhanced(), prefix(), and set_prefix().
The documentation for this class was generated from the following file:
include/kcenon/thread/metrics/metrics_backend.h