Thread System: kcenon::thread::aging_typed_job_queue_t< job_type > Class Template Reference
kcenon::thread::aging_typed_job_queue_t< job_type > Class Template Reference
A typed job queue with priority aging support, based on policy_queue.
#include <aging_typed_job_queue.h>
Public Types
using queue_type
Public Member Functions
aging_typed_job_queue_t (priority_aging_config config={})
Constructs an aging typed job queue.
~aging_typed_job_queue_t ()
Destroys the aging typed job queue.
aging_typed_job_queue_t (const aging_typed_job_queue_t &)=delete
auto operator= (const aging_typed_job_queue_t &) -> aging_typed_job_queue_t &=delete
aging_typed_job_queue_t (aging_typed_job_queue_t &&)=delete
auto operator= (aging_typed_job_queue_t &&) -> aging_typed_job_queue_t &=delete
auto start_aging () -> void
Starts the background aging thread.
auto stop_aging () -> void
Stops the background aging thread.
auto is_aging_running () const -> bool
Checks if aging is currently running.
auto apply_aging () -> std::size_t
Manually applies aging to all queued jobs.
auto get_starving_jobs () const -> std::vector< job_info >
Gets jobs that are approaching starvation.
auto get_aging_stats () const -> aging_stats
Gets aging statistics.
auto reset_aging_stats () -> void
Resets the aging statistics.
auto set_aging_config (priority_aging_config config) -> void
Sets the aging configuration.
auto get_aging_config () const -> const priority_aging_config &
Gets the current aging configuration.
auto enqueue (std::unique_ptr< aging_typed_job_t< job_type > > &&value) -> common::VoidResult
Enqueues an aging typed job.
auto register_aging_job (aging_typed_job_t< job_type > *job) -> void
Registers an aging job for tracking.
auto unregister_aging_job (aging_typed_job_t< job_type > *job) -> void
Unregisters an aging job from tracking.
auto enqueue (std::unique_ptr< job > &&value) -> common::VoidResult
Enqueues a base job into the queue.
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> common::VoidResult
Enqueues a typed job into the appropriate priority queue.
template<typename DerivedJob , typename = std::enable_if_t<std::is_base_of_v<typed_job_t<job_type>, DerivedJob>>>
auto enqueue (std::unique_ptr< DerivedJob > &&value) -> common::VoidResult
Enqueues a derived typed job.
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> common::VoidResult
Enqueues a batch of jobs.
auto dequeue () -> common::Result< std::unique_ptr< job > >
Dequeues the next available job.
auto dequeue (const std::vector< job_type > &types) -> common::Result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
auto dequeue (utility_module::span< const job_type > types) -> common::Result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
auto clear () -> void
Removes all jobs from all priority queues.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
auto empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
auto to_string () const -> std::string
Returns a string representation of the queue.
auto stop () -> void
Stops accepting new jobs and marks the queue as stopped.
auto size () const -> std::size_t
Gets the total number of jobs in all queues.
Private Member Functions
auto aging_loop () -> void
The main aging loop running in the background thread.
auto calculate_boost (std::chrono::milliseconds wait_time) const -> int
Calculates the priority boost for a given wait time.
auto check_starvation () -> void
Checks for starving jobs and invokes callbacks.
auto update_stats (std::size_t boosts_applied, std::chrono::milliseconds max_wait, std::chrono::milliseconds total_wait, std::size_t job_count) -> void
Updates statistics after applying aging.
auto get_or_create_queue (const job_type &type) -> queue_type *
Get or create a queue for the specified type.
auto try_dequeue_from_priority (const job_type &priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > >
Attempts to dequeue a single job from the queue for a given priority.
Private Attributes
priority_aging_config config_
std::unique_ptr< std::thread > aging_thread_
std::atomic< bool > aging_running_ {false}
std::atomic< bool > stopped_ {false}
std::condition_variable aging_cv_
std::mutex aging_mutex_
std::unordered_map< job_type, std::unique_ptr< queue_type > > job_queues_
std::shared_mutex queues_mutex_
std::vector< aging_typed_job_t< job_type > * > aging_jobs_
std::mutex jobs_mutex_
aging_stats stats_
std::mutex stats_mutex_
std::chrono::steady_clock::time_point stats_start_time_
Detailed Description
template<typename job_type = job_types>
class kcenon::thread::aging_typed_job_queue_t< job_type >
A typed job queue with priority aging support, based on policy_queue.
This class provides priority aging functionality using policy_queue internally instead of inheriting from typed_job_queue_t. It maintains API compatibility while leveraging the modern policy-based queue design.
Template Parameters
job_type The type used to represent priority levels.
Features
Background aging thread for periodic priority updates
Configurable aging curves (linear, exponential, logarithmic)
Starvation detection and alerting
Statistics tracking
Uses policy_queue internally for efficient queue operations
Thread Safety
All public methods are thread-safe.
Example Usage
priority_aging_config config{
    .enabled = true,
    .aging_interval = std::chrono::seconds{1},
    .max_priority_boost = 3
};
auto queue = std::make_shared<aging_typed_job_queue_t<job_types>>(config);
queue->start_aging();
// Enqueue jobs...
queue->enqueue(std::make_unique<aging_typed_job_t<job_types>>(...));
// When done
queue->stop_aging();
Definition at line 88 of file aging_typed_job_queue.h.
Member Typedef Documentation
queue_type
template<typename job_type = job_types> using kcenon::thread::aging_typed_job_queue_t< job_type >::queue_type
Initial value:
 policy_queue<policies::mutex_sync_policy,
                                        policies::unbounded_policy,
                                        policies::overflow_reject_policy>
Definition at line 91 of file aging_typed_job_queue.h.
Constructor & Destructor Documentation
aging_typed_job_queue_t() [1/3]
template<typename job_type > kcenon::thread::aging_typed_job_queue_t< job_type >::aging_typed_job_queue_t (priority_aging_config config = {}) explicit
Constructs an aging typed job queue.
Parameters
config The aging configuration.
Definition at line 14 of file aging_typed_job_queue.cpp.
        : config_(std::move(config))
        , stats_start_time_(std::chrono::steady_clock::now())
    {
    }
~aging_typed_job_queue_t()
template<typename job_type > kcenon::thread::aging_typed_job_queue_t< job_type >::~aging_typed_job_queue_t ()
Destroys the aging typed job queue.
Stops the aging thread if running.
Definition at line 21 of file aging_typed_job_queue.cpp.
    {
        stop_aging();
    }
aging_typed_job_queue_t() [2/3]
template<typename job_type = job_types> kcenon::thread::aging_typed_job_queue_t< job_type >::aging_typed_job_queue_t (const aging_typed_job_queue_t< job_type > &) delete
aging_typed_job_queue_t() [3/3]
template<typename job_type = job_types> kcenon::thread::aging_typed_job_queue_t< job_type >::aging_typed_job_queue_t (aging_typed_job_queue_t< job_type > &&) delete
Member Function Documentation
aging_loop()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::aging_loop () -> void private
The main aging loop running in the background thread.
Definition at line 66 of file aging_typed_job_queue.cpp.
    {
        while (aging_running_.load())
        {
            {
                std::unique_lock lock(aging_mutex_);
                aging_cv_.wait_for(lock, config_.aging_interval, [this]() {
                    return !aging_running_.load();
                });
            }
            if (!aging_running_.load())
            {
                break;
            }
            if (config_.enabled)
            {
                apply_aging();
                check_starvation();
            }
        }
    }
apply_aging()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::apply_aging () -> std::size_t
Manually applies aging to all queued jobs.
This is useful for testing or when you want to trigger aging on demand without waiting for the background thread.
Returns
The number of jobs that received priority boosts.
Definition at line 91 of file aging_typed_job_queue.cpp.
    {
        std::lock_guard jobs_lock(jobs_mutex_);
        std::size_t boosts_applied = 0;
        std::chrono::milliseconds max_wait{0};
        std::chrono::milliseconds total_wait{0};
        for (auto* job : aging_jobs_)
        {
            if (!job)
            {
                continue;
            }
            auto wait = job->wait_time();
            total_wait += wait;
            if (wait > max_wait)
            {
                max_wait = wait;
            }
            // Calculate number of intervals waited
            auto intervals = wait.count() / config_.aging_interval.count();
            if (intervals > 0)
            {
                auto boost = calculate_boost(wait);
                if (boost > 0 && !job->is_max_boosted())
                {
                    job->apply_boost(boost);
                    ++boosts_applied;
                    if (job->is_max_boosted())
                    {
                        std::lock_guard stats_lock(stats_mutex_);
                        ++stats_.jobs_reached_max_boost;
                    }
                }
            }
        }
        if (!aging_jobs_.empty())
        {
            update_stats(boosts_applied, max_wait, total_wait, aging_jobs_.size());
        }
        return boosts_applied;
    }
calculate_boost()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::calculate_boost (std::chrono::milliseconds wait_time) const -> int nodiscard private
Calculates the priority boost for a given wait time.
Parameters
wait_time The time the job has been waiting.
Returns
The calculated boost amount.
Definition at line 142 of file aging_typed_job_queue.cpp.
    {
        auto intervals = static_cast<double>(wait_time.count()) /
                         static_cast<double>(config_.aging_interval.count());
        int boost = 0;
        switch (config_.curve)
        {
        case aging_curve::linear:
            boost = static_cast<int>(intervals) * config_.priority_boost_per_interval;
            break;
        case aging_curve::exponential:
            // Exponential: boost increases faster over time
            boost = static_cast<int>(
                std::pow(config_.exponential_factor, intervals) - 1.0
            ) * config_.priority_boost_per_interval;
            break;
        case aging_curve::logarithmic:
            // Logarithmic: fast initial boost, slower over time
            if (intervals > 0)
            {
                boost = static_cast<int>(
                    std::log(intervals + 1) / std::log(2.0)
                ) * config_.priority_boost_per_interval;
            }
            break;
        }
        // Cap at max boost
        return std::min(boost, config_.max_priority_boost);
    }
check_starvation()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::check_starvation () -> void private
Checks for starving jobs and invokes callbacks.
Definition at line 179 of file aging_typed_job_queue.cpp.
    {
        if (!config_.starvation_callback)
        {
            return;
        }
        auto threshold = std::chrono::duration_cast<std::chrono::milliseconds>(
            config_.starvation_threshold
        );
        std::lock_guard jobs_lock(jobs_mutex_);
        for (auto* job : aging_jobs_)
        {
            if (!job)
            {
                continue;
            }
            if (job->wait_time() > threshold)
            {
                config_.starvation_callback(job->to_job_info());
                {
                    std::lock_guard stats_lock(stats_mutex_);
                    ++stats_.starvation_alerts;
                }
            }
        }
    }
clear()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::clear () -> void
Removes all jobs from all priority queues.
Definition at line 539 of file aging_typed_job_queue.cpp.
    {
        std::unique_lock lock(queues_mutex_);
        for (auto& [type, queue] : job_queues_)
        {
            if (queue)
            {
                queue->clear();
            }
        }
        {
            std::lock_guard jobs_lock(jobs_mutex_);
            aging_jobs_.clear();
        }
    }
dequeue() [1/3]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::dequeue () -> common::Result<std::unique_ptr<job>> nodiscard
Dequeues the next available job.
Returns
Result containing the dequeued job or error.
Definition at line 446 of file aging_typed_job_queue.cpp.
    {
        std::shared_lock lock(queues_mutex_);
        for (auto& [type, queue] : job_queues_)
        {
            if (queue && !queue->empty())
            {
                auto result = queue->dequeue();
                if (result.is_ok())
                {
                    return result;
                }
            }
        }
        return common::error_info{
            static_cast<int>(error_code::job_invalid),
            "No job available",
            "thread_system"
        };
    }
References kcenon::thread::result< T >::is_ok(), and kcenon::thread::job_invalid.
dequeue() [2/3]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::dequeue (const std::vector< job_type > & types) -> common::Result<std::unique_ptr<typed_job_t<job_type>>> nodiscard
Dequeues a job with one of the specified types.
Parameters
types A list of priority levels from which to attempt a dequeue.
Returns
Result containing the dequeued job or error.
Definition at line 499 of file aging_typed_job_queue.cpp.
    {
        for (const auto& type : types)
        {
            auto result = try_dequeue_from_priority(type);
            if (result.has_value())
            {
                return std::move(result.value());
            }
        }
        return common::error_info{
            static_cast<int>(error_code::job_invalid),
            "No job available for specified types",
            "thread_system"
        };
    }
References kcenon::thread::result< T >::has_value(), kcenon::thread::job_invalid, and kcenon::thread::result< T >::value().
dequeue() [3/3]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> common::Result<std::unique_ptr<typed_job_t<job_type>>> nodiscard
Dequeues a job with one of the specified types using span.
Parameters
types A span of priority levels from which to attempt a dequeue.
Returns
Result containing the dequeued job or error.
Definition at line 519 of file aging_typed_job_queue.cpp.
    {
        for (const auto& type : types)
        {
            auto result = try_dequeue_from_priority(type);
            if (result.has_value())
            {
                return std::move(result.value());
            }
        }
        return common::error_info{
            static_cast<int>(error_code::job_invalid),
            "No job available for specified types",
            "thread_system"
        };
    }
References kcenon::thread::result< T >::has_value(), kcenon::thread::job_invalid, and kcenon::thread::result< T >::value().
empty() [1/2]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool nodiscard
Checks if there are no jobs in any of the specified priority queues.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty.
Definition at line 558 of file aging_typed_job_queue.cpp.
    {
        std::shared_lock lock(queues_mutex_);
        for (const auto& type : types)
        {
            auto it = job_queues_.find(type);
            if (it != job_queues_.end() && it->second && !it->second->empty())
            {
                return false;
            }
        }
        return true;
    }
empty() [2/2]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::empty (utility_module::span< const job_type > types) const -> bool nodiscard
Checks if there are no jobs in any of the specified priority queues using span.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty.
Definition at line 575 of file aging_typed_job_queue.cpp.
    {
        std::shared_lock lock(queues_mutex_);
        for (const auto& type : types)
        {
            auto it = job_queues_.find(type);
            if (it != job_queues_.end() && it->second && !it->second->empty())
            {
                return false;
            }
        }
        return true;
    }
enqueue() [1/4]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue (std::unique_ptr< aging_typed_job_t< job_type > > && value) -> common::VoidResult nodiscard
Enqueues an aging typed job.
Parameters
value The job to enqueue.
Returns
Result indicating success or failure.
Definition at line 263 of file aging_typed_job_queue.cpp.
    {
        if (!value)
        {
            return common::error_info{
                static_cast<int>(error_code::invalid_argument),
                "Null job",
                "thread_system"
            };
        }
        if (stopped_.load())
        {
            return common::error_info{
                static_cast<int>(error_code::queue_stopped),
                "Queue is stopped",
                "thread_system"
            };
        }
        // Register for aging tracking
        register_aging_job(value.get());
        // Set max boost from config
        value->set_max_boost(config_.max_priority_boost);
        // Get the priority and enqueue to appropriate queue
        auto priority = value->priority();
        auto* queue = get_or_create_queue(priority);
        return queue->enqueue(std::move(value));
    }
References kcenon::thread::invalid_argument.
Referenced by kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue().
enqueue() [2/4]
template<typename job_type = job_types> template<typename DerivedJob , typename = std::enable_if_t<std::is_base_of_v<typed_job_t<job_type>, DerivedJob>>> auto kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue (std::unique_ptr< DerivedJob > && value) -> common::VoidResult inline nodiscard
Enqueues a derived typed job.
Template Parameters
DerivedJob A type that derives from typed_job_t<job_type>
Parameters
value A unique pointer to the derived job to enqueue.
Returns
Result indicating success or failure.
Definition at line 251 of file aging_typed_job_queue.h.
        {
            return enqueue(std::unique_ptr<typed_job_t<job_type>>(std::move(value)));
        }
References kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue().
enqueue() [3/4]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue (std::unique_ptr< job > && value) -> common::VoidResult nodiscard
Enqueues a base job into the queue.
Parameters
value A unique pointer to the base job to enqueue.
Returns
Result indicating success or failure.
Definition at line 378 of file aging_typed_job_queue.cpp.
    {
        if (!value)
        {
            return common::error_info{
                static_cast<int>(error_code::invalid_argument),
                "Null job",
                "thread_system"
            };
        }
        if (stopped_.load())
        {
            return common::error_info{
                static_cast<int>(error_code::queue_stopped),
                "Queue is stopped",
                "thread_system"
            };
        }
        // For non-typed jobs, use default priority
        auto* queue = get_or_create_queue(job_type{});
        return queue->enqueue(std::move(value));
    }
References kcenon::thread::invalid_argument.
enqueue() [4/4]
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> common::VoidResult nodiscard
Enqueues a typed job into the appropriate priority queue.
Parameters
value A unique pointer to the typed job to enqueue.
Returns
Result indicating success or failure.
Definition at line 404 of file aging_typed_job_queue.cpp.
    {
        if (!value)
        {
            return common::error_info{
                static_cast<int>(error_code::invalid_argument),
                "Null job",
                "thread_system"
            };
        }
        if (stopped_.load())
        {
            return common::error_info{
                static_cast<int>(error_code::queue_stopped),
                "Queue is stopped",
                "thread_system"
            };
        }
        auto priority = value->priority();
        auto* queue = get_or_create_queue(priority);
        return queue->enqueue(std::move(value));
    }
References kcenon::thread::invalid_argument, kcenon::thread::priority, and kcenon::thread::queue_stopped.
enqueue_batch()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> common::VoidResult nodiscard
Enqueues a batch of jobs.
Parameters
jobs A vector of unique pointers to jobs to enqueue.
Returns
Result indicating success or failure.
Definition at line 431 of file aging_typed_job_queue.cpp.
    {
        for (auto& job : jobs)
        {
            auto result = enqueue(std::move(job));
            if (result.is_err())
            {
                return result;
            }
        }
        return common::ok();
    }
get_aging_config()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::get_aging_config () const -> const priority_aging_config& nodiscard
Gets the current aging configuration.
Returns
A const reference to the configuration.
Definition at line 256 of file aging_typed_job_queue.cpp.
    {
        return config_;
    }
get_aging_stats()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::get_aging_stats () const -> aging_stats nodiscard
Gets aging statistics.
Returns
The current aging statistics.
Definition at line 234 of file aging_typed_job_queue.cpp.
    {
        std::lock_guard lock(stats_mutex_);
        return stats_;
    }
get_or_create_queue()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::get_or_create_queue (const job_type & type) -> queue_type* private
Get or create a queue for the specified type.
Parameters
type The job type.
Returns
Pointer to the queue.
Definition at line 365 of file aging_typed_job_queue.cpp.
    {
        std::unique_lock lock(queues_mutex_);
        auto it = job_queues_.find(type);
        if (it == job_queues_.end())
        {
            auto [new_it, inserted] = job_queues_.emplace(type, std::make_unique<queue_type>());
            return new_it->second.get();
        }
        return it->second.get();
    }
get_starving_jobs()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::get_starving_jobs () const -> std::vector<job_info> nodiscard
Gets jobs that are approaching starvation.
Returns
A vector of job_info for jobs waiting longer than the threshold.
Definition at line 212 of file aging_typed_job_queue.cpp.
    {
        std::vector<job_info> result;
        auto threshold = std::chrono::duration_cast<std::chrono::milliseconds>(
            config_.starvation_threshold
        );
        std::lock_guard lock(jobs_mutex_);
        for (auto* job : aging_jobs_)
        {
            if (job && job->wait_time() > threshold)
            {
                result.push_back(job->to_job_info());
            }
        }
        return result;
    }
is_aging_running()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::is_aging_running () const -> bool nodiscard
Checks if aging is currently running.
Returns
true if the aging thread is active.
Definition at line 60 of file aging_typed_job_queue.cpp.
    {
        return aging_running_.load();
    }
operator=() [1/2]
template<typename job_type = job_types> auto kcenon::thread::aging_typed_job_queue_t< job_type >::operator= (aging_typed_job_queue_t< job_type > &&) -> aging_typed_job_queue_t &=delete delete
operator=() [2/2]
template<typename job_type = job_types> auto kcenon::thread::aging_typed_job_queue_t< job_type >::operator= (const aging_typed_job_queue_t< job_type > &) -> aging_typed_job_queue_t &=delete delete
register_aging_job()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::register_aging_job (aging_typed_job_t< job_type > * job) -> void
Registers an aging job for tracking.
Parameters
job Pointer to the job to track.
Definition at line 297 of file aging_typed_job_queue.cpp.
    {
        if (!job)
        {
            return;
        }
        std::lock_guard lock(jobs_mutex_);
        aging_jobs_.push_back(job);
    }
reset_aging_stats()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::reset_aging_stats () -> void
Resets the aging statistics.
Definition at line 241 of file aging_typed_job_queue.cpp.
    {
        std::lock_guard lock(stats_mutex_);
        stats_ = aging_stats{};
        stats_start_time_ = std::chrono::steady_clock::now();
    }
set_aging_config()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::set_aging_config (priority_aging_config config) -> void
Sets the aging configuration.
Parameters
config The new configuration.
Definition at line 249 of file aging_typed_job_queue.cpp.
    {
        std::lock_guard lock(aging_mutex_);
        config_ = std::move(config);
    }
size()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::size () const -> std::size_t nodiscard
Gets the total number of jobs in all queues.
Returns
The total number of jobs.
Definition at line 619 of file aging_typed_job_queue.cpp.
    {
        std::shared_lock lock(queues_mutex_);
        std::size_t total = 0;
        for (const auto& [type, queue] : job_queues_)
        {
            if (queue)
            {
                total += queue->size();
            }
        }
        return total;
    }
start_aging()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::start_aging () -> void
Starts the background aging thread.
The aging thread periodically applies priority boosts to waiting jobs.
Definition at line 27 of file aging_typed_job_queue.cpp.
    {
        if (aging_running_.exchange(true))
        {
            return; // Already running
        }
        aging_thread_ = std::make_unique<std::thread>([this]() {
            aging_loop();
        });
    }
stop()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::stop () -> void
Stops accepting new jobs and marks the queue as stopped.
Definition at line 604 of file aging_typed_job_queue.cpp.
    {
        stopped_.store(true);
        std::unique_lock lock(queues_mutex_);
        for (auto& [type, queue] : job_queues_)
        {
            if (queue)
            {
                queue->stop();
            }
        }
    }
stop_aging()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::stop_aging () -> void
Stops the background aging thread.
Definition at line 40 of file aging_typed_job_queue.cpp.
    {
        if (!aging_running_.exchange(false))
        {
            return; // Not running
        }
        {
            std::lock_guard lock(aging_mutex_);
            aging_cv_.notify_all();
        }
        if (aging_thread_ && aging_thread_->joinable())
        {
            aging_thread_->join();
        }
        aging_thread_.reset();
    }
to_string()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::to_string () const -> std::string nodiscard
Returns a string representation of the queue.
Returns
A string describing the current state of the queue.
Definition at line 592 of file aging_typed_job_queue.cpp.
    {
        std::ostringstream oss;
        oss << "aging_typed_job_queue{";
        oss << "aging_running: " << (aging_running_.load() ? "true" : "false");
        oss << ", stopped: " << (stopped_.load() ? "true" : "false");
        oss << ", total_jobs: " << size();
        oss << "}";
        return oss.str();
    }
try_dequeue_from_priority()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::try_dequeue_from_priority (const job_type & priority) -> std::optional<std::unique_ptr<typed_job_t<job_type>>> nodiscard private
Attempts to dequeue a single job from the queue for a given priority.
Parameters
priority The priority level from which to dequeue.
Returns
The dequeued job, or std::nullopt if empty.
Definition at line 470 of file aging_typed_job_queue.cpp.
    {
        std::shared_lock lock(queues_mutex_);
        auto it = job_queues_.find(priority);
        if (it == job_queues_.end() || !it->second || it->second->empty())
        {
            return std::nullopt;
        }
        auto result = it->second->dequeue();
        if (result.is_err())
        {
            return std::nullopt;
        }
        auto job = std::move(result.value());
        // Cast back to typed_job_t if possible
        auto* typed_ptr = dynamic_cast<typed_job_t<job_type>*>(job.release());
        if (typed_ptr)
        {
            return std::unique_ptr<typed_job_t<job_type>>(typed_ptr);
        }
        return std::nullopt;
    }
References kcenon::thread::priority, and kcenon::thread::result< T >::value().
unregister_aging_job()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::unregister_aging_job (aging_typed_job_t< job_type > * job) -> void
Unregisters an aging job from tracking.
Parameters
job Pointer to the job to unregister.
Definition at line 310 of file aging_typed_job_queue.cpp.
    {
        if (!job)
        {
            return;
        }
        std::lock_guard lock(jobs_mutex_);
        auto it = std::find(aging_jobs_.begin(), aging_jobs_.end(), job);
        if (it != aging_jobs_.end())
        {
            aging_jobs_.erase(it);
        }
    }
update_stats()
template<typename job_type > auto kcenon::thread::aging_typed_job_queue_t< job_type >::update_stats (std::size_t boosts_applied, std::chrono::milliseconds max_wait, std::chrono::milliseconds total_wait, std::size_t job_count) -> void private
Updates statistics after applying aging.
Parameters
boosts_applied Number of boosts applied in this cycle.
max_wait Maximum wait time observed.
total_wait Total wait time for average calculation.
job_count Number of jobs processed.
Definition at line 327 of file aging_typed_job_queue.cpp.
    {
        std::lock_guard lock(stats_mutex_);
        stats_.total_boosts_applied += boosts_applied;
        if (max_wait > stats_.max_wait_time)
        {
            stats_.max_wait_time = max_wait;
        }
        if (job_count > 0)
        {
            stats_.avg_wait_time = std::chrono::milliseconds{
                total_wait.count() / static_cast<long long>(job_count)
            };
        }
        // Calculate boost rate (boosts per second)
        auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::steady_clock::now() - stats_start_time_
        );
        if (elapsed.count() > 0)
        {
            stats_.boost_rate = static_cast<double>(stats_.total_boosts_applied) /
                                static_cast<double>(elapsed.count());
        }
    }
Member Data Documentation
aging_cv_
template<typename job_type = job_types> std::condition_variable kcenon::thread::aging_typed_job_queue_t< job_type >::aging_cv_ private
Definition at line 335 of file aging_typed_job_queue.h.
aging_jobs_
template<typename job_type = job_types> std::vector<aging_typed_job_t<job_type>*> kcenon::thread::aging_typed_job_queue_t< job_type >::aging_jobs_ private
Definition at line 343 of file aging_typed_job_queue.h.
aging_mutex_
template<typename job_type = job_types> std::mutex kcenon::thread::aging_typed_job_queue_t< job_type >::aging_mutex_ mutable private
Definition at line 336 of file aging_typed_job_queue.h.
aging_running_
template<typename job_type = job_types> std::atomic<bool> kcenon::thread::aging_typed_job_queue_t< job_type >::aging_running_ {false} private
Definition at line 333 of file aging_typed_job_queue.h.
{false};
aging_thread_
template<typename job_type = job_types> std::unique_ptr<std::thread> kcenon::thread::aging_typed_job_queue_t< job_type >::aging_thread_ private
Definition at line 332 of file aging_typed_job_queue.h.
config_
template<typename job_type = job_types> priority_aging_config kcenon::thread::aging_typed_job_queue_t< job_type >::config_ private
Definition at line 331 of file aging_typed_job_queue.h.
job_queues_
template<typename job_type = job_types> std::unordered_map<job_type, std::unique_ptr<queue_type> > kcenon::thread::aging_typed_job_queue_t< job_type >::job_queues_ private
Definition at line 339 of file aging_typed_job_queue.h.
jobs_mutex_
template<typename job_type = job_types> std::mutex kcenon::thread::aging_typed_job_queue_t< job_type >::jobs_mutex_ mutable private
Definition at line 344 of file aging_typed_job_queue.h.
queues_mutex_
template<typename job_type = job_types> std::shared_mutex kcenon::thread::aging_typed_job_queue_t< job_type >::queues_mutex_ mutable private
Definition at line 340 of file aging_typed_job_queue.h.
stats_
template<typename job_type = job_types> aging_stats kcenon::thread::aging_typed_job_queue_t< job_type >::stats_ private
Definition at line 347 of file aging_typed_job_queue.h.
stats_mutex_
template<typename job_type = job_types> std::mutex kcenon::thread::aging_typed_job_queue_t< job_type >::stats_mutex_ mutable private
Definition at line 348 of file aging_typed_job_queue.h.
stats_start_time_
template<typename job_type = job_types> std::chrono::steady_clock::time_point kcenon::thread::aging_typed_job_queue_t< job_type >::stats_start_time_ private
Definition at line 349 of file aging_typed_job_queue.h.
stopped_
template<typename job_type = job_types> std::atomic<bool> kcenon::thread::aging_typed_job_queue_t< job_type >::stopped_ {false} private
Definition at line 334 of file aging_typed_job_queue.h.
{false};
The documentation for this class was generated from the following files:
include/kcenon/thread/impl/typed_pool/aging_typed_job_queue.h
src/impl/typed_pool/aging_typed_job_queue.cpp