Thread System: kcenon::thread::metrics::BackendRegistry Class Reference
kcenon::thread::metrics::BackendRegistry Class Reference
Backend registry for managing multiple export formats.
#include <metrics_backend.h>
Public Member Functions
void register_backend (std::shared_ptr< MetricsBackend > backend)
Register a backend.
std::shared_ptr< MetricsBackend > get (const std::string &name) const
Get a backend by name.
bool has (const std::string &name) const
Check if a backend is registered.
Static Public Member Functions
static BackendRegistry & instance ()
Get the singleton instance.
Private Member Functions
BackendRegistry ()
Private Attributes
std::map< std::string, std::shared_ptr< MetricsBackend > > backends_
Detailed Description
Backend registry for managing multiple export formats.
Allows registration and retrieval of metrics backends by name.
Definition at line 264 of file metrics_backend.h.
Constructor & Destructor Documentation
BackendRegistry()
kcenon::thread::metrics::BackendRegistry::BackendRegistry () inline private
Definition at line 306 of file metrics_backend.h.
                      {
        // Register default backends
        register_backend(std::make_shared<PrometheusBackend>());
        register_backend(std::make_shared<JsonBackend>());
        register_backend(std::make_shared<LoggingBackend>());
    }
References register_backend().
Member Function Documentation
get()
std::shared_ptr< MetricsBackend > kcenon::thread::metrics::BackendRegistry::get (const std::string & name) const inline nodiscard
Get a backend by name.
Parameters
name Backend identifier.
Returns
Shared pointer to the backend, or nullptr if not found.
Definition at line 290 of file metrics_backend.h.
{
        auto it = backends_.find(name);
        return (it != backends_.end()) ? it->second : nullptr;
    }
References backends_.
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::to_json().
has()
bool kcenon::thread::metrics::BackendRegistry::has (const std::string & name) const inline nodiscard
Check if a backend is registered.
Parameters
name Backend identifier.
Returns
True if registered.
Definition at line 301 of file metrics_backend.h.
{
        return backends_.find(name) != backends_.end();
    }
References backends_.
instance()
static BackendRegistry & kcenon::thread::metrics::BackendRegistry::instance () inline static
Get the singleton instance.
Returns
Reference to the global registry.
Definition at line 270 of file metrics_backend.h.
{
        static BackendRegistry registry;
        return registry;
    }
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::to_json().
register_backend()
void kcenon::thread::metrics::BackendRegistry::register_backend (std::shared_ptr< MetricsBackend > backend) inline
Register a backend.
Parameters
backend Shared pointer to the backend.
Definition at line 279 of file metrics_backend.h.
{
        if (backend) {
            backends_[backend->name()] = std::move(backend);
        }
    }
References backends_.
Referenced by BackendRegistry().
Member Data Documentation
backends_
std::map<std::string, std::shared_ptr<MetricsBackend> > kcenon::thread::metrics::BackendRegistry::backends_ private
Definition at line 313 of file metrics_backend.h.
Referenced by get(), has(), and register_backend().
The documentation for this class was generated from the following file:
include/kcenon/thread/metrics/metrics_backend.h