Thread System: kcenon::thread::event_bus::subscription Class Reference
kcenon::thread::event_bus::subscription Class Reference
Subscription handle for managing subscriptions.
#include <event_bus.h>
Public Member Functions
subscription ()=default
subscription (event_bus *bus, std::type_index type, std::size_t id)
void unsubscribe ()
Unsubscribe from events.
bool is_active () const
Check if subscription is active.
subscription (subscription &&other) noexcept
subscription & operator= (subscription &&other) noexcept
subscription (const subscription &)=delete
subscription & operator= (const subscription &)=delete
~subscription ()
Private Attributes
event_bus * bus_ {nullptr}
std::type_index type_ {typeid(void)}
std::size_t id_ {0}
Detailed Description
Subscription handle for managing subscriptions.
Definition at line 65 of file event_bus.h.
Constructor & Destructor Documentation
subscription() [1/4]
kcenon::thread::event_bus::subscription::subscription () default
subscription() [2/4]
kcenon::thread::event_bus::subscription::subscription (event_bus * bus, std::type_index type, std::size_t id) inline
Definition at line 68 of file event_bus.h.
            : bus_(bus), type_(type), id_(id) {}
subscription() [3/4]
kcenon::thread::event_bus::subscription::subscription (subscription && other) inline noexcept
Definition at line 89 of file event_bus.h.
            : bus_(other.bus_), type_(other.type_), id_(other.id_) {
            other.bus_ = nullptr;
        }
subscription() [4/4]
kcenon::thread::event_bus::subscription::subscription (const subscription &) delete
~subscription()
kcenon::thread::event_bus::subscription::~subscription () inline
Definition at line 109 of file event_bus.h.
{
            unsubscribe();
        }
References unsubscribe().
Member Function Documentation
is_active()
bool kcenon::thread::event_bus::subscription::is_active () const inline
Check if subscription is active.
Definition at line 84 of file event_bus.h.
{
            return bus_ != nullptr;
        }
References bus_.
operator=() [1/2]
subscription & kcenon::thread::event_bus::subscription::operator= (const subscription &) delete
operator=() [2/2]
subscription & kcenon::thread::event_bus::subscription::operator= (subscription && other) inline noexcept
Definition at line 94 of file event_bus.h.
{
            if (this != &other) {
                unsubscribe();
                bus_ = other.bus_;
                type_ = other.type_;
                id_ = other.id_;
                other.bus_ = nullptr;
            }
            return *this;
        }
References bus_, id_, type_, and unsubscribe().
unsubscribe()
void kcenon::thread::event_bus::subscription::unsubscribe () inline
Unsubscribe from events.
Definition at line 74 of file event_bus.h.
{
            if (bus_) {
                bus_->unsubscribe(type_, id_);
                bus_ = nullptr;
            }
        }
References bus_, id_, type_, and kcenon::thread::event_bus::unsubscribe().
Referenced by operator=(), and ~subscription().
Member Data Documentation
bus_
event_bus* kcenon::thread::event_bus::subscription::bus_ {nullptr} private
Definition at line 114 of file event_bus.h.
{nullptr};
Referenced by is_active(), operator=(), and unsubscribe().
id_
std::size_t kcenon::thread::event_bus::subscription::id_ {0} private
Definition at line 116 of file event_bus.h.
{0};
Referenced by operator=(), and unsubscribe().
type_
std::type_index kcenon::thread::event_bus::subscription::type_ {typeid(void)} private
Definition at line 115 of file event_bus.h.
{typeid(void)};
Referenced by operator=(), and unsubscribe().
The documentation for this class was generated from the following file:
include/kcenon/thread/core/event_bus.h