Thread System: kcenon::thread::metrics::PrometheusBackend Class Reference
kcenon::thread::metrics::PrometheusBackend Class Reference
Prometheus/OpenMetrics format backend.
#include <metrics_backend.h>
Public Member Functions
PrometheusBackend ()=default
Default constructor.
~PrometheusBackend () override=default
Destructor.
std::string name () const override
Get the backend name.
std::string export_base (const BaseSnapshot &snapshot) const override
Export base metrics snapshot.
std::string export_enhanced (const EnhancedSnapshot &snapshot) const override
Export enhanced metrics snapshot.
Public Member Functions inherited from kcenon::thread::metrics::MetricsBackend
virtual ~MetricsBackend ()=default
Virtual destructor for proper cleanup.
virtual void set_prefix (const std::string &prefix)
Set metric name prefix.
const std::string & prefix () const
Get current metric name prefix.
virtual void add_label (const std::string &key, const std::string &value)
Add a label to all exported metrics.
const std::map< std::string, std::string > & labels () const
Get all configured labels.
Private Member Functions
std::string format_labels () const
Format labels for Prometheus output.
Additional Inherited Members
Protected Member Functions inherited from kcenon::thread::metrics::MetricsBackend
MetricsBackend ()=default
Default constructor.
Protected Attributes inherited from kcenon::thread::metrics::MetricsBackend
std::string prefix_ {"thread_pool"}
Metric name prefix.
std::map< std::string, std::string > labels_
Labels to attach to all metrics.
Detailed Description
Prometheus/OpenMetrics format backend.
Exports metrics in Prometheus exposition format, suitable for scraping by Prometheus servers.
Output Format
# HELP thread_pool_tasks_submitted_total Total tasks submitted
# TYPE thread_pool_tasks_submitted_total counter
thread_pool_tasks_submitted_total 1234
Definition at line 149 of file metrics_backend.h.
Constructor & Destructor Documentation
PrometheusBackend()
kcenon::thread::metrics::PrometheusBackend::PrometheusBackend () default
Default constructor.
~PrometheusBackend()
kcenon::thread::metrics::PrometheusBackend::~PrometheusBackend () override default
Destructor.
Member Function Documentation
export_base()
std::string kcenon::thread::metrics::PrometheusBackend::export_base (const BaseSnapshot & snapshot) const nodiscard override virtual
Export base metrics snapshot.
Parameters
snapshot The base metrics snapshot to export.
Returns
Formatted string representation.
Implements kcenon::thread::metrics::MetricsBackend.
Definition at line 35 of file metrics_backend.cpp.
{
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(6);
    const auto& p = prefix_;
    const auto labels = format_labels();
    // Task counters
    oss << "# HELP " << p << "_tasks_submitted_total Total tasks submitted\n";
    oss << "# TYPE " << p << "_tasks_submitted_total counter\n";
    oss << p << "_tasks_submitted_total" << labels << " " << snapshot.tasks_submitted << "\n\n";
    oss << "# HELP " << p << "_tasks_executed_total Total tasks executed\n";
    oss << "# TYPE " << p << "_tasks_executed_total counter\n";
    oss << p << "_tasks_executed_total" << labels << " " << snapshot.tasks_executed << "\n\n";
    oss << "# HELP " << p << "_tasks_failed_total Total tasks failed\n";
    oss << "# TYPE " << p << "_tasks_failed_total counter\n";
    oss << p << "_tasks_failed_total" << labels << " " << snapshot.tasks_failed << "\n\n";
    // Time counters
    oss << "# HELP " << p << "_busy_time_nanoseconds_total Total busy time\n";
    oss << "# TYPE " << p << "_busy_time_nanoseconds_total counter\n";
    oss << p << "_busy_time_nanoseconds_total" << labels << " " << snapshot.total_busy_time_ns << "\n\n";
    oss << "# HELP " << p << "_idle_time_nanoseconds_total Total idle time\n";
    oss << "# TYPE " << p << "_idle_time_nanoseconds_total counter\n";
    oss << p << "_idle_time_nanoseconds_total" << labels << " " << snapshot.total_idle_time_ns << "\n";
    return oss.str();
}
References format_labels(), kcenon::thread::metrics::MetricsBackend::labels(), kcenon::thread::metrics::MetricsBackend::prefix_, kcenon::thread::metrics::BaseSnapshot::tasks_executed, kcenon::thread::metrics::BaseSnapshot::tasks_failed, kcenon::thread::metrics::BaseSnapshot::tasks_submitted, kcenon::thread::metrics::BaseSnapshot::total_busy_time_ns, and kcenon::thread::metrics::BaseSnapshot::total_idle_time_ns.
export_enhanced()
std::string kcenon::thread::metrics::PrometheusBackend::export_enhanced (const EnhancedSnapshot & snapshot) const nodiscard override virtual
Export enhanced metrics snapshot.
Parameters
snapshot The enhanced metrics snapshot to export.
Returns
Formatted string representation.
Implements kcenon::thread::metrics::MetricsBackend.
Definition at line 66 of file metrics_backend.cpp.
{
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(6);
    const auto& p = prefix_;
    const auto labels = format_labels();
    // Task counters
    oss << "# HELP " << p << "_tasks_submitted_total Total tasks submitted\n";
    oss << "# TYPE " << p << "_tasks_submitted_total counter\n";
    oss << p << "_tasks_submitted_total" << labels << " " << snapshot.tasks_submitted << "\n\n";
    oss << "# HELP " << p << "_tasks_executed_total Total tasks executed\n";
    oss << "# TYPE " << p << "_tasks_executed_total counter\n";
    oss << p << "_tasks_executed_total" << labels << " " << snapshot.tasks_executed << "\n\n";
    oss << "# HELP " << p << "_tasks_failed_total Total tasks failed\n";
    oss << "# TYPE " << p << "_tasks_failed_total counter\n";
    oss << p << "_tasks_failed_total" << labels << " " << snapshot.tasks_failed << "\n\n";
    // Latency summary (enqueue)
    oss << "# HELP " << p << "_enqueue_latency_us Enqueue latency in microseconds\n";
    oss << "# TYPE " << p << "_enqueue_latency_us summary\n";
    oss << p << "_enqueue_latency_us{quantile=\"0.5\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.enqueue_latency_p50_us << "\n";
    oss << p << "_enqueue_latency_us{quantile=\"0.9\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.enqueue_latency_p90_us << "\n";
    oss << p << "_enqueue_latency_us{quantile=\"0.99\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.enqueue_latency_p99_us << "\n\n";
    // Latency summary (execution)
    oss << "# HELP " << p << "_execution_latency_us Execution latency in microseconds\n";
    oss << "# TYPE " << p << "_execution_latency_us summary\n";
    oss << p << "_execution_latency_us{quantile=\"0.5\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.execution_latency_p50_us << "\n";
    oss << p << "_execution_latency_us{quantile=\"0.9\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.execution_latency_p90_us << "\n";
    oss << p << "_execution_latency_us{quantile=\"0.99\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.execution_latency_p99_us << "\n\n";
    // Latency summary (wait time)
    oss << "# HELP " << p << "_wait_time_us Queue wait time in microseconds\n";
    oss << "# TYPE " << p << "_wait_time_us summary\n";
    oss << p << "_wait_time_us{quantile=\"0.5\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.wait_time_p50_us << "\n";
    oss << p << "_wait_time_us{quantile=\"0.9\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.wait_time_p90_us << "\n";
    oss << p << "_wait_time_us{quantile=\"0.99\"" << (labels.empty() ? "" : "," + labels.substr(1, labels.size() - 2)) << "} " << snapshot.wait_time_p99_us << "\n\n";
    // Throughput
    oss << "# HELP " << p << "_throughput_1s Tasks per second (1s window)\n";
    oss << "# TYPE " << p << "_throughput_1s gauge\n";
    oss << p << "_throughput_1s" << labels << " " << snapshot.throughput_1s << "\n\n";
    oss << "# HELP " << p << "_throughput_1m Tasks per second (1m window)\n";
    oss << "# TYPE " << p << "_throughput_1m gauge\n";
    oss << p << "_throughput_1m" << labels << " " << snapshot.throughput_1m << "\n\n";
    // Queue depth
    oss << "# HELP " << p << "_queue_depth_current Current queue depth\n";
    oss << "# TYPE " << p << "_queue_depth_current gauge\n";
    oss << p << "_queue_depth_current" << labels << " " << snapshot.current_queue_depth << "\n\n";
    oss << "# HELP " << p << "_queue_depth_peak Peak queue depth\n";
    oss << "# TYPE " << p << "_queue_depth_peak gauge\n";
    oss << p << "_queue_depth_peak" << labels << " " << snapshot.peak_queue_depth << "\n\n";
    // Worker utilization
    oss << "# HELP " << p << "_worker_utilization Overall worker utilization\n";
    oss << "# TYPE " << p << "_worker_utilization gauge\n";
    oss << p << "_worker_utilization" << labels << " " << snapshot.worker_utilization << "\n\n";
    oss << "# HELP " << p << "_active_workers Number of active workers\n";
    oss << "# TYPE " << p << "_active_workers gauge\n";
    oss << p << "_active_workers" << labels << " " << snapshot.active_workers << "\n\n";
    // Per-worker utilization
    oss << "# HELP " << p << "_worker_utilization_per_worker Per-worker utilization\n";
    oss << "# TYPE " << p << "_worker_utilization_per_worker gauge\n";
    for (std::size_t i = 0; i < snapshot.per_worker_utilization.size(); ++i) {
        oss << p << "_worker_utilization_per_worker{worker=\"" << i << "\"";
        if (!labels_.empty()) {
            for (const auto& [key, value] : labels_) {
                oss << "," << key << "=\"" << value << "\"";
            }
        }
        oss << "} " << snapshot.per_worker_utilization[i] << "\n";
    }
    return oss.str();
}
References kcenon::thread::metrics::EnhancedSnapshot::active_workers, kcenon::thread::metrics::EnhancedSnapshot::current_queue_depth, kcenon::thread::metrics::EnhancedSnapshot::enqueue_latency_p50_us, kcenon::thread::metrics::EnhancedSnapshot::enqueue_latency_p90_us, kcenon::thread::metrics::EnhancedSnapshot::enqueue_latency_p99_us, kcenon::thread::metrics::EnhancedSnapshot::execution_latency_p50_us, kcenon::thread::metrics::EnhancedSnapshot::execution_latency_p90_us, kcenon::thread::metrics::EnhancedSnapshot::execution_latency_p99_us, format_labels(), kcenon::thread::metrics::MetricsBackend::labels(), kcenon::thread::metrics::MetricsBackend::labels_, kcenon::thread::metrics::EnhancedSnapshot::peak_queue_depth, kcenon::thread::metrics::EnhancedSnapshot::per_worker_utilization, kcenon::thread::metrics::MetricsBackend::prefix_, kcenon::thread::metrics::EnhancedSnapshot::tasks_executed, kcenon::thread::metrics::EnhancedSnapshot::tasks_failed, kcenon::thread::metrics::EnhancedSnapshot::tasks_submitted, kcenon::thread::metrics::EnhancedSnapshot::throughput_1m, kcenon::thread::metrics::EnhancedSnapshot::throughput_1s, kcenon::thread::metrics::EnhancedSnapshot::wait_time_p50_us, kcenon::thread::metrics::EnhancedSnapshot::wait_time_p90_us, kcenon::thread::metrics::EnhancedSnapshot::wait_time_p99_us, and kcenon::thread::metrics::EnhancedSnapshot::worker_utilization.
Referenced by kcenon::thread::metrics::EnhancedThreadPoolMetrics::to_prometheus().
format_labels()
std::string kcenon::thread::metrics::PrometheusBackend::format_labels () const nodiscard private
Format labels for Prometheus output.
Returns
Formatted label string (e.g., {key="value"}).
Definition at line 16 of file metrics_backend.cpp.
{
    if (labels_.empty()) {
        return "";
    }
    std::ostringstream oss;
    oss << "{";
    bool first = true;
    for (const auto& [key, value] : labels_) {
        if (!first) {
            oss << ",";
        }
        oss << key << "=\"" << value << "\"";
        first = false;
    }
    oss << "}";
    return oss.str();
}
References kcenon::thread::metrics::MetricsBackend::labels_.
Referenced by export_base(), and export_enhanced().
name()
std::string kcenon::thread::metrics::PrometheusBackend::name () const inline nodiscard override virtual
Get the backend name.
Returns
Human-readable backend identifier (e.g., "prometheus", "json").
Implements kcenon::thread::metrics::MetricsBackend.
Definition at line 161 of file metrics_backend.h.
{
        return "prometheus";
    }
The documentation for this class was generated from the following files:
include/kcenon/thread/metrics/metrics_backend.h
src/metrics/metrics_backend.cpp