Thread System: kcenon::thread::typed_thread_pool_t< job_type > Class Template Reference
kcenon::thread::typed_thread_pool_t< job_type > Class Template Reference
Thread Pools
Typed thread pool template.
#include <typed_thread_pool.h>
Public Member Functions
typed_thread_pool_t (const std::string &thread_title="typed_thread_pool", const thread_context &context=thread_context())
Constructs a new typed_thread_pool_t instance.
virtual ~typed_thread_pool_t (void)
Destroys the typed_thread_pool_t object.
auto get_ptr (void) -> std::shared_ptr< typed_thread_pool_t< job_type > >
Returns a shared pointer to the current typed_thread_pool_t.
auto start (void) -> common::VoidResult
Starts the thread pool by creating worker threads and initializing internal structures.
auto get_job_queue (void) -> std::shared_ptr< aging_typed_job_queue_t< job_type > >
Retrieves the underlying priority job queue managed by this thread pool.
auto execute (std::unique_ptr< job > &&work) -> common::VoidResult
auto shutdown () -> common::VoidResult
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&job) -> common::VoidResult
Enqueues a priority job into the thread pool's job queue.
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> common::VoidResult
Enqueues a batch of priority jobs into the thread pool's job queue.
auto enqueue (std::unique_ptr< typed_thread_worker_t< job_type > > &&worker) -> common::VoidResult
Enqueues a new worker thread for this thread pool.
auto enqueue_batch (std::vector< std::unique_ptr< typed_thread_worker_t< job_type > > > &&workers) -> common::VoidResult
Enqueues a batch of new worker threads for this thread pool.
auto stop (bool clear_queue=false) -> common::VoidResult
Stops the thread pool and optionally waits for currently running jobs to finish.
auto to_string (void) const -> std::string
Generates a string representation of the thread pool's internal state.
auto set_job_queue (std::shared_ptr< aging_typed_job_queue_t< job_type > > job_queue) -> void
Sets the job queue for this thread pool and its workers.
auto get_context (void) const -> const thread_context &
Gets the thread context for this pool.
auto enable_priority_aging (priority_aging_config config={}) -> void
Enables priority aging for this thread pool.
auto disable_priority_aging () -> void
Disables priority aging.
auto is_priority_aging_enabled () const -> bool
Checks if priority aging is enabled.
auto get_aging_stats () const -> aging_stats
Gets priority aging statistics.
auto enqueue (std::unique_ptr< aging_typed_job_t< job_type > > &&job) -> common::VoidResult
Enqueues an aging typed job.
Private Attributes
std::string thread_title_
A descriptive name or title for this thread pool, useful for logging.
std::atomic< bool > start_pool_
Indicates whether the thread pool has been started.
std::shared_ptr< aging_typed_job_queue_t< job_type > > job_queue_
The shared priority job queue from which workers fetch jobs.
std::vector< std::unique_ptr< typed_thread_worker_t< job_type > > > workers_
The collection of worker threads responsible for processing jobs.
thread_context context_
The thread context providing optional services.
bool priority_aging_enabled_ {false}
Flag indicating whether priority aging is enabled.
Detailed Description
template<typename job_type = job_types>
class kcenon::thread::typed_thread_pool_t< job_type >
Typed thread pool template.
A thread pool that schedules and executes jobs based on their priority levels.
Template Parameters
job_type The type representing job types (e.g., enum or integral type).
The typed_thread_pool_t template class provides a thread pool implementation that processes jobs according to their assigned types rather than just submission order. This allows more important work to be processed ahead of less important work, improving responsiveness for critical tasks.
Key Features
Type-Based Scheduling: Jobs with higher priority are processed first.
Customizable Type Types: Supports custom priority types through templates.
Worker Thread Model: Each worker runs in its own thread, processing jobs.
Type Job Queue: Thread-safe queue that orders jobs by priority.
Dynamic Thread Management: Add/remove workers at runtime.
Graceful Shutdown: Option to complete current jobs before stopping.
Use Cases
Mixed Workloads: Applications that process both critical and non-critical tasks.
Responsive User Interfaces: Prioritize UI-related tasks over background work.
Resource Management: Ensure important work gets resources when contention occurs.
Service Level Guarantees: Meet varying response time requirements for different request types.
Thread Safety
All public methods of this class are thread-safe and can be called from any thread.
Performance Considerations
Type queue operations are more expensive than simple FIFO queues.
In high-throughput scenarios with all equal-priority jobs, consider using the non-prioritized thread_pool instead for better performance.
For scenarios with mixed types, this implementation can significantly improve response time for high-priority tasks.
Example Usage
using my_thread_pool = typed_thread_pool_t<my_priority_enum>;
auto pool = std::make_shared<my_thread_pool>("My Thread Pool");
auto start_result = pool->start();
if (start_result.has_error())
{
    // Handle error starting the pool
    std::cerr << start_result.get_error().message() << std::endl;
}
// Enqueue a job
auto job = std::make_unique<typed_job_t<my_priority_enum>>(
    my_priority_enum::HIGH,
    [](){ std::cout << "RealTime priority job executed\n"; }
);
pool->enqueue(std::move(job));
// Stop the pool
pool->stop();
See also
typed_thread_worker_t The worker thread class used by the pool
typed_job_t Jobs with priority information
typed_job_queue_t The queue that orders jobs by priority
kcenon::thread::thread_pool The non-prioritized thread pool implementation
Examples
typed_thread_pool_sample_2.cpp.
Definition at line 140 of file typed_thread_pool.h.
Constructor & Destructor Documentation
typed_thread_pool_t()
template<typename job_type > kcenon::thread::typed_thread_pool_t< job_type >::typed_thread_pool_t (const std::string & thread_title = "typed_thread_pool", const thread_context & context = thread_context())
Constructs a new typed_thread_pool_t instance.
Parameters
thread_title A human-readable title or name for the thread pool. This can help in debugging or logging.
context Thread context providing optional logging and monitoring services
Definition at line 21 of file typed_thread_pool.cpp.
        : thread_title_(thread_title)
        , start_pool_(false)
        , job_queue_(std::make_shared<aging_typed_job_queue_t<job_type>>())
        , context_(context)
    {
    }
~typed_thread_pool_t()
template<typename job_type > kcenon::thread::typed_thread_pool_t< job_type >::~typed_thread_pool_t (void) virtual
Destroys the typed_thread_pool_t object.
The destructor will invoke stop() if the pool is still running, ensuring that all threads are properly terminated before destruction.
Definition at line 32 of file typed_thread_pool.cpp.
    {
        if (start_pool_.load())
        {
            stop(false); // Wait for jobs to complete
        }
    }
Member Function Documentation
disable_priority_aging()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::disable_priority_aging () -> void
Disables priority aging.
Stops the background aging thread if running.
Definition at line 278 of file typed_thread_pool.cpp.
    {
        if (!priority_aging_enabled_)
        {
            return;
        }
        if (job_queue_)
        {
            job_queue_->stop_aging();
        }
        priority_aging_enabled_ = false;
    }
enable_priority_aging()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enable_priority_aging (priority_aging_config config = {}) -> void
Enables priority aging for this thread pool.
Priority aging prevents starvation of low-priority jobs by automatically boosting their priority based on wait time.
Parameters
config The aging configuration.
Example
pool->enable_priority_aging({
    .enabled = true,
    .aging_interval = std::chrono::seconds{1},
    .max_priority_boost = 3
});
Definition at line 248 of file typed_thread_pool.cpp.
    {
        if (priority_aging_enabled_)
        {
            // Already enabled, just update config
            if (job_queue_)
            {
                job_queue_->set_aging_config(std::move(config));
            }
            return;
        }
        // Update the job queue config and start aging
        config.enabled = true;
        if (job_queue_)
        {
            job_queue_->set_aging_config(config);
            // Start aging if pool is running
            if (start_pool_.load())
            {
                job_queue_->start_aging();
            }
        }
        priority_aging_enabled_ = true;
    }
enqueue() [1/3]
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enqueue (std::unique_ptr< aging_typed_job_t< job_type > > && job) -> common::VoidResult
Enqueues an aging typed job.
Parameters
job The aging job to enqueue.
Returns
Result indicating success or failure.
Definition at line 311 of file typed_thread_pool.cpp.
    {
        if (!start_pool_.load(std::memory_order_acquire))
        {
            return common::error_info{
                static_cast<int>(error_code::thread_not_running),
                "Thread pool not started",
                "thread_system"
            };
        }
        if (!job)
        {
            return common::error_info{
                static_cast<int>(error_code::invalid_argument),
                "Null job",
                "thread_system"
            };
        }
        return job_queue_->enqueue(std::move(job));
    }
References kcenon::thread::invalid_argument, and kcenon::thread::thread_not_running.
enqueue() [2/3]
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && job) -> common::VoidResult
Enqueues a priority job into the thread pool's job queue.
Parameters
job A unique pointer to the priority job to be added.
Returns
common::VoidResult
Contains an error if the enqueue operation fails.
Otherwise, returns a success value.
Thread Safety
This method is thread-safe; multiple threads can safely enqueue jobs concurrently.
Definition at line 93 of file typed_thread_pool.cpp.
    {
        // Use acquire to ensure we see the latest pool state
        if (!start_pool_.load(std::memory_order_acquire))
        {
            return common::error_info{static_cast<int>(error_code::thread_not_running), "Thread pool not started", "thread_system"};
        }
        return job_queue_->enqueue(std::move(job));
    }
References kcenon::thread::thread_not_running.
enqueue() [3/3]
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enqueue (std::unique_ptr< typed_thread_worker_t< job_type > > && worker) -> common::VoidResult
Enqueues a new worker thread for this thread pool.
This allows dynamic addition of worker threads while the pool is running.
Parameters
worker A unique pointer to the priority thread worker to be added.
Returns
common::VoidResult
Contains an error if the enqueue operation fails.
Otherwise, returns a success value.
Note
Typically, most applications create a fixed number of workers at startup. However, if your workload changes significantly, adding more workers at runtime can help handle increased job load.
Thread Safety
This method is thread-safe.
Definition at line 119 of file typed_thread_pool.cpp.
    {
        if (!worker)
        {
            return common::error_info{static_cast<int>(error_code::invalid_argument), "Null worker", "thread_system"};
        }
        // Set the aging job queue for the worker
        worker->set_aging_job_queue(job_queue_);
        worker->set_context(context_);
        // Add worker first, then start if pool is running
        // This ensures stop() will see and stop this worker if called concurrently
        // Use acquire to synchronize with start_pool_ release in start()
        bool is_running = start_pool_.load(std::memory_order_acquire);
        workers_.push_back(std::move(worker));
        // Start the worker if the pool is already started
        if (is_running)
        {
            auto start_result = workers_.back()->start();
            if (start_result.is_err())
            {
                // Remove the worker we just added since it failed to start
                workers_.pop_back();
                return start_result;
            }
        }
        return common::ok();
    }
References kcenon::thread::invalid_argument.
enqueue_batch() [1/2]
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> common::VoidResult
Enqueues a batch of priority jobs into the thread pool's job queue.
Parameters
jobs A vector of unique pointers to priority jobs to be added.
Returns
common::VoidResult
Contains an error if the enqueue operation fails.
Otherwise, returns a success value.
Thread Safety
This method is thread-safe; multiple threads can safely enqueue jobs concurrently.
Definition at line 106 of file typed_thread_pool.cpp.
    {
        // Use acquire to ensure we see the latest pool state
        if (!start_pool_.load(std::memory_order_acquire))
        {
            return common::error_info{static_cast<int>(error_code::thread_not_running), "Thread pool not started", "thread_system"};
        }
        return job_queue_->enqueue_batch(std::move(jobs));
    }
References kcenon::thread::thread_not_running.
enqueue_batch() [2/2]
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_thread_worker_t< job_type > > > && workers) -> common::VoidResult
Enqueues a batch of new worker threads for this thread pool.
This allows dynamic addition of multiple worker threads while the pool is running.
Parameters
workers A vector of unique pointers to priority thread workers to be added.
Returns
common::VoidResult
Contains an error if the enqueue operation fails.
Otherwise, returns a success value.
Note
Typically, most applications create a fixed number of workers at startup. However, if your workload changes significantly, adding more workers at runtime can help handle increased job load.
Thread Safety
This method is thread-safe.
Definition at line 154 of file typed_thread_pool.cpp.
    {
        for (auto& worker : workers)
        {
            auto result = enqueue(std::move(worker));
            if (result.is_err())
            {
                return result;
            }
        }
        return common::ok();
    }
execute()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::execute (std::unique_ptr< job > && work) -> common::VoidResult
Definition at line 81 of file typed_thread_pool.cpp.
    {
        // Use acquire to ensure we see the latest pool state
        if (!start_pool_.load(std::memory_order_acquire))
        {
            return common::error_info{static_cast<int>(error_code::thread_not_running), "Thread pool not started", "thread_system"};
        }
        return job_queue_->enqueue(std::move(work));
    }
References kcenon::thread::thread_not_running.
get_aging_stats()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::get_aging_stats () const -> aging_stats nodiscard
Gets priority aging statistics.
Returns
The current aging statistics.
Definition at line 301 of file typed_thread_pool.cpp.
    {
        if (job_queue_)
        {
            return job_queue_->get_aging_stats();
        }
        return aging_stats{};
    }
get_context()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::get_context (void) const -> const thread_context& nodiscard
Gets the thread context for this pool.
Returns
const thread_context& Reference to the thread context
Definition at line 238 of file typed_thread_pool.cpp.
    {
        return context_;
    }
get_job_queue()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::get_job_queue (void) -> std::shared_ptr<aging_typed_job_queue_t<job_type>> nodiscard
Retrieves the underlying priority job queue managed by this thread pool.
Returns
std::shared_ptr<aging_typed_job_queue_t<job_type>> A shared pointer to the thread-safe priority job queue with aging support.
Thread Safety
This queue is shared and used by worker threads, so care should be taken if you modify or replace the queue. Typically, external code only needs to enqueue new jobs via enqueue(), rather than directly accessing the queue.
Definition at line 75 of file typed_thread_pool.cpp.
    {
        return job_queue_;
    }
get_ptr()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::get_ptr (void) -> std::shared_ptr<typed_thread_pool_t<job_type>> nodiscard
Returns a shared pointer to the current typed_thread_pool_t.
This is a convenience method when you only have a raw pointer to the pool but need a std::shared_ptr.
Returns
std::shared_ptr<typed_thread_pool_t<job_type>> A shared pointer to this thread pool.
Definition at line 41 of file typed_thread_pool.cpp.
    {
        return this->shared_from_this();
    }
is_priority_aging_enabled()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::is_priority_aging_enabled () const -> bool nodiscard
Checks if priority aging is enabled.
Returns
true if aging is enabled and running.
Definition at line 294 of file typed_thread_pool.cpp.
    {
        return priority_aging_enabled_ && job_queue_ &&
               job_queue_->is_aging_running();
    }
set_job_queue()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::set_job_queue (std::shared_ptr< aging_typed_job_queue_t< job_type > > job_queue) -> void
Sets the job queue for this thread pool and its workers.
Parameters
job_queue A shared pointer to the job queue to use.
Definition at line 222 of file typed_thread_pool.cpp.
    {
        job_queue_ = std::move(job_queue);
        // Update all workers with the new queue
        for (auto& worker : workers_)
        {
            if (worker)
            {
                worker->set_aging_job_queue(job_queue_);
            }
        }
    }
shutdown()
template<typename job_type = job_types> auto kcenon::thread::typed_thread_pool_t< job_type >::shutdown () -> common::VoidResult inline
Definition at line 207 of file typed_thread_pool.h.
{ return stop(false); }
References kcenon::thread::typed_thread_pool_t< job_type >::stop().
start()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::start (void) -> common::VoidResult
Starts the thread pool by creating worker threads and initializing internal structures.
Returns
common::VoidResult
If an error occurs during start-up, the returned result will contain an error object.
If no error occurs, the result will be a success value.
Thread Safety
This method is typically called once, before using other methods such as enqueue(). Calling start() multiple times without stopping is not recommended.
Definition at line 47 of file typed_thread_pool.cpp.
    {
        bool expected = false;
        if (!start_pool_.compare_exchange_strong(expected, true))
        {
            return common::error_info{static_cast<int>(error_code::thread_already_running), "Thread pool already started", "thread_system"};
        }
        // Check if there are workers to start
        if (workers_.empty())
        {
            start_pool_.store(false); // Reset state since we didn't actually start
            return common::error_info{static_cast<int>(error_code::invalid_argument), "no workers to start", "thread_system"};
        }
        // Start all workers
        for (auto& worker : workers_)
        {
            if (worker)
            {
                worker->start();
            }
        }
        return common::ok();
    }
References kcenon::thread::invalid_argument, and kcenon::thread::thread_already_running.
stop()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::stop (bool clear_queue = false) -> common::VoidResult
Stops the thread pool and optionally waits for currently running jobs to finish.
Parameters
clear_queue If true, any queued jobs are removed. If false (default), the pool stops accepting new jobs but allows currently running jobs to complete.
Returns
common::VoidResult
Contains an error if the stop operation fails.
Otherwise, returns a success value.
Thread Safety
Calling stop() from multiple threads simultaneously is safe, but redundant calls to stop() will have no additional effect after the first.
Definition at line 170 of file typed_thread_pool.cpp.
    {
        // Use compare_exchange_strong to atomically check and set state
        // This prevents race conditions during concurrent stop() calls
        bool expected = true;
        if (!start_pool_.compare_exchange_strong(expected, false,
                                                  std::memory_order_acq_rel,
                                                  std::memory_order_acquire))
        {
            return common::ok(); // Already stopped or being stopped by another thread
        }
        // Always stop the queue to prevent new jobs from being enqueued
        // This ensures consistent behavior with thread_pool and prevents
        // race conditions where jobs might be added after stop() is called
        if (job_queue_)
        {
            job_queue_->stop();
            // Optionally clear pending jobs for immediate shutdown
            if (clear_queue)
            {
                job_queue_->clear();
            }
        }
        // Stop all workers
        for (auto& worker : workers_)
        {
            if (worker)
            {
                worker->stop();
                // thread_base doesn't have join(), it manages threads internally
            }
        }
        return common::ok();
    }
Referenced by kcenon::thread::typed_thread_pool_t< job_type >::shutdown().
to_string()
template<typename job_type > auto kcenon::thread::typed_thread_pool_t< job_type >::to_string (void) const -> std::string nodiscard
Generates a string representation of the thread pool's internal state.
Returns
std::string A human-readable string containing pool details, such as whether the pool is running, the thread title, and potentially the number of workers.
Example
std::cout << pool.to_string() << std::endl;
// Output might look like:
// "typed_thread_pool [Title: typed_thread_pool, Started: true, Workers: 4]"
Definition at line 210 of file typed_thread_pool.cpp.
    {
        std::ostringstream oss;
        oss << "typed_thread_pool{"
            << "title: " << thread_title_
            << ", started: " << start_pool_.load()
            << ", workers: " << workers_.size()
            << "}";
        return oss.str();
    }
Referenced by std::formatter< kcenon::thread::typed_thread_pool_t< job_type > >::format(), and std::formatter< kcenon::thread::typed_thread_pool_t< job_type >, wchar_t >::format().
Member Data Documentation
context_
template<typename job_type = job_types> thread_context kcenon::thread::typed_thread_pool_t< job_type >::context_ private
The thread context providing optional services.
Definition at line 463 of file typed_thread_pool.h.
job_queue_
template<typename job_type = job_types> std::shared_ptr<aging_typed_job_queue_t<job_type> > kcenon::thread::typed_thread_pool_t< job_type >::job_queue_ private
The shared priority job queue from which workers fetch jobs.
Definition at line 457 of file typed_thread_pool.h.
priority_aging_enabled_
template<typename job_type = job_types> bool kcenon::thread::typed_thread_pool_t< job_type >::priority_aging_enabled_ {false} private
Flag indicating whether priority aging is enabled.
Definition at line 466 of file typed_thread_pool.h.
{false};
start_pool_
template<typename job_type = job_types> std::atomic<bool> kcenon::thread::typed_thread_pool_t< job_type >::start_pool_ private
Indicates whether the thread pool has been started.
Definition at line 454 of file typed_thread_pool.h.
thread_title_
template<typename job_type = job_types> std::string kcenon::thread::typed_thread_pool_t< job_type >::thread_title_ private
A descriptive name or title for this thread pool, useful for logging.
Definition at line 451 of file typed_thread_pool.h.
workers_
template<typename job_type = job_types> std::vector<std::unique_ptr<typed_thread_worker_t<job_type> > > kcenon::thread::typed_thread_pool_t< job_type >::workers_ private
The collection of worker threads responsible for processing jobs.
Definition at line 460 of file typed_thread_pool.h.
The documentation for this class was generated from the following files:
include/kcenon/thread/forward.h
include/kcenon/thread/impl/typed_pool/typed_thread_pool.h
src/impl/typed_pool/typed_thread_pool.cpp