# Codecov Configuration for thread_system
# https://docs.codecov.io/docs/codecov-yaml

# Coverage thresholds
coverage:
  status:
    project:
      default:
        # Enforce minimum 80% code coverage
        threshold: 1%
        target: 80%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        if_ci_failed: error

# Ignore files and directories
ignore:
  - "tests/**"
  - "unittest/**"
  - "benchmarks/**"
  - "examples/**"
  - "samples/**"
  - "integration_tests/**"
  - "docs/**"
  - "cmake/**"
  - "*.md"
  - "build/**"
  - "build_test/**"

# Comment configuration
comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Flags for different test types
flags:
  unit_tests:
    paths:
      - core/
      - utilities/
      - interfaces/
  integration_tests:
    paths:
      - core/
      - utilities/
