# Codecov Configuration for thread_system
# https://docs.codecov.io/docs/codecov-yaml

# Coverage thresholds
coverage:
  status:
    project:
      default:
        # Current coverage: ~52%, target set realistically with gradual improvement plan
        # Phase 1: 50% (current baseline)
        # Phase 2: 60% (after adding unit tests)
        # Phase 3: 70% (after integration test coverage)
        threshold: 2%
        target: 50%
        if_ci_failed: error
    patch:
      default:
        # New code should maintain reasonable coverage
        target: 60%
        if_ci_failed: error

# Ignore files and directories
ignore:
  - "tests/**"
  - "unittest/**"
  - "benchmarks/**"
  - "examples/**"
  - "samples/**"
  - "integration_tests/**"
  - "docs/**"
  - "cmake/**"
  - "*.md"
  - "build/**"
  - "build_test/**"
  - "src/modules/**"  # C++20 modules not compiled in standard CI builds

# Comment configuration
comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Flags for different test types
flags:
  unit_tests:
    paths:
      - core/
      - utilities/
      - interfaces/
  integration_tests:
    paths:
      - core/
      - utilities/
