var hierarchy =
[
    [ "kcenon::thread::adaptive_job_queue::accuracy_guard", "classkcenon_1_1thread_1_1adaptive__job__queue_1_1accuracy__guard.html", null ],
    [ "kcenon::thread::policies::adaptive_sync_policy", "classkcenon_1_1thread_1_1policies_1_1adaptive__sync__policy.html", null ],
    [ "kcenon::thread::aged_priority< P >", "structkcenon_1_1thread_1_1aged__priority.html", null ],
    [ "kcenon::thread::aged_priority< job_type >", "structkcenon_1_1thread_1_1aged__priority.html", null ],
    [ "kcenon::thread::aged_priority< job_types >", "structkcenon_1_1thread_1_1aged__priority.html", null ],
    [ "kcenon::thread::aging_stats", "structkcenon_1_1thread_1_1aging__stats.html", null ],
    [ "kcenon::thread::aging_typed_job_queue_t< job_type >", "classkcenon_1_1thread_1_1aging__typed__job__queue__t.html", null ],
    [ "kcenon::thread::aging_typed_job_queue_t< job_types >", "classkcenon_1_1thread_1_1aging__typed__job__queue__t.html", null ],
    [ "kcenon::thread::sync::atomic_flag_wrapper", "classkcenon_1_1thread_1_1sync_1_1atomic__flag__wrapper.html", null ],
    [ "kcenon::thread::atomic_shared_ptr< T >", "classkcenon_1_1thread_1_1atomic__shared__ptr.html", null ],
    [ "kcenon::thread::atomic_wait_helper< T >", "classkcenon_1_1thread_1_1atomic__wait__helper.html", null ],
    [ "kcenon::thread::atomic_with_wait< T >", "classkcenon_1_1thread_1_1atomic__with__wait.html", null ],
    [ "kcenon::thread::autoscaler", "classkcenon_1_1thread_1_1autoscaler.html", null ],
    [ "kcenon::thread::autoscaling_policy", "structkcenon_1_1thread_1_1autoscaling__policy.html", null ],
    [ "kcenon::thread::autoscaling_stats", "structkcenon_1_1thread_1_1autoscaling__stats.html", null ],
    [ "kcenon::thread::metrics::BackendRegistry", "classkcenon_1_1thread_1_1metrics_1_1BackendRegistry.html", null ],
    [ "kcenon::thread::backoff_calculator", "classkcenon_1_1thread_1_1backoff__calculator.html", null ],
    [ "kcenon::thread::backpressure_config", "structkcenon_1_1thread_1_1backpressure__config.html", null ],
    [ "kcenon::thread::backpressure_stats", "structkcenon_1_1thread_1_1backpressure__stats.html", null ],
    [ "kcenon::thread::backpressure_stats_snapshot", "structkcenon_1_1thread_1_1backpressure__stats__snapshot.html", null ],
    [ "kcenon::thread::barrier< CompletionFunction >", "classkcenon_1_1thread_1_1barrier.html", null ],
    [ "kcenon::thread::metrics::BaseSnapshot", "structkcenon_1_1thread_1_1metrics_1_1BaseSnapshot.html", null ],
    [ "std::bool_constant", null, [
      [ "kcenon::thread::concepts::is_future_like< T >", "structkcenon_1_1thread_1_1concepts_1_1is__future__like.html", null ],
      [ "kcenon::thread::concepts::is_nothrow_callable< F >", "structkcenon_1_1thread_1_1concepts_1_1is__nothrow__callable.html", null ]
    ] ],
    [ "kcenon::thread::diagnostics::bottleneck_report", "structkcenon_1_1thread_1_1diagnostics_1_1bottleneck__report.html", null ],
    [ "kcenon::thread::policies::bound_policy_tag", "structkcenon_1_1thread_1_1policies_1_1bound__policy__tag.html", null ],
    [ "kcenon::thread::policies::bounded_policy", "classkcenon_1_1thread_1_1policies_1_1bounded__policy.html", null ],
    [ "kcenon::thread::metrics::SlidingWindowCounter::Bucket", "structkcenon_1_1thread_1_1metrics_1_1SlidingWindowCounter_1_1Bucket.html", null ],
    [ "kcenon::thread::detail::callable_eraser", "classkcenon_1_1thread_1_1detail_1_1callable__eraser.html", null ],
    [ "kcenon::thread::concepts::callable_return_type< F, typename >", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type.html", null ],
    [ "kcenon::thread::concepts::callable_return_type< F, std::enable_if_t< std::is_invocable_v< F > > >", "structkcenon_1_1thread_1_1concepts_1_1callable__return__type_3_01F_00_01std_1_1enable__if__t_3_0934ffa248d47f139931de1a3e7ea01d0.html", null ],
    [ "kcenon::thread::crash_handler::callback_entry", "structkcenon_1_1thread_1_1crash__handler_1_1callback__entry.html", null ],
    [ "kcenon::thread::cancellable_future< R >", "classkcenon_1_1thread_1_1cancellable__future.html", null ],
    [ "kcenon::thread::cancellable_future< void >", "classkcenon_1_1thread_1_1cancellable__future_3_01void_01_4.html", null ],
    [ "kcenon::thread::cancellation_callback_guard", "classkcenon_1_1thread_1_1cancellation__callback__guard.html", null ],
    [ "kcenon::thread::cancellation_context", "classkcenon_1_1thread_1_1cancellation__context.html", null ],
    [ "kcenon::thread::cancellation_reason", "structkcenon_1_1thread_1_1cancellation__reason.html", null ],
    [ "kcenon::thread::cancellation_scope", "classkcenon_1_1thread_1_1cancellation__scope.html", null ],
    [ "kcenon::thread::cancellation_token", "classkcenon_1_1thread_1_1cancellation__token.html", null ],
    [ "kcenon::thread::lockfree::circular_array< T >", "classkcenon_1_1thread_1_1lockfree_1_1circular__array.html", null ],
    [ "kcenon::thread::lockfree::circular_array< kcenon::thread::job * >", "classkcenon_1_1thread_1_1lockfree_1_1circular__array.html", null ],
    [ "kcenon::thread::crash_handler::cleanup_entry", "structkcenon_1_1thread_1_1crash__handler_1_1cleanup__entry.html", null ],
    [ "kcenon::thread::adapters::common_executor_factory", "classkcenon_1_1thread_1_1adapters_1_1common__executor__factory.html", null ],
    [ "kcenon::thread::detail::compile_string< N >", "structkcenon_1_1thread_1_1detail_1_1compile__string.html", null ],
    [ "kcenon::thread::diagnostics::component_health", "structkcenon_1_1thread_1_1diagnostics_1_1component__health.html", null ],
    [ "kcenon::thread::detail::concurrent_queue< T >", "classkcenon_1_1thread_1_1detail_1_1concurrent__queue.html", null ],
    [ "kcenon::thread::sync::condition_variable_wrapper", "classkcenon_1_1thread_1_1sync_1_1condition__variable__wrapper.html", null ],
    [ "kcenon::thread::detail::conditional_feature< Condition >", "structkcenon_1_1thread_1_1detail_1_1conditional__feature.html", null ],
    [ "kcenon::thread::config_builder", "classkcenon_1_1thread_1_1config__builder.html", null ],
    [ "kcenon::thread::configuration_manager", "classkcenon_1_1thread_1_1configuration__manager.html", null ],
    [ "kcenon::thread::detail::constexpr_string< N >", "structkcenon_1_1thread_1_1detail_1_1constexpr__string.html", null ],
    [ "utility_module::convert_string", "classutility__module_1_1convert__string.html", null ],
    [ "kcenon::thread::crash_context", "structkcenon_1_1thread_1_1crash__context.html", null ],
    [ "kcenon::thread::crash_handler", "classkcenon_1_1thread_1_1crash__handler.html", null ],
    [ "kcenon::thread::crash_handler::crash_stats", "structkcenon_1_1thread_1_1crash__handler_1_1crash__stats.html", null ],
    [ "critical_resource", "classcritical__resource.html", null ],
    [ "kcenon::thread::dag_config", "structkcenon_1_1thread_1_1dag__config.html", null ],
    [ "kcenon::thread::dag_job_builder", "classkcenon_1_1thread_1_1dag__job__builder.html", null ],
    [ "kcenon::thread::dag_job_info", "structkcenon_1_1thread_1_1dag__job__info.html", null ],
    [ "kcenon::thread::dag_scheduler", "classkcenon_1_1thread_1_1dag__scheduler.html", null ],
    [ "kcenon::thread::dag_stats", "structkcenon_1_1thread_1_1dag__stats.html", null ],
    [ "demo_service", "structdemo__service.html", null ],
    [ "kcenon::thread::diagnostics::diagnostics_config", "structkcenon_1_1thread_1_1diagnostics_1_1diagnostics__config.html", null ],
    [ "kcenon::thread::policies::dynamic_bounded_policy", "classkcenon_1_1thread_1_1policies_1_1dynamic__bounded__policy.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "kcenon::thread::job_queue", "classkcenon_1_1thread_1_1job__queue.html", [
        [ "kcenon::thread::backpressure_job_queue", "classkcenon_1_1thread_1_1backpressure__job__queue.html", null ]
      ] ],
      [ "kcenon::thread::thread_pool", "classkcenon_1_1thread_1_1thread__pool.html", [
        [ "kcenon::thread::numa_thread_pool", "classkcenon_1_1thread_1_1numa__thread__pool.html", null ]
      ] ],
      [ "kcenon::thread::typed_thread_pool_t< job_type >", "classkcenon_1_1thread_1_1typed__thread__pool__t.html", null ]
    ] ],
    [ "kcenon::thread::enhanced_cancellation_token", "classkcenon_1_1thread_1_1enhanced__cancellation__token.html", null ],
    [ "kcenon::thread::enhanced_work_stealing_config", "structkcenon_1_1thread_1_1enhanced__work__stealing__config.html", null ],
    [ "kcenon::thread::metrics::EnhancedSnapshot", "structkcenon_1_1thread_1_1metrics_1_1EnhancedSnapshot.html", null ],
    [ "kcenon::thread::utils::enum_formatter< T, Converter >", "classkcenon_1_1thread_1_1utils_1_1enum__formatter.html", null ],
    [ "utility_module::enum_formatter< T, Converter >", "classutility__module_1_1enum__formatter.html", null ],
    [ "kcenon::thread::error", "classkcenon_1_1thread_1_1error.html", null ],
    [ "std::error_category", null, [
      [ "kcenon::thread::thread_error_category", "classkcenon_1_1thread_1_1thread__error__category.html", null ]
    ] ],
    [ "kcenon::thread::error_handler", "classkcenon_1_1thread_1_1error__handler.html", [
      [ "kcenon::thread::default_error_handler", "classkcenon_1_1thread_1_1default__error__handler.html", null ]
    ] ],
    [ "kcenon::thread::event_base", "classkcenon_1_1thread_1_1event__base.html", [
      [ "kcenon::thread::config_changed_event", "structkcenon_1_1thread_1_1config__changed__event.html", null ],
      [ "kcenon::thread::performance_alert_event", "structkcenon_1_1thread_1_1performance__alert__event.html", null ],
      [ "kcenon::thread::system_shutdown_event", "structkcenon_1_1thread_1_1system__shutdown__event.html", null ],
      [ "kcenon::thread::system_startup_event", "structkcenon_1_1thread_1_1system__startup__event.html", null ]
    ] ],
    [ "kcenon::thread::event_bus", "classkcenon_1_1thread_1_1event__bus.html", null ],
    [ "std::exception", null, [
      [ "kcenon::thread::operation_cancelled_exception", "classkcenon_1_1thread_1_1operation__cancelled__exception.html", null ]
    ] ],
    [ "kcenon::thread::diagnostics::execution_event_listener", "classkcenon_1_1thread_1_1diagnostics_1_1execution__event__listener.html", null ],
    [ "std::false_type", null, [
      [ "kcenon::thread::concepts::has_get_method< T, typename >", "structkcenon_1_1thread_1_1concepts_1_1has__get__method.html", null ],
      [ "kcenon::thread::concepts::has_wait_method< T, typename >", "structkcenon_1_1thread_1_1concepts_1_1has__wait__method.html", null ],
      [ "kcenon::thread::concepts::is_duration< T >", "structkcenon_1_1thread_1_1concepts_1_1is__duration.html", null ],
      [ "kcenon::thread::concepts::is_valid_job_type< T, typename >", "structkcenon_1_1thread_1_1concepts_1_1is__valid__job__type.html", null ],
      [ "kcenon::thread::detail::has_bound_policy_tag< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__tag.html", null ],
      [ "kcenon::thread::detail::has_bound_policy_type< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__type.html", null ],
      [ "kcenon::thread::detail::has_do_work_method< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__do__work__method.html", null ],
      [ "kcenon::thread::detail::has_get_method< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__get__method.html", null ],
      [ "kcenon::thread::detail::has_overflow_policy_tag< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__tag.html", null ],
      [ "kcenon::thread::detail::has_overflow_policy_type< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__type.html", null ],
      [ "kcenon::thread::detail::has_priority_method< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__priority__method.html", null ],
      [ "kcenon::thread::detail::has_sync_policy_tag< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__tag.html", null ],
      [ "kcenon::thread::detail::has_sync_policy_type< T, typename >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__type.html", null ],
      [ "kcenon::thread::detail::is_compatible_job< Job, ExpectedJobType >", "structkcenon_1_1thread_1_1detail_1_1is__compatible__job.html", null ],
      [ "kcenon::thread::detail::is_policy_queue_impl< T >", "structkcenon_1_1thread_1_1detail_1_1is__policy__queue__impl.html", null ],
      [ "kcenon::thread::has_blocking_overflow< T, typename >", "structkcenon_1_1thread_1_1has__blocking__overflow.html", null ],
      [ "kcenon::thread::is_bounded_queue< T, typename >", "structkcenon_1_1thread_1_1is__bounded__queue.html", null ],
      [ "kcenon::thread::is_lockfree_queue< T, typename >", "structkcenon_1_1thread_1_1is__lockfree__queue.html", null ]
    ] ],
    [ "kcenon::thread::utils::formatter", "classkcenon_1_1thread_1_1utils_1_1formatter.html", null ],
    [ "std::formatter", null, [
      [ "std::formatter< kcenon::thread::job_queue >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_01_4.html", null ],
      [ "std::formatter< kcenon::thread::job_queue, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__queue_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::job_types >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_01_4.html", null ],
      [ "std::formatter< kcenon::thread::job_types, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1job__types_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_conditions >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_conditions, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__conditions_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_pool >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_pool, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__pool_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_worker >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_01_4.html", null ],
      [ "std::formatter< kcenon::thread::thread_worker, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1thread__worker_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::typed_thread_pool_t< job_type > >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_01_4.html", null ],
      [ "std::formatter< kcenon::thread::typed_thread_pool_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__pool__t_3_01job__type_01_4_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< kcenon::thread::typed_thread_worker_t< job_type > >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_01_4.html", null ],
      [ "std::formatter< kcenon::thread::typed_thread_worker_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01kcenon_1_1thread_1_1typed__thread__worker__t_3_01job__type_01_4_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< test_priority >", "structstd_1_1formatter_3_01test__priority_01_4.html", null ],
      [ "std::formatter< test_priority, wchar_t >", "structstd_1_1formatter_3_01test__priority_00_01wchar__t_01_4.html", null ]
    ] ],
    [ "utility_module::formatter", "classutility__module_1_1formatter.html", null ],
    [ "kcenon::thread::detail::function_traits< F >", "structkcenon_1_1thread_1_1detail_1_1function__traits.html", null ],
    [ "kcenon::thread::detail::function_traits< R(*)(Args...) noexcept >", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "kcenon::thread::detail::function_traits< R(*)(Args...)>", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", null ],
    [ "kcenon::thread::detail::function_traits< R(C::*)(Args...) const >", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", null ],
    [ "kcenon::thread::detail::function_traits< R(C::*)(Args...)>", "structkcenon_1_1thread_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", null ],
    [ "kcenon::thread::detail::future_value_type< Future >", "structkcenon_1_1thread_1_1detail_1_1future__value__type.html", null ],
    [ "kcenon::thread::detail::global_reclamation_manager", "classkcenon_1_1thread_1_1detail_1_1global__reclamation__manager.html", null ],
    [ "kcenon::thread::cancellation_context::guard", "classkcenon_1_1thread_1_1cancellation__context_1_1guard.html", null ],
    [ "kcenon::thread::has_blocking_overflow< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1has__blocking__overflow_3_01T_00_01std_1_1enable__if__t_3_01policy__qu2578a9953134c095edab50d2ce8b7484.html", null ],
    [ "kcenon::thread::hazard_pointer", "classkcenon_1_1thread_1_1hazard__pointer.html", null ],
    [ "kcenon::thread::hazard_pointer_domain< T >", "classkcenon_1_1thread_1_1hazard__pointer__domain.html", null ],
    [ "kcenon::thread::detail::hazard_pointer_registry", "classkcenon_1_1thread_1_1detail_1_1hazard__pointer__registry.html", null ],
    [ "kcenon::thread::diagnostics::health_status", "structkcenon_1_1thread_1_1diagnostics_1_1health__status.html", null ],
    [ "kcenon::thread::diagnostics::health_thresholds", "structkcenon_1_1thread_1_1diagnostics_1_1health__thresholds.html", null ],
    [ "common::interfaces::IExecutor", null, [
      [ "kcenon::thread::adapters::thread_pool_executor_adapter", "classkcenon_1_1thread_1_1adapters_1_1thread__pool__executor__adapter.html", null ]
    ] ],
    [ "kcenon::common::interfaces::ILogger", null, [
      [ "console_logger", "classconsole__logger.html", null ],
      [ "mock_logger", "classmock__logger.html", null ]
    ] ],
    [ "kcenon::common::interfaces::IMonitor", null, [
      [ "console_monitoring", "classconsole__monitoring.html", null ],
      [ "mock_monitoring", "classmock__monitoring.html", null ],
      [ "sample_monitoring", "classsample__monitoring.html", null ]
    ] ],
    [ "kcenon::thread::is_bounded_queue< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1is__bounded__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue__6d81250e1ad6a165a566bf9432592958.html", null ],
    [ "kcenon::thread::detail::is_compatible_job< Job, ExpectedJobType >", "structkcenon_1_1thread_1_1detail_1_1is__compatible__job_3_01Job_00_01ExpectedJobType_01_4.html", null ],
    [ "kcenon::thread::is_lockfree_queue< T, std::enable_if_t< policy_queue_traits< T >::is_policy_queue > >", "structkcenon_1_1thread_1_1is__lockfree__queue_3_01T_00_01std_1_1enable__if__t_3_01policy__queue_0a64f444c12908d9268f79b4e4314f7a.html", null ],
    [ "std::is_same", null, [
      [ "kcenon::thread::detail::has_bound_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__tag_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1policy__tag_01_4_01_4.html", null ],
      [ "kcenon::thread::detail::has_overflow_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__tag_3_01T_00_01std_1_1void__t_3_01typ2b25af737181b619f5e96dad2dc19fc0.html", null ],
      [ "kcenon::thread::detail::has_sync_policy_tag< T, std::void_t< typename T::policy_tag > >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__tag_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1policy__tag_01_4_01_4.html", null ]
    ] ],
    [ "kcenon::thread::job", "classkcenon_1_1thread_1_1job.html", [
      [ "kcenon::thread::typed_job_t< job_types >", "classkcenon_1_1thread_1_1typed__job__t.html", [
        [ "kcenon::thread::aging_typed_job_t< job_types >", "classkcenon_1_1thread_1_1aging__typed__job__t.html", null ]
      ] ],
      [ "cancellable_long_job", "classcancellable__long__job.html", null ],
      [ "kcenon::thread::callback_job", "classkcenon_1_1thread_1_1callback__job.html", null ],
      [ "kcenon::thread::dag_job", "classkcenon_1_1thread_1_1dag__job.html", null ],
      [ "kcenon::thread::future_job< R >", "classkcenon_1_1thread_1_1future__job.html", null ],
      [ "kcenon::thread::job_builder::built_job", "classkcenon_1_1thread_1_1job__builder_1_1built__job.html", null ],
      [ "kcenon::thread::protected_job", "classkcenon_1_1thread_1_1protected__job.html", null ],
      [ "kcenon::thread::typed_job_t< job_type >", "classkcenon_1_1thread_1_1typed__job__t.html", [
        [ "kcenon::thread::aging_typed_job_t< job_type >", "classkcenon_1_1thread_1_1aging__typed__job__t.html", null ],
        [ "kcenon::thread::callback_typed_job_t< job_type >", "classkcenon_1_1thread_1_1callback__typed__job__t.html", null ]
      ] ],
      [ "non_cancellable_job", "classnon__cancellable__job.html", null ]
    ] ],
    [ "kcenon::thread::job_builder", "classkcenon_1_1thread_1_1job__builder.html", null ],
    [ "kcenon::thread::job_components", "structkcenon_1_1thread_1_1job__components.html", null ],
    [ "kcenon::thread::detail::job_eraser", "classkcenon_1_1thread_1_1detail_1_1job__eraser.html", null ],
    [ "kcenon::thread::diagnostics::job_execution_event", "structkcenon_1_1thread_1_1diagnostics_1_1job__execution__event.html", null ],
    [ "kcenon::thread::diagnostics::job_info", "structkcenon_1_1thread_1_1diagnostics_1_1job__info.html", null ],
    [ "kcenon::thread::job_info", "structkcenon_1_1thread_1_1job__info.html", null ],
    [ "kcenon::thread::jobs::job_interface", "classkcenon_1_1thread_1_1jobs_1_1job__interface.html", null ],
    [ "kcenon::thread::detail::job_type_extractor< Job >", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor.html", null ],
    [ "kcenon::thread::detail::job_type_extractor< T >", "structkcenon_1_1thread_1_1detail_1_1job__type__extractor_3_01T_01_4.html", null ],
    [ "kcenon::thread::detail::job_type_list< Types >", "structkcenon_1_1thread_1_1detail_1_1job__type__list.html", null ],
    [ "kcenon::thread::detail::job_type_traits< T, typename >", "structkcenon_1_1thread_1_1detail_1_1job__type__traits.html", null ],
    [ "kcenon::thread::detail::job_validator< Job, ExpectedType >", "structkcenon_1_1thread_1_1detail_1_1job__validator.html", null ],
    [ "kcenon::thread::latch", "classkcenon_1_1thread_1_1latch.html", null ],
    [ "kcenon::thread::metrics::LatencyHistogram", "classkcenon_1_1thread_1_1metrics_1_1LatencyHistogram.html", null ],
    [ "kcenon::thread::lifecycle_controller", "classkcenon_1_1thread_1_1lifecycle__controller.html", null ],
    [ "kcenon::thread::policies::lockfree_sync_policy", "classkcenon_1_1thread_1_1policies_1_1lockfree__sync__policy.html", null ],
    [ "LockFreeStack", "classLockFreeStack.html", null ],
    [ "kcenon::thread::job_queue::memory_stats", "structkcenon_1_1thread_1_1job__queue_1_1memory__stats.html", null ],
    [ "kcenon::thread::metrics::metrics_service", "classkcenon_1_1thread_1_1metrics_1_1metrics__service.html", null ],
    [ "kcenon::thread::metrics::MetricsBackend", "classkcenon_1_1thread_1_1metrics_1_1MetricsBackend.html", [
      [ "kcenon::thread::metrics::JsonBackend", "classkcenon_1_1thread_1_1metrics_1_1JsonBackend.html", null ],
      [ "kcenon::thread::metrics::LoggingBackend", "classkcenon_1_1thread_1_1metrics_1_1LoggingBackend.html", null ],
      [ "kcenon::thread::metrics::PrometheusBackend", "classkcenon_1_1thread_1_1metrics_1_1PrometheusBackend.html", null ]
    ] ],
    [ "kcenon::thread::metrics::MetricsBase", "classkcenon_1_1thread_1_1metrics_1_1MetricsBase.html", [
      [ "kcenon::thread::metrics::EnhancedThreadPoolMetrics", "classkcenon_1_1thread_1_1metrics_1_1EnhancedThreadPoolMetrics.html", null ],
      [ "kcenon::thread::metrics::ThreadPoolMetrics", "classkcenon_1_1thread_1_1metrics_1_1ThreadPoolMetrics.html", null ]
    ] ],
    [ "kcenon::thread::module_version", "structkcenon_1_1thread_1_1module__version.html", null ],
    [ "mock_monitoring::monitoring_stats", "structmock__monitoring_1_1monitoring__stats.html", null ],
    [ "kcenon::thread::policies::mutex_sync_policy", "classkcenon_1_1thread_1_1policies_1_1mutex__sync__policy.html", null ],
    [ "kcenon::thread::detail::concurrent_queue< T >::node", "structkcenon_1_1thread_1_1detail_1_1concurrent__queue_1_1node.html", null ],
    [ "kcenon::thread::detail::lockfree_job_queue::node", "structkcenon_1_1thread_1_1detail_1_1lockfree__job__queue_1_1node.html", null ],
    [ "kcenon::thread::policies::lockfree_sync_policy::node", "structkcenon_1_1thread_1_1policies_1_1lockfree__sync__policy_1_1node.html", null ],
    [ "kcenon::thread::detail::lockfree_job_queue::node_pool", "classkcenon_1_1thread_1_1detail_1_1lockfree__job__queue_1_1node__pool.html", null ],
    [ "kcenon::thread::numa_node", "structkcenon_1_1thread_1_1numa__node.html", null ],
    [ "kcenon::thread::numa_topology", "classkcenon_1_1thread_1_1numa__topology.html", null ],
    [ "kcenon::thread::numa_work_stealer", "classkcenon_1_1thread_1_1numa__work__stealer.html", null ],
    [ "kcenon::thread::policies::overflow_block_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__block__policy.html", null ],
    [ "kcenon::thread::policies::overflow_drop_newest_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__newest__policy.html", null ],
    [ "kcenon::thread::policies::overflow_drop_oldest_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__drop__oldest__policy.html", null ],
    [ "kcenon::thread::policies::overflow_policy_tag", "structkcenon_1_1thread_1_1policies_1_1overflow__policy__tag.html", null ],
    [ "kcenon::thread::policies::overflow_reject_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__reject__policy.html", null ],
    [ "kcenon::thread::policies::overflow_timeout_policy", "classkcenon_1_1thread_1_1policies_1_1overflow__timeout__policy.html", null ],
    [ "kcenon::thread::policy_queue_traits< T, typename >", "structkcenon_1_1thread_1_1policy__queue__traits.html", null ],
    [ "kcenon::thread::policy_queue_traits< T, std::enable_if_t< detail::has_sync_policy_type< T >::value &&detail::has_bound_policy_type< T >::value &&detail::has_overflow_policy_type< T >::value > >", "structkcenon_1_1thread_1_1policy__queue__traits_3_01T_00_01std_1_1enable__if__t_3_01detail_1_1haeec5129467d87996fbc20a79b22278eb.html", null ],
    [ "kcenon::thread::thread_system_config::pool_config", "structkcenon_1_1thread_1_1thread__system__config_1_1pool__config.html", null ],
    [ "kcenon::thread::pool_future< T >", "classkcenon_1_1thread_1_1pool__future.html", null ],
    [ "kcenon::thread::pool_policy", "classkcenon_1_1thread_1_1pool__policy.html", [
      [ "kcenon::thread::autoscaling_pool_policy", "classkcenon_1_1thread_1_1autoscaling__pool__policy.html", null ],
      [ "kcenon::thread::circuit_breaker_policy", "classkcenon_1_1thread_1_1circuit__breaker__policy.html", null ],
      [ "kcenon::thread::work_stealing_pool_policy", "classkcenon_1_1thread_1_1work__stealing__pool__policy.html", null ]
    ] ],
    [ "kcenon::thread::pool_promise< T >", "classkcenon_1_1thread_1_1pool__promise.html", null ],
    [ "kcenon::thread::pool_promise< void >", "classkcenon_1_1thread_1_1pool__promise_3_01void_01_4.html", null ],
    [ "kcenon::thread::pool_queue_adapter_interface", "classkcenon_1_1thread_1_1pool__queue__adapter__interface.html", [
      [ "kcenon::thread::job_queue_adapter", "classkcenon_1_1thread_1_1job__queue__adapter.html", null ],
      [ "kcenon::thread::policy_queue_adapter< SyncPolicy, BoundPolicy, OverflowPolicy >", "classkcenon_1_1thread_1_1policy__queue__adapter.html", null ]
    ] ],
    [ "kcenon::thread::priority_aging_config", "structkcenon_1_1thread_1_1priority__aging__config.html", null ],
    [ "kcenon::thread::detail::priority_comparator< T, Comparator >", "structkcenon_1_1thread_1_1detail_1_1priority__comparator.html", null ],
    [ "kcenon::thread::queue_capabilities", "structkcenon_1_1thread_1_1queue__capabilities.html", null ],
    [ "kcenon::thread::queue_capabilities_interface", "classkcenon_1_1thread_1_1queue__capabilities__interface.html", [
      [ "kcenon::thread::adaptive_job_queue", "classkcenon_1_1thread_1_1adaptive__job__queue.html", null ],
      [ "kcenon::thread::detail::lockfree_job_queue", "classkcenon_1_1thread_1_1detail_1_1lockfree__job__queue.html", null ],
      [ "kcenon::thread::job_queue", "classkcenon_1_1thread_1_1job__queue.html", null ],
      [ "kcenon::thread::policy_queue< SyncPolicy, BoundPolicy, OverflowPolicy >", "classkcenon_1_1thread_1_1policy__queue.html", null ]
    ] ],
    [ "kcenon::thread::queue_factory", "classkcenon_1_1thread_1_1queue__factory.html", null ],
    [ "kcenon::thread::queue_type_selector< NeedExactSize, PreferLockFree >", "structkcenon_1_1thread_1_1queue__type__selector.html", null ],
    [ "kcenon::thread::queue_factory::requirements", "structkcenon_1_1thread_1_1queue__factory_1_1requirements.html", null ],
    [ "kcenon::thread::thread_system_config::resilience_config", "structkcenon_1_1thread_1_1thread__system__config_1_1resilience__config.html", null ],
    [ "kcenon::thread::result< T >", "classkcenon_1_1thread_1_1result.html", null ],
    [ "kcenon::thread::result< void >", "classkcenon_1_1thread_1_1result_3_01void_01_4.html", null ],
    [ "kcenon::thread::result_void", "classkcenon_1_1thread_1_1result__void.html", null ],
    [ "kcenon::thread::detail::retire_node", "structkcenon_1_1thread_1_1detail_1_1retire__node.html", null ],
    [ "kcenon::thread::retry_policy", "classkcenon_1_1thread_1_1retry__policy.html", null ],
    [ "kcenon::thread::safe_hazard_guard", "classkcenon_1_1thread_1_1safe__hazard__guard.html", null ],
    [ "kcenon::thread::safe_hazard_pointer_domain", "classkcenon_1_1thread_1_1safe__hazard__pointer__domain.html", null ],
    [ "kcenon::thread::safe_hazard_pointer_record", "classkcenon_1_1thread_1_1safe__hazard__pointer__record.html", null ],
    [ "kcenon::thread::autoscaling_policy::scale_down_config", "structkcenon_1_1thread_1_1autoscaling__policy_1_1scale__down__config.html", null ],
    [ "kcenon::thread::autoscaling_policy::scale_up_config", "structkcenon_1_1thread_1_1autoscaling__policy_1_1scale__up__config.html", null ],
    [ "kcenon::thread::thread_system_config::scaling_config", "structkcenon_1_1thread_1_1thread__system__config_1_1scaling__config.html", null ],
    [ "kcenon::thread::scaling_decision", "structkcenon_1_1thread_1_1scaling__decision.html", null ],
    [ "kcenon::thread::scaling_metrics_sample", "structkcenon_1_1thread_1_1scaling__metrics__sample.html", null ],
    [ "kcenon::thread::scheduler_interface", "classkcenon_1_1thread_1_1scheduler__interface.html", [
      [ "kcenon::thread::adaptive_job_queue", "classkcenon_1_1thread_1_1adaptive__job__queue.html", null ],
      [ "kcenon::thread::detail::lockfree_job_queue", "classkcenon_1_1thread_1_1detail_1_1lockfree__job__queue.html", null ],
      [ "kcenon::thread::job_queue", "classkcenon_1_1thread_1_1job__queue.html", null ],
      [ "kcenon::thread::policy_queue< SyncPolicy, BoundPolicy, OverflowPolicy >", "classkcenon_1_1thread_1_1policy__queue.html", null ]
    ] ],
    [ "kcenon::thread::scoped_crash_callback", "classkcenon_1_1thread_1_1scoped__crash__callback.html", null ],
    [ "kcenon::thread::sync::scoped_lock_guard< Mutex >", "classkcenon_1_1thread_1_1sync_1_1scoped__lock__guard.html", null ],
    [ "kcenon::thread::scoped_service< Interface >", "classkcenon_1_1thread_1_1scoped__service.html", null ],
    [ "kcenon::thread::service_container", "classkcenon_1_1thread_1_1service__container.html", null ],
    [ "kcenon::thread::service_container::service_entry", "structkcenon_1_1thread_1_1service__container_1_1service__entry.html", null ],
    [ "kcenon::thread::service_registry", "classkcenon_1_1thread_1_1service__registry.html", null ],
    [ "kcenon::thread::sync::shared_mutex_wrapper", "classkcenon_1_1thread_1_1sync_1_1shared__mutex__wrapper.html", null ],
    [ "kcenon::thread::metrics::SlidingWindowCounter", "classkcenon_1_1thread_1_1metrics_1_1SlidingWindowCounter.html", null ],
    [ "SmartJobProcessor", "classSmartJobProcessor.html", null ],
    [ "kcenon::thread::metrics::ThreadPoolMetrics::Snapshot", "structkcenon_1_1thread_1_1metrics_1_1ThreadPoolMetrics_1_1Snapshot.html", null ],
    [ "utility_module::span< T, Extent >", "classutility__module_1_1span.html", null ],
    [ "kcenon::thread::enhanced_cancellation_token::state", "structkcenon_1_1thread_1_1enhanced__cancellation__token_1_1state.html", null ],
    [ "kcenon::thread::adaptive_job_queue::stats", "structkcenon_1_1thread_1_1adaptive__job__queue_1_1stats.html", null ],
    [ "kcenon::thread::hazard_pointer_domain< T >::stats", "structkcenon_1_1thread_1_1hazard__pointer__domain_1_1stats.html", null ],
    [ "kcenon::thread::steal_backoff_config", "structkcenon_1_1thread_1_1steal__backoff__config.html", null ],
    [ "kcenon::thread::submit_options", "structkcenon_1_1thread_1_1submit__options.html", null ],
    [ "kcenon::thread::event_bus::subscription", "classkcenon_1_1thread_1_1event__bus_1_1subscription.html", null ],
    [ "kcenon::thread::policies::sync_policy_tag", "structkcenon_1_1thread_1_1policies_1_1sync__policy__tag.html", null ],
    [ "kcenon::thread::platform::system_info", "structkcenon_1_1thread_1_1platform_1_1system__info.html", null ],
    [ "TestData", "structTestData.html", null ],
    [ "TestNode", "structTestNode.html", null ],
    [ "kcenon::thread::thread_base", "classkcenon_1_1thread_1_1thread__base.html", [
      [ "kcenon::thread::typed_thread_worker_t< job_types >", "classkcenon_1_1thread_1_1typed__thread__worker__t.html", null ],
      [ "kcenon::thread::thread_worker", "classkcenon_1_1thread_1_1thread__worker.html", null ],
      [ "kcenon::thread::typed_thread_worker_t< job_type >", "classkcenon_1_1thread_1_1typed__thread__worker__t.html", null ]
    ] ],
    [ "kcenon::thread::thread_context", "classkcenon_1_1thread_1_1thread__context.html", null ],
    [ "kcenon::thread::thread_context_builder", "classkcenon_1_1thread_1_1thread__context__builder.html", null ],
    [ "kcenon::thread::detail::thread_hazard_list", "structkcenon_1_1thread_1_1detail_1_1thread__hazard__list.html", null ],
    [ "kcenon::thread::detail::thread_impl", "classkcenon_1_1thread_1_1detail_1_1thread__impl.html", null ],
    [ "kcenon::thread::diagnostics::thread_info", "structkcenon_1_1thread_1_1diagnostics_1_1thread__info.html", null ],
    [ "kcenon::thread::thread_logger", "classkcenon_1_1thread_1_1thread__logger.html", null ],
    [ "kcenon::thread::thread_pool_builder", "classkcenon_1_1thread_1_1thread__pool__builder.html", null ],
    [ "kcenon::thread::thread_pool_crash_safety", "classkcenon_1_1thread_1_1thread__pool__crash__safety.html", null ],
    [ "kcenon::thread::diagnostics::thread_pool_diagnostics", "classkcenon_1_1thread_1_1diagnostics_1_1thread__pool__diagnostics.html", null ],
    [ "kcenon::thread::hazard_pointer_domain< T >::thread_retire_list", "structkcenon_1_1thread_1_1hazard__pointer__domain_1_1thread__retire__list.html", null ],
    [ "kcenon::thread::thread_system_config", "structkcenon_1_1thread_1_1thread__system__config.html", null ],
    [ "kcenon::thread::token_bucket", "classkcenon_1_1thread_1_1token__bucket.html", null ],
    [ "kcenon::thread::cancellation_token::token_state", "structkcenon_1_1thread_1_1cancellation__token_1_1token__state.html", null ],
    [ "std::true_type", null, [
      [ "kcenon::thread::concepts::has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "structkcenon_1_1thread_1_1concepts_1_1has__get__method_3_01T_00_01std_1_1void__t_3_01decltype_07d869b6cf96acafc0ea1f11f421689910.html", null ],
      [ "kcenon::thread::concepts::has_wait_method< T, std::void_t< decltype(std::declval< T >().wait())> >", "structkcenon_1_1thread_1_1concepts_1_1has__wait__method_3_01T_00_01std_1_1void__t_3_01decltype_05d3c12d9bfc583e0c6389f2921b80175.html", null ],
      [ "kcenon::thread::concepts::is_duration< std::chrono::duration< Rep, Period > >", "structkcenon_1_1thread_1_1concepts_1_1is__duration_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_01_4.html", null ],
      [ "kcenon::thread::concepts::is_valid_job_type< T, std::enable_if_t< JobType< T > > >", "structkcenon_1_1thread_1_1concepts_1_1is__valid__job__type_3_01T_00_01std_1_1enable__if__t_3_01JobType_3_01T_01_4_01_4_01_4.html", null ],
      [ "kcenon::thread::detail::has_bound_policy_type< T, std::void_t< typename T::bound_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__bound__policy__type_3_01T_00_01std_1_1void__t_3_01typen855d4214eb0f318dab7d3b857389f8a0.html", null ],
      [ "kcenon::thread::detail::has_do_work_method< T, std::void_t< decltype(std::declval< T >().do_work())> >", "structkcenon_1_1thread_1_1detail_1_1has__do__work__method_3_01T_00_01std_1_1void__t_3_01decltype279da4895ca19f645443738873665ae7.html", null ],
      [ "kcenon::thread::detail::has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "structkcenon_1_1thread_1_1detail_1_1has__get__method_3_01T_00_01std_1_1void__t_3_01decltype_07st2973351f2472797fc8429b46ac63ffb8.html", null ],
      [ "kcenon::thread::detail::has_overflow_policy_type< T, std::void_t< typename T::overflow_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__overflow__policy__type_3_01T_00_01std_1_1void__t_3_01tyd833da87b23127ba287c43a16167794f.html", null ],
      [ "kcenon::thread::detail::has_priority_method< T, std::void_t< decltype(std::declval< T >().priority())> >", "structkcenon_1_1thread_1_1detail_1_1has__priority__method_3_01T_00_01std_1_1void__t_3_01decltype1259939ce1df6e30ea7bdfeb245c14ca.html", null ],
      [ "kcenon::thread::detail::has_sync_policy_type< T, std::void_t< typename T::sync_policy_type > >", "structkcenon_1_1thread_1_1detail_1_1has__sync__policy__type_3_01T_00_01std_1_1void__t_3_01typena93cedef5780fa3e844c7d4b967dd5a13.html", null ],
      [ "kcenon::thread::detail::is_policy_queue_impl< policy_queue< SyncPolicy, BoundPolicy, OverflowPolicy > >", "structkcenon_1_1thread_1_1detail_1_1is__policy__queue__impl_3_01policy__queue_3_01SyncPolicy_00_e091157b5e63405d7e768a64a3750f7f.html", null ],
      [ "std::is_error_code_enum< kcenon::thread::error_code >", "structstd_1_1is__error__code__enum_3_01kcenon_1_1thread_1_1error__code_01_4.html", null ]
    ] ],
    [ "kcenon::thread::typed_job_factory_interface< job_type >", "classkcenon_1_1thread_1_1typed__job__factory__interface.html", null ],
    [ "kcenon::thread::typed_job_interface< job_type >", "classkcenon_1_1thread_1_1typed__job__interface.html", null ],
    [ "kcenon::thread::typed_safe_hazard_domain< T >", "classkcenon_1_1thread_1_1typed__safe__hazard__domain.html", null ],
    [ "kcenon::thread::typed_thread_pool_builder< job_type >", "classkcenon_1_1thread_1_1typed__thread__pool__builder.html", null ],
    [ "kcenon::thread::policies::unbounded_policy", "classkcenon_1_1thread_1_1policies_1_1unbounded__policy.html", null ],
    [ "kcenon::thread::detail::validate_thread_count< ThreadCount >", "structkcenon_1_1thread_1_1detail_1_1validate__thread__count.html", null ],
    [ "kcenon::thread::validation_result", "structkcenon_1_1thread_1_1validation__result.html", null ],
    [ "kcenon::thread::detail::callable_eraser::vtable_t", "structkcenon_1_1thread_1_1detail_1_1callable__eraser_1_1vtable__t.html", null ],
    [ "kcenon::thread::detail::job_eraser::vtable_t", "structkcenon_1_1thread_1_1detail_1_1job__eraser_1_1vtable__t.html", null ],
    [ "kcenon::thread::work_affinity_tracker", "classkcenon_1_1thread_1_1work__affinity__tracker.html", null ],
    [ "kcenon::thread::lockfree::work_stealing_deque< T >", "classkcenon_1_1thread_1_1lockfree_1_1work__stealing__deque.html", null ],
    [ "kcenon::thread::lockfree::work_stealing_deque< kcenon::thread::job * >", "classkcenon_1_1thread_1_1lockfree_1_1work__stealing__deque.html", null ],
    [ "kcenon::thread::work_stealing_stats", "structkcenon_1_1thread_1_1work__stealing__stats.html", null ],
    [ "kcenon::thread::work_stealing_stats_snapshot", "structkcenon_1_1thread_1_1work__stealing__stats__snapshot.html", null ],
    [ "kcenon::thread::worker_policy", "structkcenon_1_1thread_1_1worker__policy.html", null ],
    [ "kcenon::thread::metrics::WorkerMetrics", "structkcenon_1_1thread_1_1metrics_1_1WorkerMetrics.html", null ]
];