Thread System: kcenon::thread::diagnostics Namespace Reference
kcenon::thread::diagnostics Namespace Reference
Classes
struct bottleneck_report
Analysis report of bottlenecks in the thread pool.
struct component_health
Health status of a single component.
struct diagnostics_config
Configuration options for thread pool diagnostics.
class execution_event_listener
Interface for receiving job execution events.
struct health_status
Comprehensive health status of the thread pool.
struct health_thresholds
Configurable thresholds for health status determination.
struct job_execution_event
Event data for job execution tracing.
struct job_info
Information about a job in the thread pool.
struct thread_info
Information about a worker thread in the pool.
class thread_pool_diagnostics
Comprehensive diagnostics API for thread pool monitoring.
Enumerations
enum class bottleneck_type {
bottleneck_type::none , bottleneck_type::queue_full , bottleneck_type::slow_consumer , bottleneck_type::worker_starvation ,
bottleneck_type::lock_contention , bottleneck_type::uneven_distribution , bottleneck_type::memory_pressure
}
Type of bottleneck detected in the thread pool.
enum class event_type {
event_type::enqueued , event_type::dequeued , event_type::started , event_type::completed ,
event_type::failed , event_type::cancelled , event_type::retried
}
Type of job execution event.
enum class health_state { health_state::healthy , health_state::degraded , health_state::unhealthy , health_state::unknown }
Overall health state of a component or system.
enum class job_status {
job_status::pending , job_status::running , job_status::completed , job_status::failed ,
job_status::cancelled , job_status::timed_out
}
Status of a job in the thread pool.
enum class worker_state { worker_state::idle , worker_state::active , worker_state::stopping , worker_state::stopped }
Current state of a worker thread.
Functions
auto bottleneck_type_to_string (bottleneck_type type) -> std::string
Converts bottleneck_type to human-readable string.
auto event_type_to_string (event_type type) -> std::string
Converts event_type to human-readable string.
auto health_state_to_string (health_state state) -> std::string
Converts health_state to human-readable string.
auto health_state_to_http_code (health_state state) -> int
Gets HTTP status code for health state.
auto job_status_to_string (job_status status) -> std::string
Converts job_status to human-readable string.
auto worker_state_to_string (worker_state state) -> std::string
Converts worker_state to human-readable string.
Function Documentation
bottleneck_type_to_string()
auto kcenon::thread::diagnostics::bottleneck_type_to_string (bottleneck_type type) -> std::string inline nodiscard
Converts bottleneck_type to human-readable string.
Parameters
type The bottleneck type to convert.
Returns
String representation of the bottleneck type.
Definition at line 47 of file bottleneck_report.h.
    {
        switch (type)
        {
            case bottleneck_type::none: return "none";
            case bottleneck_type::queue_full: return "queue_full";
            case bottleneck_type::slow_consumer: return "slow_consumer";
            case bottleneck_type::worker_starvation: return "worker_starvation";
            case bottleneck_type::lock_contention: return "lock_contention";
            case bottleneck_type::uneven_distribution: return "uneven_distribution";
            case bottleneck_type::memory_pressure: return "memory_pressure";
            default: return "unknown";
        }
    }
References lock_contention, memory_pressure, none, queue_full, slow_consumer, uneven_distribution, and worker_starvation.
Referenced by kcenon::thread::diagnostics::bottleneck_report::to_json(), kcenon::thread::diagnostics::thread_pool_diagnostics::to_json(), and kcenon::thread::diagnostics::bottleneck_report::to_string().
event_type_to_string()
auto kcenon::thread::diagnostics::event_type_to_string (event_type type) -> std::string inline nodiscard
Converts event_type to human-readable string.
Parameters
type The event type to convert.
Returns
String representation of the event type.
Definition at line 51 of file execution_event.h.
    {
        switch (type)
        {
            case event_type::enqueued: return "enqueued";
            case event_type::dequeued: return "dequeued";
            case event_type::started: return "started";
            case event_type::completed: return "completed";
            case event_type::failed: return "failed";
            case event_type::cancelled: return "cancelled";
            case event_type::retried: return "retried";
            default: return "unknown";
        }
    }
References cancelled, completed, dequeued, enqueued, failed, retried, and started.
Referenced by kcenon::thread::diagnostics::job_execution_event::to_json(), and kcenon::thread::diagnostics::job_execution_event::to_string().
health_state_to_http_code()
auto kcenon::thread::diagnostics::health_state_to_http_code (health_state state) -> int inline nodiscard
Gets HTTP status code for health state.
Useful for implementing health check HTTP endpoints.
Parameters
state The health state.
Returns
HTTP status code (200, 503, etc.).
Definition at line 122 of file health_status.h.
    {
        switch (state)
        {
            case health_state::healthy: return 200;
            case health_state::degraded: return 200;  // Still operational
            case health_state::unhealthy: return 503;
            case health_state::unknown: return 503;
            default: return 503;
        }
    }
References degraded, healthy, unhealthy, and unknown.
Referenced by kcenon::thread::diagnostics::health_status::http_status_code().
health_state_to_string()
auto kcenon::thread::diagnostics::health_state_to_string (health_state state) -> std::string inline nodiscard
Converts health_state to human-readable string.
Parameters
state The state to convert.
Returns
String representation of the health state.
Definition at line 103 of file health_status.h.
    {
        switch (state)
        {
            case health_state::healthy: return "healthy";
            case health_state::degraded: return "degraded";
            case health_state::unhealthy: return "unhealthy";
            case health_state::unknown: return "unknown";
            default: return "unknown";
        }
    }
References degraded, healthy, unhealthy, and unknown.
Referenced by kcenon::thread::diagnostics::health_status::to_json(), kcenon::thread::diagnostics::thread_pool_diagnostics::to_json(), and kcenon::thread::diagnostics::health_status::to_string().
job_status_to_string()
auto kcenon::thread::diagnostics::job_status_to_string (job_status status) -> std::string inline nodiscard
Converts job_status to human-readable string.
Parameters
status The status to convert.
Returns
String representation of the status.
Definition at line 47 of file job_info.h.
    {
        switch (status)
        {
            case job_status::pending: return "pending";
            case job_status::running: return "running";
            case job_status::completed: return "completed";
            case job_status::failed: return "failed";
            case job_status::cancelled: return "cancelled";
            case job_status::timed_out: return "timed_out";
            default: return "unknown";
        }
    }
References cancelled, completed, failed, pending, running, and timed_out.
Referenced by kcenon::thread::diagnostics::job_info::to_json(), and kcenon::thread::diagnostics::job_info::to_string().
worker_state_to_string()
auto kcenon::thread::diagnostics::worker_state_to_string (worker_state state) -> std::string inline nodiscard
Converts worker_state to human-readable string.
Parameters
state The state to convert.
Returns
String representation of the state.
Definition at line 47 of file thread_info.h.
    {
        switch (state)
        {
            case worker_state::idle: return "IDLE";
            case worker_state::active: return "ACTIVE";
            case worker_state::stopping: return "STOPPING";
            case worker_state::stopped: return "STOPPED";
            default: return "UNKNOWN";
        }
    }
References active, idle, stopped, and stopping.
Referenced by kcenon::thread::diagnostics::thread_pool_diagnostics::format_thread_dump(), kcenon::thread::diagnostics::thread_info::to_json(), and kcenon::thread::diagnostics::thread_info::to_string().