Thread System: kcenon::thread::utils Namespace Reference
kcenon::thread::utils Namespace Reference
Classes
class enum_formatter
A generic formatter for enum types, using a user-provided converter functor.
class formatter
Provides convenience methods for string formatting using C++20 <format>.
Typedefs
using formatter = kcenon::thread::utils::formatter
template<typename T , typename Converter >
using enum_formatter = kcenon::thread::utils::enum_formatter<T, Converter>
Functions
template<class T , size_t N>
span (T(&)[N]) -> span< T, N >
template<class T , size_t N>
span (std::array< T, N > &) -> span< T, N >
template<class T , size_t N>
span (const std::array< T, N > &) -> span< const T, N >
template<class Container >
span (Container &) -> span< typename Container::value_type >
template<class Container >
span (const Container &) -> span< const typename Container::value_type >
Typedef Documentation
enum_formatter
template<typename T , typename Converter > using kcenon::thread::utils::enum_formatter = kcenon::thread::utils::enum_formatter<T, Converter>
Definition at line 191 of file formatter.h.
formatter
using kcenon::thread::utils::formatter = kcenon::thread::utils::formatter
Definition at line 189 of file formatter.h.
Function Documentation
span() [1/5]
template<class Container > kcenon::thread::utils::span (const Container &) -> span< const typename Container::value_type >
References span().
span() [2/5]
template<class T , size_t N> kcenon::thread::utils::span (const std::array< T, N > &) -> span< const T, N >
References span().
span() [3/5]
template<class Container > kcenon::thread::utils::span (Container &) -> span< typename Container::value_type >
References span().
span() [4/5]
template<class T , size_t N> kcenon::thread::utils::span (std::array< T, N > &) -> span< T, N >
References span().
span() [5/5]
template<class T , size_t N> kcenon::thread::utils::span (T(&) [N]) -> span< T, N >
References span().
Referenced by utility_module::span< T, Extent >::first(), utility_module::span< T, Extent >::first(), utility_module::span< T, Extent >::last(), utility_module::span< T, Extent >::last(), span(), span(), span(), span(), span(), utility_module::span< T, Extent >::subspan(), and utility_module::span< T, Extent >::subspan().