Thread System: kcenon::thread::platform Namespace Reference
kcenon::thread::platform Namespace Reference
Classes
struct system_info
System information structure.
Enumerations
enum class cpu_architecture { x86 , x86_64 , arm64 , unknown }
CPU architecture enumeration.
enum class os_type { windows , macos , linux_os , unknown }
Operating system enumeration.
Functions
cpu_architecture get_architecture () noexcept
Get current CPU architecture.
os_type get_os () noexcept
Get current operating system.
bool is_arm64 () noexcept
Check if running on ARM64 architecture.
uint32_t get_physical_core_count () noexcept
Get physical core count.
uint32_t get_logical_core_count () noexcept
Get logical core count.
bool is_container_environment () noexcept
Check if running in container environment.
bool has_efficiency_cores () noexcept
Check if system has efficiency cores (Apple Silicon)
system_info get_system_info () noexcept
Get comprehensive system information.
const char * get_platform_name () noexcept
Get platform name string.
const char * get_arch_name () noexcept
Get architecture name string.
Enumeration Type Documentation
cpu_architecture
enum class kcenon::thread::platform::cpu_architecture strong
CPU architecture enumeration.
Enumerator
x86
x86_64
arm64
unknown
Definition at line 61 of file platform_detection.h.
{
    x86,
    x86_64,
    arm64,
    unknown
};
os_type
enum class kcenon::thread::platform::os_type strong
Operating system enumeration.
Enumerator
windows
macos
linux_os
unknown
Definition at line 71 of file platform_detection.h.
                   {
    windows,
    macos,
    linux_os,
    unknown
};
Function Documentation
get_arch_name()
const char * kcenon::thread::platform::get_arch_name () inline noexcept
Get architecture name string.
Definition at line 199 of file platform_detection.h.
{
    return THREAD_SYSTEM_ARCH_NAME;
}
References THREAD_SYSTEM_ARCH_NAME.
get_architecture()
cpu_architecture kcenon::thread::platform::get_architecture () inline noexcept
Get current CPU architecture.
Definition at line 95 of file platform_detection.h.
{
#if defined(THREAD_SYSTEM_ARCH_X64)
    return cpu_architecture::x86_64;
#elif defined(THREAD_SYSTEM_ARCH_ARM64)
    return cpu_architecture::arm64;
#elif defined(THREAD_SYSTEM_ARCH_X86)
    return cpu_architecture::x86;
#else
    return cpu_architecture::unknown;
#endif
}
References arm64, unknown, x86, and x86_64.
Referenced by get_system_info().
get_logical_core_count()
uint32_t kcenon::thread::platform::get_logical_core_count () inline noexcept
Get logical core count.
Definition at line 145 of file platform_detection.h.
{
    return static_cast<uint32_t>(std::thread::hardware_concurrency());
}
Referenced by get_system_info().
get_os()
os_type kcenon::thread::platform::get_os () inline noexcept
Get current operating system.
Definition at line 110 of file platform_detection.h.
{
#if defined(THREAD_SYSTEM_WINDOWS)
    return os_type::windows;
#elif defined(THREAD_SYSTEM_MACOS)
    return os_type::macos;
#elif defined(THREAD_SYSTEM_LINUX)
    return os_type::linux_os;
#else
    return os_type::unknown;
#endif
}
References linux_os, macos, unknown, and windows.
Referenced by get_system_info().
get_physical_core_count()
uint32_t kcenon::thread::platform::get_physical_core_count () inline noexcept
Get physical core count.
Definition at line 136 of file platform_detection.h.
{
    // std::thread::hardware_concurrency returns logical cores
    // For physical cores, platform-specific implementation needed
    return static_cast<uint32_t>(std::thread::hardware_concurrency());
}
Referenced by get_system_info().
get_platform_name()
const char * kcenon::thread::platform::get_platform_name () inline noexcept
Get platform name string.
Definition at line 192 of file platform_detection.h.
{
    return THREAD_SYSTEM_PLATFORM_NAME;
}
References THREAD_SYSTEM_PLATFORM_NAME.
get_system_info()
system_info kcenon::thread::platform::get_system_info () inline noexcept
Get comprehensive system information.
Definition at line 176 of file platform_detection.h.
{
    system_info info{};
    info.os = get_os();
    info.arch = get_architecture();
    info.physical_cores = get_physical_core_count();
    info.logical_cores = get_logical_core_count();
    info.efficiency_cores = 0;  // Platform-specific
    info.is_container = is_container_environment();
    info.is_arm64 = is_arm64();
    info.has_efficiency_cores = has_efficiency_cores();
    return info;
}
References get_architecture(), get_logical_core_count(), get_os(), get_physical_core_count(), has_efficiency_cores(), kcenon::thread::info, is_arm64(), is_container_environment(), and kcenon::thread::platform::system_info::os.
has_efficiency_cores()
bool kcenon::thread::platform::has_efficiency_cores () inline noexcept
Check if system has efficiency cores (Apple Silicon)
Definition at line 165 of file platform_detection.h.
{
#if defined(THREAD_SYSTEM_HAS_EFFICIENCY_CORES)
    return true;
#else
    return false;
#endif
}
Referenced by get_system_info().
is_arm64()
bool kcenon::thread::platform::is_arm64 () inline noexcept
Check if running on ARM64 architecture.
Definition at line 125 of file platform_detection.h.
{
#if defined(THREAD_SYSTEM_ARCH_ARM64)
    return true;
#else
    return false;
#endif
}
Referenced by get_system_info().
is_container_environment()
bool kcenon::thread::platform::is_container_environment () inline noexcept
Check if running in container environment.
Definition at line 152 of file platform_detection.h.
{
#if defined(THREAD_SYSTEM_LINUX)
    // Check for common container indicators
    // This is a simplified check; production code should be more thorough
    return false;  // Would check /proc/1/cgroup in real implementation
#else
    return false;
#endif
}
Referenced by get_system_info().