Thread System: kcenon::thread::diagnostics::job_execution_event Struct Reference
kcenon::thread::diagnostics::job_execution_event Struct Reference
Diagnostics
Event data for job execution tracing.
#include <execution_event.h>
Public Member Functions
auto format_timestamp () const -> std::string
Formats the event timestamp as ISO 8601 string.
auto wait_time_ms () const -> double
Converts wait_time to milliseconds.
auto execution_time_ms () const -> double
Converts execution_time to milliseconds.
auto is_terminal () const -> bool
Checks if this is a terminal event (job finished).
auto is_error () const -> bool
Checks if this event indicates an error.
auto to_json () const -> std::string
Converts the event to a JSON string.
auto to_string () const -> std::string
Converts the event to a human-readable string.
Public Attributes
std::uint64_t event_id {0}
Unique identifier for this event.
std::uint64_t job_id {0}
ID of the job this event relates to.
std::string job_name
Human-readable name of the job.
event_type type {event_type::enqueued}
Type of event that occurred.
std::chrono::steady_clock::time_point timestamp
Time when the event occurred.
std::chrono::system_clock::time_point system_timestamp
System time when the event occurred.
std::thread::id thread_id
ID of the thread that processed this event.
std::size_t worker_id {0}
Worker ID that processed this job.
std::chrono::nanoseconds wait_time {0}
Time spent waiting in queue before dequeue.
std::chrono::nanoseconds execution_time {0}
Time spent executing the job.
std::optional< int > error_code
Error code if the job failed.
std::optional< std::string > error_message
Error message if the job failed.
Detailed Description
Event data for job execution tracing.
Contains detailed information about a job execution event, suitable for logging, tracing, and monitoring purposes.
Event Flow
enqueued → dequeued → started → completed/failed/cancelled
                                 ↓
                              retried → started → ...
Usage Example
pool->diagnostics().add_event_listener(
    std::make_shared<MyEventLogger>()
);
// In MyEventLogger::on_event
void on_event(const job_execution_event& event) override {
    LOG_INFO("{} [job:{}] {}",
             event.format_timestamp(),
             event.job_name,
             event_type_to_string(event.type));
}
Definition at line 97 of file execution_event.h.
Member Function Documentation
execution_time_ms()
auto kcenon::thread::diagnostics::job_execution_event::execution_time_ms () const -> double inline nodiscard
Converts execution_time to milliseconds.
Returns
Execution time in milliseconds.
Definition at line 212 of file execution_event.h.
        {
            return std::chrono::duration<double, std::milli>(execution_time).count();
        }
References execution_time.
Referenced by to_json(), and to_string().
format_timestamp()
auto kcenon::thread::diagnostics::job_execution_event::format_timestamp () const -> std::string inline nodiscard
Formats the event timestamp as ISO 8601 string.
Returns
Formatted timestamp string.
Definition at line 185 of file execution_event.h.
        {
            auto time_t = std::chrono::system_clock::to_time_t(system_timestamp);
            auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                system_timestamp.time_since_epoch()) % 1000;
            char buffer[32];
            std::strftime(buffer, sizeof(buffer), "%Y-%m-%dT%H:%M:%S",
                          std::gmtime(&time_t));
            return std::string(buffer) + "." +
                   std::to_string(ms.count()) + "Z";
        }
References system_timestamp.
Referenced by to_json(), and to_string().
is_error()
auto kcenon::thread::diagnostics::job_execution_event::is_error () const -> bool inline nodiscard
Checks if this event indicates an error.
Returns
true if failed or cancelled.
Definition at line 232 of file execution_event.h.
        {
            return type == event_type::failed ||
                   type == event_type::cancelled;
        }
References kcenon::thread::diagnostics::cancelled, kcenon::thread::diagnostics::failed, and type.
is_terminal()
auto kcenon::thread::diagnostics::job_execution_event::is_terminal () const -> bool inline nodiscard
Checks if this is a terminal event (job finished).
Returns
true if completed, failed, or cancelled.
Definition at line 221 of file execution_event.h.
        {
            return type == event_type::completed ||
                   type == event_type::failed ||
                   type == event_type::cancelled;
        }
References kcenon::thread::diagnostics::cancelled, kcenon::thread::diagnostics::completed, kcenon::thread::diagnostics::failed, and type.
to_json()
auto kcenon::thread::diagnostics::job_execution_event::to_json () const -> std::string inline nodiscard
Converts the event to a JSON string.
Returns
JSON representation of the event.
Output format:
{
  "event_id": 123,
  "job_id": 456,
  "job_name": "ProcessOrder",
  "type": "completed",
  "timestamp": "2025-01-08T10:30:00.123Z",
  "thread_id": "12345",
  "worker_id": 0,
  "wait_time_ms": 1.5,
  "execution_time_ms": 10.2,
  "error_code": null,
  "error_message": null
}
Definition at line 259 of file execution_event.h.
        {
            std::ostringstream oss;
            oss << "{\n";
            oss << "  \"event_id\": " << event_id << ",\n";
            oss << "  \"job_id\": " << job_id << ",\n";
            oss << "  \"job_name\": \"" << job_name << "\",\n";
            oss << "  \"type\": \"" << event_type_to_string(type) << "\",\n";
            oss << "  \"timestamp\": \"" << format_timestamp() << "\",\n";
            // Format thread_id as string
            std::ostringstream tid_oss;
            tid_oss << thread_id;
            oss << "  \"thread_id\": \"" << tid_oss.str() << "\",\n";
            oss << "  \"worker_id\": " << worker_id << ",\n";
            oss << std::fixed << std::setprecision(3);
            oss << "  \"wait_time_ms\": " << wait_time_ms() << ",\n";
            oss << "  \"execution_time_ms\": " << execution_time_ms();
            if (error_code.has_value())
            {
                oss << ",\n  \"error_code\": " << error_code.value();
            }
            else
            {
                oss << ",\n  \"error_code\": null";
            }
            if (error_message.has_value())
            {
                oss << ",\n  \"error_message\": \"" << error_message.value() << "\"";
            }
            else
            {
                oss << ",\n  \"error_message\": null";
            }
            oss << "\n}";
            return oss.str();
        }
References error_message, event_id, kcenon::thread::diagnostics::event_type_to_string(), execution_time_ms(), format_timestamp(), job_name, thread_id, type, wait_time_ms(), and worker_id.
to_string()
auto kcenon::thread::diagnostics::job_execution_event::to_string () const -> std::string inline nodiscard
Converts the event to a human-readable string.
Returns
String representation of the event.
Output format:
[2025-01-08T10:30:00.123Z] Event#123 job:ProcessOrder#456 type:completed
  worker:0 thread:12345 wait:1.500ms exec:10.200ms
Definition at line 311 of file execution_event.h.
        {
            std::ostringstream oss;
            // First line: timestamp, event info, job info, type
            oss << "[" << format_timestamp() << "] ";
            oss << "Event#" << event_id << " ";
            oss << "job:" << job_name << "#" << job_id << " ";
            oss << "type:" << event_type_to_string(type) << "\n";
            // Second line: worker, thread, timing
            oss << "  worker:" << worker_id << " ";
            oss << "thread:" << thread_id << " ";
            oss << std::fixed << std::setprecision(3);
            oss << "wait:" << wait_time_ms() << "ms ";
            oss << "exec:" << execution_time_ms() << "ms";
            // Error info if present
            if (error_code.has_value() || error_message.has_value())
            {
                oss << "\n  error:";
                if (error_code.has_value())
                {
                    oss << " code=" << error_code.value();
                }
                if (error_message.has_value())
                {
                    oss << " msg=\"" << error_message.value() << "\"";
                }
            }
            return oss.str();
        }
References error_message, event_id, kcenon::thread::diagnostics::event_type_to_string(), execution_time_ms(), format_timestamp(), job_name, thread_id, type, wait_time_ms(), and worker_id.
wait_time_ms()
auto kcenon::thread::diagnostics::job_execution_event::wait_time_ms () const -> double inline nodiscard
Converts wait_time to milliseconds.
Returns
Wait time in milliseconds.
Definition at line 203 of file execution_event.h.
        {
            return std::chrono::duration<double, std::milli>(wait_time).count();
        }
References wait_time.
Referenced by to_json(), and to_string().
Member Data Documentation
error_code
std::optional<int> kcenon::thread::diagnostics::job_execution_event::error_code
Error code if the job failed.
Definition at line 170 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work().
error_message
std::optional<std::string> kcenon::thread::diagnostics::job_execution_event::error_message
Error message if the job failed.
Definition at line 175 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work(), to_json(), and to_string().
event_id
std::uint64_t kcenon::thread::diagnostics::job_execution_event::event_id {0}
Unique identifier for this event.
Monotonically increasing within the thread pool lifetime.
Definition at line 104 of file execution_event.h.
{0};
Referenced by to_json(), and to_string().
execution_time
std::chrono::nanoseconds kcenon::thread::diagnostics::job_execution_event::execution_time {0}
Time spent executing the job.
Only valid for completed, failed, cancelled events.
Definition at line 161 of file execution_event.h.
{0};
Referenced by kcenon::thread::thread_worker::do_work(), and execution_time_ms().
job_id
std::uint64_t kcenon::thread::diagnostics::job_execution_event::job_id {0}
ID of the job this event relates to.
Definition at line 109 of file execution_event.h.
{0};
Referenced by kcenon::thread::thread_worker::do_work().
job_name
std::string kcenon::thread::diagnostics::job_execution_event::job_name
Human-readable name of the job.
Definition at line 114 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work(), to_json(), and to_string().
system_timestamp
std::chrono::system_clock::time_point kcenon::thread::diagnostics::job_execution_event::system_timestamp
System time when the event occurred.
Used for logging and correlation with external systems.
Definition at line 131 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work(), and format_timestamp().
thread_id
std::thread::id kcenon::thread::diagnostics::job_execution_event::thread_id
ID of the thread that processed this event.
May be empty for enqueued events.
Definition at line 138 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work(), to_json(), and to_string().
timestamp
std::chrono::steady_clock::time_point kcenon::thread::diagnostics::job_execution_event::timestamp
Time when the event occurred.
Definition at line 124 of file execution_event.h.
Referenced by kcenon::thread::thread_worker::do_work().
type
event_type kcenon::thread::diagnostics::job_execution_event::type {event_type::enqueued}
Type of event that occurred.
Definition at line 119 of file execution_event.h.
{event_type::enqueued};
Referenced by kcenon::thread::thread_worker::do_work(), is_error(), is_terminal(), to_json(), and to_string().
wait_time
std::chrono::nanoseconds kcenon::thread::diagnostics::job_execution_event::wait_time {0}
Time spent waiting in queue before dequeue.
Only valid for dequeued, started events and later.
Definition at line 154 of file execution_event.h.
{0};
Referenced by kcenon::thread::thread_worker::do_work(), and wait_time_ms().
worker_id
std::size_t kcenon::thread::diagnostics::job_execution_event::worker_id {0}
Worker ID that processed this job.
Definition at line 143 of file execution_event.h.
{0};
Referenced by kcenon::thread::thread_worker::do_work(), to_json(), and to_string().
The documentation for this struct was generated from the following file:
include/kcenon/thread/diagnostics/execution_event.h