Thread System: kcenon::thread::hazard_pointer_domain< T >::thread_retire_list Struct Reference
kcenon::thread::hazard_pointer_domain< T >::thread_retire_list Struct Reference
Public Member Functions
size_t get_adaptive_threshold () const
void add (T *ptr)
size_t scan_and_reclaim (const std::vector< void * > &protected_ptrs)
void reclaim_all ()
~thread_retire_list ()
Public Attributes
detail::retire_node * head = nullptr
size_t count = 0
Static Public Attributes
static constexpr size_t BASE_RECLAIM_THRESHOLD = 64
static constexpr size_t RECLAIM_THRESHOLD_PER_THREAD = 16
Detailed Description
template<typename T>
struct kcenon::thread::hazard_pointer_domain< T >::thread_retire_list
Definition at line 205 of file hazard_pointer.h.
Constructor & Destructor Documentation
~thread_retire_list()
template<typename T > kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::~thread_retire_list ()
Definition at line 360 of file hazard_pointer.h.
{
    reclaim_all();
}
Member Function Documentation
add()
template<typename T > void kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::add (T * ptr)
Definition at line 299 of file hazard_pointer.h.
{
    auto* node = new detail::retire_node(static_cast<void*>(ptr),
                                         [](void* p) { delete static_cast<T*>(p); });
    node->next = head;
    head = node;
    ++count;
}
References kcenon::thread::detail::retire_node::next.
get_adaptive_threshold()
template<typename T > size_t kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::get_adaptive_threshold () const inline
Definition at line 216 of file hazard_pointer.h.
{
            auto& registry = detail::hazard_pointer_registry::instance();
            size_t active_threads = registry.get_active_thread_count();
            // Clamp between 64 and 512 to prevent extremes
            return std::min(size_t(512),
                            BASE_RECLAIM_THRESHOLD + active_threads * RECLAIM_THRESHOLD_PER_THREAD);
        }
reclaim_all()
template<typename T > void kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::reclaim_all ()
Definition at line 342 of file hazard_pointer.h.
{
    // 1. Try to reclaim what we can locally
    auto& registry = detail::hazard_pointer_registry::instance();
    auto protected_ptrs = registry.scan_hazard_pointers();
    scan_and_reclaim(protected_ptrs);
    // 2. Transfer ANY remaining nodes to GlobalReclamationManager
    // These are nodes that are still protected by other threads.
    // Instead of leaking them (or force deleting them which causes UAF),
    // we give them to the global manager to clean up later.
    if (head) {
        detail::global_reclamation_manager::instance().add_orphaned_nodes(head, count);
        head = nullptr;
        count = 0;
    }
}
References kcenon::thread::detail::global_reclamation_manager::add_orphaned_nodes(), kcenon::thread::detail::global_reclamation_manager::instance(), and kcenon::thread::detail::hazard_pointer_registry::instance().
scan_and_reclaim()
template<typename T > size_t kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::scan_and_reclaim (const std::vector< void * > & protected_ptrs)
Definition at line 309 of file hazard_pointer.h.
{
    size_t reclaimed = 0;
    detail::retire_node** curr = &head;
    while (*curr) {
        // Check if this pointer is protected
        bool is_protected = false;
        // Binary search since protected_ptrs is sorted
        if (std::binary_search(protected_ptrs.begin(), protected_ptrs.end(), (*curr)->ptr)) {
            is_protected = true;
        }
        if (!is_protected) {
            // Safe to reclaim
            detail::retire_node* to_delete = *curr;
            *curr = (*curr)->next;
            to_delete->deleter(to_delete->ptr);
            delete to_delete;
            ++reclaimed;
            --count;
        } else {
            // Keep in list
            curr = &(*curr)->next;
        }
    }
    return reclaimed;
}
References kcenon::thread::detail::retire_node::deleter, kcenon::thread::hazard_pointer::is_protected(), kcenon::thread::detail::retire_node::next, and kcenon::thread::detail::retire_node::ptr.
Member Data Documentation
BASE_RECLAIM_THRESHOLD
template<typename T > size_t kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::BASE_RECLAIM_THRESHOLD = 64 static constexpr
Definition at line 213 of file hazard_pointer.h.
count
template<typename T > size_t kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::count = 0
Definition at line 207 of file hazard_pointer.h.
head
template<typename T > detail::retire_node* kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::head = nullptr
Definition at line 206 of file hazard_pointer.h.
RECLAIM_THRESHOLD_PER_THREAD
template<typename T > size_t kcenon::thread::hazard_pointer_domain< T >::thread_retire_list::RECLAIM_THRESHOLD_PER_THREAD = 16 static constexpr
Definition at line 214 of file hazard_pointer.h.
The documentation for this struct was generated from the following file:
include/kcenon/thread/core/hazard_pointer.h