Thread System: examples/typed_thread_pool_sample/typed_thread_pool_sample.cpp File Reference
typed_thread_pool_sample.cpp File Reference
Typed thread pool with priority-based job routing using built-in job_types.
#include <iostream>
#include <memory>
#include <chrono>
#include <thread>
#include "logger/core/logger.h"
#include <kcenon/thread/utils/formatter.h>
#include <kcenon/thread/impl/typed_pool/typed_thread_pool.h>
#include <format>
Functions
auto initialize_logger () -> std::optional< std::string >
auto create_default (const uint16_t &high_priority_workers, const uint16_t &normal_priority_workers, const uint16_t &low_priority_workers) -> std::tuple< std::shared_ptr< typed_thread_pool >, std::optional< std::string > >
auto store_job (std::shared_ptr< typed_thread_pool > thread_pool) -> std::optional< std::string >
auto main () -> int
Variables
bool use_backup_ = false
uint32_t max_lines_ = 0
uint16_t wait_interval_ = 100
uint32_t test_line_count_ = 1000000
log_module::log_types file_target_ = log_module::log_types::None
log_module::log_types console_target_ = log_module::log_types::Information
log_module::log_types callback_target_ = log_module::log_types::None
uint16_t high_priority_workers_ = 3
uint16_t normal_priority_workers_ = 2
uint16_t low_priority_workers_ = 1
Detailed Description
Typed thread pool with priority-based job routing using built-in job_types.
Definition in file typed_thread_pool_sample.cpp.
Function Documentation
create_default()
auto create_default (const uint16_t & high_priority_workers, const uint16_t & normal_priority_workers, const uint16_t & low_priority_workers) -> std::tuple<std::shared_ptr<typed_thread_pool>, std::optional<std::string>>
Definition at line 64 of file typed_thread_pool_sample.cpp.
{
    std::shared_ptr<typed_thread_pool> pool;
    try
    {
        pool = std::make_shared<typed_thread_pool>();
    }
    catch (const std::bad_alloc& e)
    {
        return { nullptr, std::string(e.what()) };
    }
    std::optional<std::string> error_message = std::nullopt;
    std::vector<std::unique_ptr<typed_thread_worker>> workers;
    workers.reserve(high_priority_workers + normal_priority_workers + low_priority_workers);
    for (uint16_t i = 0; i < high_priority_workers; ++i)
    {
        workers.push_back(std::make_unique<typed_thread_worker>(
            std::vector<job_types>{ job_types::RealTime }, "high priority worker"));
    }
    for (uint16_t i = 0; i < normal_priority_workers; ++i)
    {
        workers.push_back(std::make_unique<typed_thread_worker>(
            std::vector<job_types>{ job_types::Batch }, "normal priority worker"));
    }
    for (uint16_t i = 0; i < low_priority_workers; ++i)
    {
        workers.push_back(std::make_unique<typed_thread_worker>(
            std::vector<job_types>{ job_types::Background }, "low priority worker"));
    }
    auto enqueue_result = pool->enqueue_batch(std::move(workers));
    if (enqueue_result.is_err())
    {
        return { nullptr, formatter::format("cannot enqueue to workers: {}",
                                            enqueue_result.error().message) };
    }
    return { pool, std::nullopt };
}
References kcenon::thread::utils::formatter::format().
Referenced by main().
initialize_logger()
auto initialize_logger () -> std::optional<std::string>
Definition at line 43 of file typed_thread_pool_sample.cpp.
{
    log_module::set_title("typed_thread_pool_sample");
    log_module::set_use_backup(use_backup_);
    log_module::set_max_lines(max_lines_);
    log_module::file_target(file_target_);
    log_module::console_target(console_target_);
    log_module::callback_target(callback_target_);
    // Note: This demonstrates the logger callback feature - std::cout is intentionally used here
    log_module::message_callback(
        [](const log_module::log_types& type, const std::string& datetime,
           const std::string& message)
        { std::cout << formatter::format("[{}][{}] {}\n", datetime, type, message); });
    if (wait_interval_ > 0)
    {
        log_module::set_wake_interval(std::chrono::milliseconds(wait_interval_));
    }
    return log_module::start();
}
References callback_target_, console_target_, file_target_, kcenon::thread::utils::formatter::format(), max_lines_, use_backup_, and wait_interval_.
Referenced by main().
main()
auto main () -> int
Definition at line 143 of file typed_thread_pool_sample.cpp.
{
    auto error_message = initialize_logger();
    if (error_message.has_value())
    {
        std::cerr << formatter::format("error starting logger: {}\n",
                                       error_message.value_or("unknown error"));
        return 0;
    }
    std::shared_ptr<typed_thread_pool> thread_pool = nullptr;
    std::tie(thread_pool, error_message)
        = create_default(high_priority_workers_, normal_priority_workers_, low_priority_workers_);
    if (error_message.has_value())
    {
        log_module::write_error("error creating thread pool: {}",
                                error_message.value_or("unknown error"));
        return 0;
    }
    log_module::write_information("created {}", thread_pool->to_string());
    error_message = store_job(thread_pool);
    if (error_message.has_value())
    {
        log_module::write_error("error storing job: {}", error_message.value_or("unknown error"));
        thread_pool.reset();
        return 0;
    }
    auto start_result = thread_pool->start();
    if (start_result.is_err())
    {
        log_module::write_error("error starting thread pool: {}",
                                start_result.error().message);
        thread_pool.reset();
        return 0;
    }
    log_module::write_information("started {}", thread_pool->to_string());
    {
        auto stop_result = thread_pool->stop();
        if (stop_result.is_err()) {
            log_module::write_error("error stopping thread pool: {}", stop_result.error().message);
        }
    }
    log_module::write_information("stopped {}", thread_pool->to_string());
    thread_pool.reset();
    log_module::stop();
    return 0;
}
References create_default(), kcenon::thread::utils::formatter::format(), high_priority_workers_, initialize_logger(), low_priority_workers_, normal_priority_workers_, kcenon::thread::thread_pool::start(), kcenon::thread::thread_pool::stop(), store_job(), and kcenon::thread::thread_pool::to_string().
store_job()
auto store_job (std::shared_ptr< typed_thread_pool > thread_pool) -> std::optional<std::string>
Definition at line 112 of file typed_thread_pool_sample.cpp.
{
    int target = 0;
    std::vector<std::unique_ptr<typed_job>> jobs;
    jobs.reserve(test_line_count_);
    for (auto index = 0; index < test_line_count_; ++index)
    {
        target = index % 3;
        jobs.push_back(std::make_unique<callback_typed_job>(
            [target](void) -> kcenon::common::VoidResult
            {
                log_module::write_debug("Hello, World!: {} priority", target);
                return kcenon::common::ok();
            },
            static_cast<job_types>(target)));
    }
    auto enqueue_result = thread_pool->enqueue_batch(std::move(jobs));
    if (enqueue_result.is_err())
    {
        return formatter::format("error enqueuing jobs: {}",
                                 enqueue_result.error().message);
    }
    log_module::write_sequence("enqueued jobs: {}", test_line_count_);
    return std::nullopt;
}
References kcenon::thread::thread_pool::enqueue_batch(), kcenon::thread::utils::formatter::format(), and test_line_count_.
Referenced by main().
Variable Documentation
callback_target_
log_module::log_types callback_target_ = log_module::log_types::None
Definition at line 37 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().
console_target_
log_module::log_types console_target_ = log_module::log_types::Information
Definition at line 36 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().
file_target_
log_module::log_types file_target_ = log_module::log_types::None
Definition at line 35 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().
high_priority_workers_
uint16_t high_priority_workers_ = 3
Examples
typed_thread_pool_sample.cpp.
Definition at line 39 of file typed_thread_pool_sample.cpp.
Referenced by main().
low_priority_workers_
uint16_t low_priority_workers_ = 1
Examples
typed_thread_pool_sample.cpp.
Definition at line 41 of file typed_thread_pool_sample.cpp.
Referenced by main().
max_lines_
uint32_t max_lines_ = 0
Definition at line 32 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().
normal_priority_workers_
uint16_t normal_priority_workers_ = 2
Examples
typed_thread_pool_sample.cpp.
Definition at line 40 of file typed_thread_pool_sample.cpp.
Referenced by main().
test_line_count_
uint32_t test_line_count_ = 1000000
Definition at line 34 of file typed_thread_pool_sample.cpp.
Referenced by store_job().
use_backup_
bool use_backup_ = false
Definition at line 31 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().
wait_interval_
uint16_t wait_interval_ = 100
Definition at line 33 of file typed_thread_pool_sample.cpp.
Referenced by initialize_logger().