var searchData=
[
  ['parameter_0',['Parameter',['../d9/de0/namespacelog__module.html#ac59af6ec9704b7fd0d73e7becbc54709a83f499a540b1323009c200d6f8cc9396',1,'log_module']]],
  ['parse_1',['parse',['../d1/dec/classutility__module_1_1enum__formatter.html#a4865828c30d45b4a4ab6270ece0f5404',1,'utility_module::enum_formatter::parse()'],['../de/d30/classutility__module_1_1argument__manager.html#a8c717ac27d873d26ac1b5f741a4d9999',1,'utility_module::argument_manager::parse()']]],
  ['parsing_20conventions_2',['Parsing Conventions',['../de/d30/classutility__module_1_1argument__manager.html#autotoc_md47',1,'']]],
  ['performance_20benchmarks_3',['📈 Performance Benchmarks',['../index.html#benchmarks',1,'']]],
  ['performance_20characteristics_4',['Performance Characteristics',['../index.html#performance_characteristics',1,'']]],
  ['performance_20considerations_5',['performance considerations',['../d4/df8/classpriority__thread__pool__module_1_1priority__thread__pool__t.html#autotoc_md6',1,'Performance Considerations'],['../d9/da1/classthread__pool__module_1_1thread__pool.html#autotoc_md44',1,'Performance Considerations']]],
  ['performance_20excellence_6',['🚀 Performance Excellence',['../index.html#performance',1,'']]],
  ['pin_5fthreads_5fto_5fcores_7',['pin_threads_to_cores',['../d6/dc0/structthread__pool__module_1_1thread__pool__config.html#ab133fd652c4f0063088f1cb9bb1c5267',1,'thread_pool_module::thread_pool_config']]],
  ['planned_20enhancements_8',['🚀 Planned Enhancements',['../index.html#planned_features',1,'']]],
  ['pool_20system_20priority_5fthread_5fpool_5fmodule_9',['Priority Thread Pool System (priority_thread_pool_module)',['../index.html#priority_thread_pool',1,'']]],
  ['pool_20system_20thread_5fpool_5fmodule_10',['Thread Pool System (thread_pool_module)',['../index.html#thread_pool',1,'']]],
  ['principles_11',['principles',['../d9/da1/classthread__pool__module_1_1thread__pool.html#autotoc_md42',1,'Design Principles'],['../index.html#design_principles',1,'Design Principles']]],
  ['priorities_12',['priorities',['../d5/d22/classpriority__thread__pool__module_1_1priority__thread__worker__t.html#a01d4119d950267422c9712e0293e9b15',1,'priority_thread_pool_module::priority_thread_worker_t']]],
  ['priorities_5f_13',['priorities_',['../d5/d22/classpriority__thread__pool__module_1_1priority__thread__worker__t.html#a77ab8ff57249aaed604fbff88040c227',1,'priority_thread_pool_module::priority_thread_worker_t']]],
  ['priority_14',['priority',['../d7/dce/classpriority__thread__pool__module_1_1priority__job__t.html#a7c621bc2dace12ddf09dfeb0863243d0',1,'priority_thread_pool_module::priority_job_t']]],
  ['priority_20thread_20pool_20system_20priority_5fthread_5fpool_5fmodule_15',['Priority Thread Pool System (priority_thread_pool_module)',['../index.html#priority_thread_pool',1,'']]],
  ['priority_5f_16',['priority_',['../d7/dce/classpriority__thread__pool__module_1_1priority__job__t.html#a4523ca3b0d1215f4a6da7e9cdb20a4f7',1,'priority_thread_pool_module::priority_job_t']]],
  ['priority_5fjob_17',['priority_job',['../d8/da5/namespacepriority__thread__pool__module.html#a0d1f63df9460984a01c3b44bed3e0f38',1,'priority_thread_pool_module']]],
  ['priority_5fjob_2eh_18',['priority_job.h',['../da/d1e/priority__job_8h.html',1,'']]],
  ['priority_5fjob_2etpp_19',['priority_job.tpp',['../db/da2/priority__job_8tpp.html',1,'']]],
  ['priority_5fjob_5fqueue_20',['priority_job_queue',['../d8/da5/namespacepriority__thread__pool__module.html#a052133f790e63c78a7d12f09d3cd37c5',1,'priority_thread_pool_module']]],
  ['priority_5fjob_5fqueue_2eh_21',['priority_job_queue.h',['../d1/d8b/priority__job__queue_8h.html',1,'']]],
  ['priority_5fjob_5fqueue_2etpp_22',['priority_job_queue.tpp',['../df/d51/priority__job__queue_8tpp.html',1,'']]],
  ['priority_5fjob_5fqueue_5ft_23',['priority_job_queue_t',['../d5/db9/classpriority__thread__pool__module_1_1priority__job__queue__t.html#ac0534e8e1857910d43c4ea4acbdfac83',1,'priority_thread_pool_module::priority_job_queue_t::priority_job_queue_t()'],['../d5/db9/classpriority__thread__pool__module_1_1priority__job__queue__t.html',1,'priority_thread_pool_module::priority_job_queue_t&lt; priority_type &gt;']]],
  ['priority_5fjob_5fqueue_5ft_3c_20job_5fpriorities_20_3e_24',['priority_job_queue_t&lt; job_priorities &gt;',['../d5/db9/classpriority__thread__pool__module_1_1priority__job__queue__t.html',1,'priority_thread_pool_module']]],
  ['priority_5fjob_5fqueue_5ft_3c_20priority_5ftype_20_3e_25',['priority_job_queue_t&lt; priority_type &gt;',['../d5/db9/classpriority__thread__pool__module_1_1priority__job__queue__t.html',1,'priority_thread_pool_module']]],
  ['priority_5fjob_5ft_26',['priority_job_t',['../d7/dce/classpriority__thread__pool__module_1_1priority__job__t.html#a85200cd44cab22eb8013da64f6a03ebc',1,'priority_thread_pool_module::priority_job_t::priority_job_t()'],['../d7/dce/classpriority__thread__pool__module_1_1priority__job__t.html',1,'priority_thread_pool_module::priority_job_t&lt; priority_type &gt;']]],
  ['priority_5fjob_5ft_3c_20job_5fpriorities_20_3e_27',['priority_job_t&lt; job_priorities &gt;',['../d7/dce/classpriority__thread__pool__module_1_1priority__job__t.html',1,'priority_thread_pool_module']]],
  ['priority_5fthread_5fpool_28',['priority_thread_pool',['../d8/da5/namespacepriority__thread__pool__module.html#a41ef2e79bef51fd16d3289eb9272118b',1,'priority_thread_pool_module']]],
  ['priority_5fthread_5fpool_2eh_29',['priority_thread_pool.h',['../dd/d10/priority__thread__pool_8h.html',1,'']]],
  ['priority_5fthread_5fpool_2etpp_30',['priority_thread_pool.tpp',['../df/d1d/priority__thread__pool_8tpp.html',1,'']]],
  ['priority_5fthread_5fpool_5fmodule_31',['priority_thread_pool_module',['../index.html#priority_thread_pool',1,'Priority Thread Pool System (priority_thread_pool_module)'],['../d8/da5/namespacepriority__thread__pool__module.html',1,'priority_thread_pool_module']]],
  ['priority_5fthread_5fpool_5fmodule_3a_3ajob_5fdetail_32',['job_detail',['../d8/dc9/namespacepriority__thread__pool__module_1_1job__detail.html',1,'priority_thread_pool_module']]],
  ['priority_5fthread_5fpool_5ft_33',['priority_thread_pool_t',['../d4/df8/classpriority__thread__pool__module_1_1priority__thread__pool__t.html#a673450d019a2e1e389585a37d0d7c085',1,'priority_thread_pool_module::priority_thread_pool_t::priority_thread_pool_t()'],['../d4/df8/classpriority__thread__pool__module_1_1priority__thread__pool__t.html',1,'priority_thread_pool_module::priority_thread_pool_t&lt; priority_type &gt;']]],
  ['priority_5fthread_5fworker_34',['priority_thread_worker',['../d8/da5/namespacepriority__thread__pool__module.html#ab2acdb902539e5d69fb8bf7b0512a14f',1,'priority_thread_pool_module']]],
  ['priority_5fthread_5fworker_2eh_35',['priority_thread_worker.h',['../db/dc2/priority__thread__worker_8h.html',1,'']]],
  ['priority_5fthread_5fworker_2etpp_36',['priority_thread_worker.tpp',['../d0/dea/priority__thread__worker_8tpp.html',1,'']]],
  ['priority_5fthread_5fworker_5ft_37',['priority_thread_worker_t',['../d5/d22/classpriority__thread__pool__module_1_1priority__thread__worker__t.html',1,'priority_thread_pool_module::priority_thread_worker_t&lt; priority_type &gt;'],['../d5/d22/classpriority__thread__pool__module_1_1priority__thread__worker__t.html#abd10b8fece26de7794c6f01928fe9edd',1,'priority_thread_pool_module::priority_thread_worker_t::priority_thread_worker_t()']]],
  ['priority_5fthread_5fworker_5ft_3c_20job_5fpriorities_20_3e_38',['priority_thread_worker_t&lt; job_priorities &gt;',['../d5/d22/classpriority__thread__pool__module_1_1priority__thread__worker__t.html',1,'priority_thread_pool_module']]],
  ['production_20grade_20reliability_39',['🛡️ Production-Grade Reliability',['../index.html#reliability',1,'']]],
  ['productivity_40',['🔧 Developer Productivity',['../index.html#productivity',1,'']]],
  ['promise_5ftype_41',['promise_type',['../de/d6e/classthread__pool__module_1_1task.html#a2d38e8089dfd3c582b9e4c9dcbf957ee',1,'thread_pool_module::task']]]
];
