name: Build-Fedora-Clang

on:
  push:
    branches:
      - main
      - release**
  pull_request:
    branches:
      - main
      - release**
  workflow_dispatch:

jobs:
  build_fedora_clang:
    permissions:
      contents: write
    runs-on: fedora-latest
    timeout-minutes: 60
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: kcenon/thread_system
          ssh-strict: true
          ssh-user: git
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          show-progress: true
          lfs: false
          set-safe-directory: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      
      - name: Install dependencies
        run: |
          dnf update -y
          dnf groupinstall -y "Development Tools"
          dnf install -y cmake clang clang-tools-extra lld lldb pkgconfig curl zip unzip tar
          dnf install -y autoconf automake autoconf-archive git libc++-devel libc++abi-devel

      - name: Check architecture and set environment variable if needed
        run: |
          if [ $(uname -m) == "aarch64" ]; then
            echo "VCPKG_FORCE_SYSTEM_BINARIES=arm" >> $GITHUB_ENV
          fi
      
      - name: Cache vcpkg
        uses: actions/cache@v3
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            !${{ github.workspace }}/vcpkg/buildtrees
            !${{ github.workspace }}/vcpkg/packages
            !${{ github.workspace }}/vcpkg/downloads
          key: fedora-clang-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Set up vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            git clone https://github.com/Microsoft/vcpkg.git
          fi
          cd vcpkg
          git pull
          ./bootstrap-vcpkg.sh
          cd ..

      - name: Cache vcpkg installed
        uses: actions/cache@v3
        id: vcpkg-installed
        with:
          path: ${{ github.workspace }}/vcpkg_installed
          key: fedora-clang-vcpkg-installed-${{ hashFiles('**/vcpkg.json') }}

      - name: Install dependencies with vcpkg
        if: steps.vcpkg-installed.outputs.cache-hit != 'true'
        run: |
          ./vcpkg/vcpkg install --x-manifest-root=. --x-install-root=${{ github.workspace }}/vcpkg_installed

      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
          key: fedora-clang-cmake-${{ hashFiles('CMakeLists.txt', 'vcpkg.json') }}
          restore-keys: |
            fedora-clang-cmake-

      - name: Build application with Clang
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_TESTS=ON -DCMAKE_INSTALL_PREFIX="../target" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++"
          cmake --build .

      - name: Cache built libraries
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build
          key: fedora-clang-built-libs-${{ hashFiles('CMakeLists.txt', 'vcpkg.json', 'src/**/*.cpp', 'src/**/*.h') }}
          restore-keys: |
            fedora-clang-built-libs-